### ISSUE TITLE
sibbay众合的规范讨论

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#1]
# 0、目的
尝试建立有偿的社区化贡献机制。
# 1、人员：
## Contributor
熟悉Sibbay的流程
- issue
- commit
- review
- pull request
## Committer
- 有Contributor的所有权利
- push
- merge
- 工作量核定
- 提名活跃Contributor升级为Committer
## Maintainer
- 有Committer的所有权利
- 参与投票决策
## 仅与个人合作
# 2、issue就是一切
**凡没有在issue中讨论过的，都没有发生。**
issue的label规范：。。。
# 3、管理
**MGM**(Meritocratic Governance Model)采取apache的精英治理模型
# 4、贡献者指南
# 4.1、issue
提交规范
# 4.2、PR
PR的checklist：
 - [ ] 相关的issue已经关联了
 - [ ] 是否编写了相关的unittest（后端）
 - [ ] 提交时以运行了full test（后端）
# 5、贡献者奖励
lablel:D0.1 D0.2 D0.5  D1  D2   D??
Contributor每个D奖励单价为RMB500 或等值（token）
Commiter每个D奖励单价为RMB700 或等值（token）
每月15日统计
现金通过mart.coding.net或zbj.com发放，税费自负。
token直接发放

# 资料：
http://www.infoq.com/cn/articles/apache-foundation-the-success-of-apache/
https://www.qcloud.com/community/article/570793?romSource=gwzcw.114001.114001.114001
stackexchange的机制：https://www.zhihu.com/question/21037078

**Comment by georgeliuyu** [comment]
这是宋亮写的执行细节：https://github.com/sibbay-ai/lt-miniapp/wiki/pay-for-bug

**Comment by georgeliuyu** [comment]
问题：
1、贡献者是否需要认证？
2、提交者的产生细则能定工作量吗？
3、需求确定和方向确定？

**Comment by ben7th** [comment]
我的想法：

- 贡献者需要认证，且长远来说，需要认证体系。
  目前进行的“阅读代码并尝试写例子”就是一种简单的认证。
  将来这种认证需要变得更自动化，阶梯化

- 这种细则基于现有条件不容易制定与执行。换言之，不存在软件开发的通用细则。也许存在特定项目，特定开发框架，特定过程管理方法 + 工具驱动的细则。

- 需求由三种动力驱动：
  - 长期：团队愿景
  - 中期：运营目标
  - 短期：用户直接反馈

**Comment by ben7th** [comment]
要点：

- 针对所有贡献者建立竞争机制
- 针对所有贡献者建立评价体系

**Comment by georgeliuyu** [comment]
@ben7th @fushang318 @sinchb 大家对这种角色划分是否有意见：
## Contibutor
issue
commit
review
pull request
## Committer
有Contributor的所有权利
push
merge
工作量核定
提名活跃Contributor升级为Committer

**Comment by georgeliuyu** [comment]
@ben7th @fushang318 @sinchb 对贡献者的认证是否可以采用issue和pr的数量和质量进行自动评价。

**Comment by georgeliuyu** [comment]
工作量的确定，其实就是对需求和fix bug的issue进行定价。

**Comment by ben7th** [comment]
@georgeliuyu @fushang318 @sinchb 

对于非开源项目来说，同意上述角色划分。

目前我们在非开源项目的运作方式之下，实际上是由 committer 通过对新参与者的“读代码/尝试编码”的任务进行 review 之后，使其成为 contibutor 的。

也就是说，一开始会有一个“准入”的过程。之后若建立等级体系，才是用 issue 和 pr 的数量质量来评价。

另外，要维持开发者社区运转，还有两项必要工作：

1. 开发文档的撰写/维护（决定了一些知识能否存续）
2. 需求的提出以及围绕需求进行的设计工作

contibutor 和 committer 围绕上述两项工作，具体完成什么任务，以及上述任务是否也能归纳到目前 issue/commit/pr 的体系中来，需要考虑。我会考虑后给出我的意见。

**Comment by georgeliuyu** [comment]
@ben7th 赞同归纳到icp（issue、commit、pr）的体系中。

**Comment by georgeliuyu** [comment]
@pimgeek 你的意见是对的，不过现在更多focus在组织的管理方式上，也即如何围绕icp（issue/commit/pr为核心来展开组织和管理。也即每个Contributor仅仅只需要关注项目的issue就能方便的参与进来，并且能清楚的预期自己的收益。

**Comment by alwaysloseall** [comment]
根据这条信息：
>
贡献者需要认证，且长远来说，需要认证体系。
目前进行的“阅读代码并尝试写例子”就是一种简单的认证。
将来这种认证需要变得更自动化，阶梯化
想了解一下：如何参与sibbay众合贡献代码，如何进行认证

**Comment by fushang318** [comment]
@alwaysloseall 
目前还没有一个完善的认证体系  
目前认证基本包括如下几个方面：
1. 个人参与
2. 通过沟通，了解基本的做事规则和流程
3. 拥有的某方面技能可以胜任这方面的工作（比如后端开发人员需要可以会XX技能这类的）
3. 通过完成一个包，基本熟悉了相关业务，也就是通过这个包为入口逐渐和其他成员相互熟悉

现在 sibbay 每周会有一个周报（公开阅读的），里面有汇总发包内容，以及其他工作进度这类的内容

**Comment by ben7th** [comment]
文档已合并，此 issue 关闭
