### ISSUE TITLE
针对开发者的 ICP 规范以及操作方法的讲解视频

### ISSUE THREAD

**Issue by ben7th** [sibbay-ai/public#100]
为帮助各位开发者熟悉 ICP 规范下的开发工作接受/提交方法，以及费用计算和支付方式。
录制了两段视频供大家观看。

这次视频主要针对程序开发者，对于非开发者的小白贡献者们，将通过一段时间的实践后，了解大家的定期/不定期工作和提交内容后，对操作方法提出建议。

视频可以直接通过浏览器打开在线观看。

#### 视频一：ICP 介绍和规范文档导读
[video-1 在线观看地址](http://sibbay-files.oss-cn-hangzhou.aliyuncs.com/icp_tutorial/1.mp4) (18′17″)

#### 视频二：在 ICP 规范下的代码提交操作示例
[video-2 在线观看地址](http://sibbay-files.oss-cn-hangzhou.aliyuncs.com/icp_tutorial/2.mp4) (22′10″)

以下被 @ 到的，正在参与小白工作的开发者，自由找时间观看视频，提出问题/建议，并在 1 月 8 号（周一）前回复到这个 issue, 每个开发者都需要回复. 届时将对大家的问题进行整理，形成 FAQ

------------------

@ben7th @lixinxuan @arnkorty @Yidadaa @pimgeek @fushang318 @choufeng @NiuShy @bqx619 @yeyuexia @sinchb @ax003d @wb14123
  
人数比较多，assign 最多指定十个，committer 就不再 assign 了

**Comment by georgeliuyu** [comment]
@ben7th 建议补充到readme中

**Comment by ben7th** [comment]
@georgeliuyu 已经发 pr 了，还没有合并
https://github.com/sibbay-ai/public/pull/92

**Comment by bqx619** [comment]
@ben7th 
1. 两个视频已经学习观看.
2. 提出一点小口误:
在两个视频中, 描述申请`ICP`的格式时, 指出应该是 **@bqx619 申请开发 Size：xx Deadline：2017-12-5** , 是在 ISSUS 中@自己申请这种格式, 但是在`icp 奖励机制`文档和已经**In Progress**的 ISSUS 中均是以@此 ISSUS 的committer的方式.似乎是一个小口误
3. 一个小问题:review和申请`ICP`是否限定了开发组别?比如前端的在熟悉`Python`的基础上是否可以参与到其余`ICP`的申请或是review之中?有哪些约束?

最后, 感谢制作引导视频, 是一个优秀的**speaker**!

**Comment by ben7th** [comment]
@bqx619 

谢谢指正！

确实口误了，其实 @ 谁不是特别重要，如果 committer 是发 issue 的人，回复时他就会看到。一般需要通知谁看到这个 issue 的时候，就去 @ 他。ICP 申请格式重点在于写明白 size 和 deadline 就可以了

申请 ICP 不限组别，可以参与各种 ICP 的申请，但是否指派需要由 committer 确定，committer 有时会采取指派另一个“证明有能力参与”的工作的形式来确定开发能力。

review 默认是任务对应的 committer 进行，其他开发者参与 review 需 committer 事先认可。也可随时向 committer 表明参与 review 的意愿

**Comment by bqx619** [comment]
@ben7th 了解了，谢谢！

**Comment by fushang318** [comment]
已经使用了新的ICP规范
