### ISSUE TITLE
icp管理流程图：标准版+简易版（非专业人员使用）

### ISSUE THREAD

**Issue by AmberGN** [sibbay-ai/public#101]
了解熟悉小白健康的icp管理流程，并交付以下内容：
1. 整理出一份标准版流程图，便于新同学快速了解整个icp管理流程
2. 设计并整理一份简易版流程图，供非专业人员使用，目标是能直接通过网页端进行所有操作，并对交付件进行相应的规定。

**Comment by georgeliuyu** [comment]
@AmberGN 你自己按照icp流程，申请一下这个issue。

**Comment by AmberGN** [comment]
@AmberGN 申请开发 Size：2 Deadline：2018-1-15

**Comment by georgeliuyu** [comment]
@AmberGN 你应该@的是我。怎么会自己@自己。

**Comment by AmberGN** [comment]
之前理解错格式了，重发一遍
@georgeliuyu 申请开发 Size：2 Deadline：2018-1-15

**Comment by georgeliuyu** [comment]
@AmberGN 同意

**Comment by fushang318** [comment]
icp流程图已经做完了
