### ISSUE TITLE
小白项目贡献者（maohuaming）ICP认证测试

### ISSUE THREAD

**Issue by maohuaming** [sibbay-ai/public#102]
| 项目  | 结果  |
|---|---|
| 申请者  | _github账号_ | 
| mentor  | _github账号_ | 
| icp流程测试 | _pr链接 及size数量_| 
| icp理解测试 | _issue链接_ |
| 协作测试 | _申请者耗时（小时）/协作者耗时（小时_ |
| issue响应速度 | _分钟/次_  |

**Comment by maohuaming** [comment]
@georgeliuyu 申请认证 Size 3 Deadline：2018-01-16

**Comment by georgeliuyu** [comment]
@maohuaming 这个是一个测试的结果issue，不用进行请求。而是要将上面的表实现完成。

**Comment by georgeliuyu** [comment]
@maohuaming 没有收到你认证测试issue的提醒。

**Comment by georgeliuyu** [comment]
![image](https://user-images.githubusercontent.com/16983441/34856612-f5d70440-f780-11e7-842e-3d30cea41a20.png)

**Comment by maohuaming** [comment]
@georgeliuyu 已经在我自己的github上建立了一个测试用的repo并创建master和develop两个分支，请参见：https://github.com/maohuaming/sibbay-test

**Comment by fushang318** [comment]
已经认证完了
