### ISSUE TITLE
关于规范执行ICP流程的通知

### ISSUE THREAD

**Issue by shero3** [sibbay-ai/public#103]
1.	小白健康遵循“凡没有在 issue 中记录的，都没有发生”的宗旨，所以所有ICP相关的工作都必须以issue的形式记录并完成，在申请时必须按照规范申请，即申请者在该 issue 上提交申请留言时必须包含以下内容：
（1）@committer 
（2）Size：
（3）Deadline：
以上要求同样适用于申请者自己创建的issue。

2.	任务由 committer 指定 contributor后，在执行过程中对issue的记录必须符合规范， 
规范详见：https://github.com/sibbay-ai/public/blob/master/issue%20%E8%A7%84%E8%8C%83.md

3.	对于deadline超期的icp任务（以merge的时间为准），必须提交特别说明（原因和改进方法），需经committer认可，由shero跟进电话交流后，提交刘总审核同意

4.	以上规范从本月起实施，本月结算ICP前不规范的issue请尽快修改。

**请各位ICP贡献者阅读后在此issue中回复“已阅读”确认已知悉相关通知！**

**Comment by ben7th** [comment]
已阅读

**Comment by fazhen** [comment]
已阅读

**Comment by pimgeek** [comment]
@pimeek 已经阅读此通知。

**Comment by Yidadaa** [comment]
已阅读

**Comment by bqx619** [comment]
已阅读

**Comment by arnkorty** [comment]
已阅读

**Comment by fushang318** [comment]
已阅读

**Comment by wb14123** [comment]
已阅读

**Comment by sinchb** [comment]
已阅读

**Comment by sinchb** [comment]
@ben7th deadline 写在comment下，还是以label形式记录？

**Comment by alisahuxu** [comment]
已阅读

**Comment by pimgeek** [comment]
@sinchb 我建议在 comment 中提及 deadline，但一定要用更可靠的方式记录，因为：

1. comment 可以被其发起者重新编辑
2. comment 被重新编辑后，未显示详细的编辑历史，只显示了“谁曾经于何时编辑过该 comment”

更可靠的方式可以是 label 也可以是别的，但似乎应避免 “无法准确回溯更改历史” 的问题。

**Comment by shero3** [comment]
@Yidadaa @lixinxuan  @NiuShy  @yeyuexia @ax003d   请尽快阅读通知并按要求回复，谢谢

**Comment by NiuShy** [comment]
已阅读

**Comment by ax003d** [comment]
已阅读

**Comment by lixinxuan** [comment]
已阅读

**Comment by yeyuexia** [comment]
已阅读

**Comment by choufeng** [comment]
已阅读
