### ISSUE TITLE
小白项目贡献者（AmberGN）icp认证测试

### ISSUE THREAD

**Issue by AmberGN** [sibbay-ai/public#104]
| 项目  | 结果  |
|---|---|
| 申请者  | _AmberGN_ | 
| mentor  | _georgeliuyu_ | 
| icp流程测试 | _pr链接 及size数量_| #
| icp理解测试 | _issue链接_ |
| 协作测试 | _申请者耗时（小时）/协作者耗时（小时_ |
| issue响应速度 | _分钟/次_  |

**Comment by georgeliuyu** [comment]
@AmberGN 我没有收到你认证测试issue的提醒

**Comment by AmberGN** [comment]
@georgeliuyu 已发icp流程测试和理解测试的issue，请查看

**Comment by AmberGN** [comment]
| 项目  | 结果  |
|---|---|
| 申请者  | _AmberGN_ | 
| mentor  | _georgeliuyu_ | 
| icp流程测试 | [icp需求issue对应的pr](https://github.com/AmberGN/sibbay-ai-certification/pull/2) /[icp BUG issue对应的pr](https://github.com/AmberGN/sibbay-ai-certification/pull/4) / size 0.4 | #
| icp理解测试 | [icp理解测试](https://github.com/AmberGN/sibbay-ai-certification/issues/5) |
| 协作测试 | _申请者耗时（0.2小时）/协作者耗时（0.2小时）_ |
| issue响应速度 | _58分钟/次_  |
