### ISSUE TITLE
设法编写并成功运行一个结构和功能均比较完整 MRI 互动脚本，然后提交 Pull Request 并通过审核（仿真环境），最后把学会的部分制作为视频教程（进阶）。

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/public#107]
需求来源： #66 #71
来源：https://github.com/sibbay-ai/mri-learning/blob/master/mri-simulator-trial-use-report.md#222-%E8%AE%BE%E6%B3%95%E7%BC%96%E5%86%99%E5%B9%B6%E6%88%90%E5%8A%9F%E8%BF%90%E8%A1%8C%E4%B8%80%E4%B8%AA%E7%BB%93%E6%9E%84%E5%92%8C%E5%8A%9F%E8%83%BD%E5%9D%87%E6%AF%94%E8%BE%83%E5%AE%8C%E6%95%B4-mri-%E4%BA%92%E5%8A%A8%E8%84%9A%E6%9C%AC%E7%84%B6%E5%90%8E%E6%8F%90%E4%BA%A4-pull-request-%E5%B9%B6%E9%80%9A%E8%BF%87%E5%AE%A1%E6%A0%B8%E4%BB%BF%E7%9C%9F%E7%8E%AF%E5%A2%83%E6%9C%80%E5%90%8E%E6%8A%8A%E5%AD%A6%E4%BC%9A%E7%9A%84%E9%83%A8%E5%88%86%E5%88%B6%E4%BD%9C%E4%B8%BA%E8%A7%86%E9%A2%91%E6%95%99%E7%A8%8B%E8%BF%9B%E9%98%B6

根据立会讨论，可能场景还需要好好想想

**Comment by pimgeek** [comment]
@fushang318 
1. 医学问询场景调研，需要与医学工作者沟通，初定与贾老师等二人沟通 1~2 次，总计 4 小时
2. 设法把医学问询场景结构化，以便编写脚本，这部分初步估计占用 8 小时
3. 编写脚本并调试通过，这部分初步估计占用 4 小时
4. 录制脚本开发说明视频，这部分初步估计占用 4 小时

根据以上估算，申请工作时间如下（因上次任务时间紧张，故此次初定的 Deadline 较晚）：

@pimgeek - Size: 2.5 , Deadline: 2018-02-05

**Comment by fushang318** [comment]
医学问询场景目前不用编写脚本，有一个自动转化方案，可能需要先找个时间给你介绍一下 @pimgeek

**Comment by pimgeek** [comment]
听起来不错，回头了解一下 ：）

**Comment by fushang318** [comment]
@pimgeek 咱们定一个时间，我给你介绍一下吧，ZOOM进行，最好白天...你们这周内哪天合适？

**Comment by pimgeek** [comment]
@fushang318 抱歉上周事情太多没安排开，现在定 2018-01-30 日中午 13:00 听你介绍。

**Comment by fushang318** [comment]
@pimgeek 好的，到时间我发起 zoom

**Comment by pimgeek** [comment]
我今天中午与 @fazhen 初步沟通过 30 分钟左右，大概确定了一个落地思路，我会尽快更新工作思路，并形成更合理的 size 和 deadline。

**Comment by fazhen** [comment]
我这里以Excel表格的形式写了一份问询脚本，完成了约70%，明天可以提交。

**Comment by fushang318** [comment]
@pimgeek 先用简短的方式告诉我大致思路，我来确定是否值得做，这个我还是可以判断的

**Comment by pimgeek** [comment]
@fushang318 
1. @fazhen 从一个真实的病例出发，去生成一份问诊记录，以 Excel 表格形式给出 （期间需要与 fazhen 沟通并做必要的记录）
2. @pimgeek 利用这个 Excel 表格里描述的问诊过程，描述出具体的问答场景（期间可能要与 fazhen 和 fushang318 沟通并做必要记录）
3. @pimgeek 根据问答场景编写 MRI 脚本（期间可能要与 fushang318 沟通并做必要记录）并成功运行

因第 2、第 3 步涉及一些实验性步骤，所以不确定能一次形成有效的 “问诊记录 => MRI 脚本” 操作方法，所以暂时不承诺制作讲解视频，集中力量把操作步骤整理清楚，并附可行性报告（提交物均为 Markdown 文档）

**Comment by fushang318** [comment]
@pimgeek 问诊记录是什么样的内容？和现在的医学问询有什么区别？

**Comment by pimgeek** [comment]
@fushang318 目前我从已有的 “腹痛” Excel 表格中，很难反推出医生与患者之间的比较原始的问诊过程。
![image](https://user-images.githubusercontent.com/1609306/35838551-c4639284-0b26-11e8-9835-118722627019.png)

**所谓的问诊记录，就是在这个原始问诊过程中的问答记录。** 这种记录对于医生、患者都更直观，但是不易直接获得。

所以 @fazhen 的思路是，基于一份真实完整的病历，结合个人的诊疗经验，去推断出原始的问诊问答记录，然后交给我来做 MRI 相关场景构建。我对 fazhen 这个思路的可行性有一定信心，也希望能看到这个比较原始的问诊记录的实际样子。

**Comment by fushang318** [comment]
@pimgeek 先初步尝试吧，得出一些正向或者反向的结论，再考虑是否深入

**Comment by pimgeek** [comment]
@fushang318 OK，为避免偏移太远，初步考虑只投入不超 2 天的时间去得出上述 “正向或反向的结论” 。

**Comment by fushang318** [comment]
@pimgeek 好
