### ISSUE TITLE
《ICP奖励机制》的说明和讨论

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#11]
ICP奖励机制还处在起步阶段，有很多操作和理解，需要实践过程中进一步明确和完善。大家可以在这里讨论

**Comment by georgeliuyu** [comment]
## 是不是每个issue都应该有icp label？  
不是的，我们的理念是：凡是没有issue的，就不存在。但并非每个issue一定是icp。  
有很多的讨论，比如此issue就不会是icp。

**Comment by ben7th** [comment]
同意 @georgeliuyu 的观点，会议纪要这些 issue 也不是 icp

> 不是的，我们的理念是：凡是没有issue的，就不存在。但并非每个issue一定是icp。
有很多的讨论，比如此issue就不会是icp。

**Comment by sinchb** [comment]
@ben7th @georgeliuyu 那就要确定，哪些issue是必然有ICP的

**Comment by ben7th** [comment]
> @ben7th @georgeliuyu 那就要确定，哪些issue是必然有ICP的

1. 声明了工作内容或工作目标
2. 被放入里程碑
3. 需要开发代码或提交文档（会产生 pr）
4. 不是通过发包方式付费的

这些 issue，都要标记 ICP

**Comment by georgeliuyu** [comment]
@sinchb 这个的决定权，全权在你们这样的committer手上。你们跟项目需要可以个发一个任务icp issue，你也可以发一个没有icp的需求讨论，注意所有的icp issue一定要有提交物。

**Comment by georgeliuyu** [comment]
@ben7th 没有放入milestone的issue不会被统计

**Comment by ben7th** [comment]
## 通过 ICP 体系给开发者和 review 者标记工作量，具体是怎么操作的？

举例：现在某工程存在三个 issue `#1` `#2` `#3`

**每个 issue 的工作量标记（给开发者）：**
`issue #1` - `size: 0.5`
`issue #2` - `size: 1`
`issue #3` - `size: 0.2`

**开发者张三的 pr:**
```
pr #4
- commit - fix #1
- commit - fix #3
```

**开发者李四的 pr:**
```
pr #5
- commit - fix #2
```

**pr 上的工作量标记（给 review 者）**
`pr #4` - `size: 0.3`
`pr #5` - `size: 0.2`

`pr #4` 由王五 review
`pr #5` 由赵六 review

那么，当 pr 被合并，issue 被关闭，贡献被统计时，各人获得的贡献值为：

张三：0.7 （来源于 `issue #1` `issue #3 `）
李四：1（来源于 `issue #2`）
王五：0.3（来源于 `pr #4`）
赵六：0.2（来源于 `pr #5`）

---------

总结：
- issue 上标记的工作量给开发者
- pr 上标记的工作量给 review 者
- pr 被合并是开发者和 review 者获得贡献统计的**必要条件**

**Comment by georgeliuyu** [comment]
## contributor禁止加 icp 相关的 label

**Comment by ben7th** [comment]
> contributor禁止加 icp 相关的 label

@georgeliuyu 同意。由于所有 label 标记动作都会被 github 记录，所以相关行为可以通过工具来统计与纠正；

**Comment by georgeliuyu** [comment]
@ben7th @sinchb @fushang318 
建议：
1、既然协作的耗时统计，很难自动完成，那么建议采用手工统计的方式；  
2、统计建议每天进行，这样也能便于committer把握和促进协作的进行；  
3、每个协作完成组织做一次review，核心是发现耗时节点和优化。

**Comment by fushang318** [comment]
@georgeliuyu 每天什么时间统计呢，有的人喜欢凌晨工作，有的人喜欢白天工作，或者不统计最后一楼？
其实很多的时候的耗时主要是因为整个工作的多个参与者工作时间差别大，比如
1. A喜欢白天工作
2. B喜欢凌晨工作
3. 那么A和B的每次沟通经常跨越一整天

**Comment by georgeliuyu** [comment]
@fushang318 你提的问题很好，我的看法是：1、众和社区推动并且建议大家能正常作息，这样对身体有好处；2、基于第一点，可建议23:00-8:00之间不计算时间消耗；

**Comment by georgeliuyu** [comment]
@fushang318 我犯了个错误，以后应该是我来提问题，你们解决。

**Comment by ben7th** [comment]
@georgeliuyu 协作的时间统计，恰恰是手工很难统计，只能自动完成。
自动统计规则涵盖不了的内容，靠每天手工统计同样涵盖不了，而且过多的非自动规则会让大家更累。

**Comment by georgeliuyu** [comment]
@ben7th  1、如果能实现自动统计非常好 :+1:  ,你起一个issue，并确定完成deadline；2、在没有自动化之前 @fushang318 手工统计的结果出来后，做一次review。

**Comment by sinchb** [comment]
@georgeliuyu @ben7th @fushang318 其实每个人的作息也应该得到尊重，假如我们有一位大洋彼岸的同学，那他无论如何都无法和我们同步。

**Comment by georgeliuyu** [comment]
@sinchb 存在这种情况，你的建议是？

**Comment by sinchb** [comment]
如果我们能在大的deadline上做好把控，那么每个回复是否能在30分钟内就变得不那么重要。那么我们放宽限制，如果在6小时，或者12小时内能回复，就算通过。因为

* 考虑不同时区问题
* 考虑不同人作息问题
* 考虑到开发需要集中精力和时间，不应该被被issue回复或者邮件提醒打断

所以我的建议是：
* 做好大项目划分，需求划分，以及时间安排（这是个难度很高的活）
* 卡好每个小阶段的时间，而不是每个comment回复的时间
* 一个工作日必须有相应的回复，没有时间处理，也请说出来。
@georgeliuyu @fushang318 @ben7th 


@georgeliuyu @ben7th @fushang318

**Comment by fushang318** [comment]
> 一个工作日必须有相应的回复，没有时间处理，也请说出来。

我非常赞同 @sinchb 的这个说法，就算没有时间处理（这个是正常的，有可能在忙其他事情），也要给别人一个时间预期，告诉大家自己的状态和计划
