### ISSUE TITLE
费用结算及统计工作

### ISSUE THREAD

**Issue by shero3** [sibbay-ai/public#110]
9月-1.15
1.医疗组人员费用结算2次，size：0.2D
2.ICP结算3次，合计21人次，size：1.8D
3.码市发包及管理，合计18个包，size：1D
4.配合数据统计，整理码市及猪八戒费用支出数据，size：1D
以上工作都已按期完成，合计：4D

另zoom.us费用是单独钉钉申请，还是在icp统计时一起申请？
@georgeliuyu

**Comment by georgeliuyu** [comment]
@shero3 这个issue可以关了
