### ISSUE TITLE
关于此次开发组ICP延迟发放的说明以及ICP相关规范的说明

### ISSUE THREAD

**Issue by shero3** [sibbay-ai/public#112]
此次ICP的结算由于统计上的问题导致没有按时发放，对此对各位小白健康的贡献者表示非常抱歉，这一两天待各位Committer确认数据无误后，会尽快发放本次的ICP奖励。

由于此次ICP发放的延误，我想就相关流程再细化一些，具体如下：
1.每月统计区间为上月16号-当月15号
2.每月ICP统计会由@ben7th先提供一份系统自动统计的数据，然后由各位Committer确认数据无误，此项工作最晚需在每月18号之前完成，提交给我，以便在20号之前完成当次ICP的发放工作
3.issue的规范申请以及规范记录，详见：https://github.com/sibbay-ai/public/issues/103   ，  如有不符合规范的issue，必须按规范修改
4.非开发者的ICP统计暂时还是由贡献者手动统计

最后，由于下月15号正值春节，故1月的ICP统计需提前，统计区间为1.16-2.8，各位Committer请在10号之前确认数据提交给我，12号前完成发放。

@georgeliuyu @ben7th @fushang318 @sinchb  @lixinxuan @arnkorty @Yidadaa @pimgeek @choufeng @NiuShy @bqx619 @yeyuexia @ax003d @wb14123 @alisahuxu @fangrongxaing @fazhen

**Comment by alisahuxu** [comment]
收到





| |
alisa
邮箱：alisa_huxu@126.com
|

签名由 网易邮箱大师 定制

在2018年01月22日 10:22，shero3 写道：

此次ICP的结算由于统计上的问题导致没有按时发放，对此对各位小白健康的贡献者表示非常抱歉，这一两天待各位Committer确认数据无误后，会尽快发放本次的ICP奖励。

由于此次ICP发放的延误，我想就相关流程再细化一些，具体如下：
1.每月统计区间为上月16号-当月15号
2.每月ICP统计会由@ben7th先提供一份系统自动统计的数据，然后由各位Committer确认数据无误，此项工作最晚需在每月18号之前完成，提交给我，以便在20号之前完成当次ICP的发放工作
3.issue的规范申请以及规范记录，详见：https://github.com/sibbay-ai/public/issues/103，如有不符合规范的issue，必须按规范修改
4.非开发者的ICP统计暂时还是由贡献者手动统计

最后，由于下月15号正值春节，故1月的ICP统计需提前，统计区间为1.16-2.8，各位Committer请在10号之前确认数据提交给我，12号前完成发放。

@georgeliuyu@ben7th@fushang318@sinchb@lixinxuan@arnkorty@Yidadaa@pimgeek@choufeng@NiuShy@bqx619@yeyuexia@ax003d@wb14123@alisahuxu@fangrongxaing@fazhen

**Comment by sinchb** [comment]
ok

**Comment by pimgeek** [comment]
@pimgeek 已阅读，自行统计工作量以后，如何把总工作量发给 @shero3 ？

**Comment by shero3** [comment]
@pimgeek 自行统计后都交committer确认，由committer统一提交到我这里

**Comment by ax003d** [comment]
@shero3 收到

**Comment by georgeliuyu** [comment]
@shero3 这种issue，要注意close
