### ISSUE TITLE
小程序：点击头像该打开健康状况

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#114]
![image](https://user-images.githubusercontent.com/16983441/35490022-77716ff0-04d7-11e8-9665-eb8d70fcd8d9.png)
 点击这里应该打开健康状况

@ben7th @Yidadaa

**Comment by Yidadaa** [comment]
@ben7th @georgeliuyu 

我来添加此功能。

Size: 0.1
Deadline: 2018-01-30

**Comment by Yidadaa** [comment]
@georgeliuyu 

已加入该功能。

页面整合工作见ISSUE: sibbay-ai/lt-miniapp#270

**Comment by Yidadaa** [comment]
bug已修复。
