### ISSUE TITLE
《issue 规范》的说明和讨论

### ISSUE THREAD

**Issue by ben7th** [sibbay-ai/public#12]
规范文档：[《issue 规范》](https://github.com/sibbay-ai/public/blob/master/issue%20%E8%A7%84%E8%8C%83.md)

对于实际操作过程中，issue 的撰写，管理，以及关闭，如何实践，以及有各种问题，大家可以在这里讨论

**Comment by sinchb** [comment]
@ben7th @fushang318 @georgeliuyu @shero3 

>
issue 创建后需尽快指定 assignees. assignees 通常为希望看到并回复此 issue 的开发者；
ICP 奖励的确定仅与对应 issue 的 pr 有关。assignees 只作为一种跟踪参考；

关于这点我有个建议：
* 一个issue 的assignees一般来说，** 有且仅有一个，这个人必须是实际执行issue的人**。 原则上不同意一个issue有多个assignees

* pr 的 reviewer可以有多个，但是assignee **有且仅有一个，必然是pr的实际贡献者**

这样我们在统计的时候，会少很多干扰因子。

**Comment by georgeliuyu** [comment]
@sinchb :+1:
