### ISSUE TITLE
关于规范ICP流程的通知

### ISSUE THREAD

**Issue by shero3** [sibbay-ai/public#124]
**背景**

基于上一次ICP自动统计中遇到的问题（ICP标记不规范，流程混乱等），我们于2018-01-23日修改了ICP的流程以及规范，并画了ICP流程图，作为示意。

**新ICP流程的理解**

新的ICP流程和前一个版本略有不同，所有参与小白工作的贡献者都需要重新阅读新的规范、流程图。如有疑问，可回复此issue，并@sinchb进行询问。 
ICP修改PR：https://github.com/sibbay-ai/public/pull/113 
ICP流程图： https://www.processon.com/view/link/5a65784ce4b05a8ff311e34f

**更正工作**

我们将在2018-02-05 对本期ICP作一次脚本自动统计，为了使新的统计通过能够顺利、准确完成，需要对现有的ICP issue、ICP PR进行一次修正。 修正工作，先由各位贡献者根据新的规范进行自查，最终提交给各自 committer进行复查。 具体committer如下：

前端 @ben7th
运维、mri、后台管理 @fushang318
后端 @sinchb
运营 @alisahuxu
注意：此次未按期按规范修改的，就延迟到下一次统计。

时间节点

各位committer于2018-02-04 24:00:00前完成验收，并在issue中通知@sinchb

所有人员阅读后请回复“收到”

- [x] 前端 @ben7th 
- [x] mri && 后台管理 @fushang318 
- [ ] 运营 @alisahuxu 
- [x] 后端 @sinchb

**Comment by fushang318** [comment]
@sibbay-ai/all 各位看一下

**Comment by fazhen** [comment]
收到 @shero3

**Comment by fazhen** [comment]
收到 @fushang318

**Comment by alisahuxu** [comment]
收到@shero3

**Comment by fushang318** [comment]
收到

**Comment by ben7th** [comment]
OK👌

**Comment by sinchb** [comment]
@fushang318 @ben7th @alisahuxu 是否都ok了？今天是deadline

**Comment by alisahuxu** [comment]
ok




| |
alisa
邮箱：alisa_huxu@126.com
|

签名由 网易邮箱大师 定制

在2018年02月04日 23:40，sinchb 写道：

@fushang318@ben7th@alisahuxu 是否都ok了？今天是deadline

**Comment by georgeliuyu** [comment]
@shero3 还是要@所有的人

**Comment by georgeliuyu** [comment]
@shero3 怎么at的？你截个图我看看

**Comment by shero3** [comment]
![image](https://user-images.githubusercontent.com/32825620/35785579-4bc4264c-0a5c-11e8-95d5-93b71c85db1f.png)
@georgeliuyu

**Comment by fushang318** [comment]
@sibbay-ai/all

**Comment by pimgeek** [comment]
我感觉这个应该是可行的，属于 GitHub 的自动提示
![image](https://user-images.githubusercontent.com/1609306/35785828-695e2106-0a5e-11e8-8836-95c309a0fa00.png)

**Comment by sinchb** [comment]
@ben7th @fushang318 @alisahuxu 如果完成review了，在上面的checklist里打上一个勾吧。

**Comment by ax003d** [comment]
收到

**Comment by fushang318** [comment]
@sinchb 没法打钩，我完成了

**Comment by alisahuxu** [comment]
我也是，找不到打勾地方




| |
alisa
邮箱：alisa_huxu@126.com
|

签名由 网易邮箱大师 定制

在2018年02月06日 09:31，fushang318 写道：

@sinchb 没法打钩，我完成了

**Comment by sinchb** [comment]
@fushang318 @ben7th @alisahuxu 好了，markdown写错了

**Comment by fushang318** [comment]
deadline: 2018-04-15
