### ISSUE TITLE
【小白健康】首届云上年会邀请函

### ISSUE THREAD

**Issue by shero3** [sibbay-ai/public#125]
![_20180204105002](https://user-images.githubusercontent.com/32825620/35773913-9e38df48-099a-11e8-8fef-6a0c56d5599b.jpg)
@sibbay-ai/all

**Comment by ben7th** [comment]
已经通过公众号获得会议地址，赞 👍

**Comment by fushang318** [comment]
已经通过公众号获得会议地址，赞 👍

**Comment by sinchb** [comment]
已经通过公众号获得会议地址，赞 👍

**Comment by ShengDu** [comment]
已经通过公众号获得会议地址，赞 👍

**Comment by ben7th** [comment]
年会已结束，此 issue 关闭
