### ISSUE TITLE
关于社区使用人群的状态标签设计需求

### ISSUE THREAD

**Issue by fangrongxaing** [sibbay-ai/public#127]
关于社区使用人群的状态标签设计需求 @georgeliuyu

**Comment by georgeliuyu** [comment]
@fangrongxaing 你按照icp的流程申请一下。

**Comment by georgeliuyu** [comment]
总共有4种人：1、我；2、我监督的人；3、我关注的人；4、系统推荐的；需要标注的：1、我；2、我监督的人
每个人的状态是：1、很好；2、一般；3、还行；4、很糟；
@fangrongxaing

**Comment by ben7th** [comment]
@fangrongxaing 这个 issue 是否需要关联 PR？

**Comment by fangrongxaing** [comment]
等下我做个标签pr

**Comment by fangrongxaing** [comment]
等下我做个标签pr

**Comment by fangrongxaing** [comment]
申请开发 deadline:2018-05-15 size:2
