### ISSUE TITLE
没有疾病的社区显示

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#128]
没有疾病按照左边的方式显示，不要使用“健康”,而是将下面的内容上移
![image](https://user-images.githubusercontent.com/16983441/35893560-90b5a152-0be9-11e8-8dd8-23e70037b428.png)
注意文字上面和下面要留些空：
![image](https://user-images.githubusercontent.com/16983441/35893748-641a03c6-0bea-11e8-910e-3232c7ebce9d.png)

@ben7th @Yidadaa

**Comment by ben7th** [comment]
@ben7th 申请开发 
Size: 0.2 
Deadline：2018-02-12

**Comment by ben7th** [comment]
已经在新设计里包含并另外实现，此 issue 关闭
