### ISSUE TITLE
pull request 规范的说明和讨论

### ISSUE THREAD

**Issue by ben7th** [sibbay-ai/public#13]
规范文档：[《pull request 规范》](https://github.com/sibbay-ai/public/blob/master/pull%20request%20%E8%A7%84%E8%8C%83.md)

对于实际操作过程中，pull request 的提交，review 工作的具体进行方法，如何合并，关闭，甚至重新打开 pull request, 如何实践，以及有各种问题，大家可以在这里讨论

**Comment by sinchb** [comment]
我看很多pr最后都没有rebase为1个commit，导致主干分支的timeline很乱。是否强制增加一条： **所有pr在merge之前，必须rebase为一个commit，并有简明扼要的备注信息 ** 
@ben7th @fushang318 @georgeliuyu

**Comment by georgeliuyu** [comment]
@sinchb  同意；
@ben7th 
1、以后所有的规则都作为统计的条件。
2、pr 加checklist：

- [ ]   相关的issue已经关联了
- [ ]   是否编写了相关的unittest（后端）
- [ ]   提交时以运行了full test（后端）

**Comment by ben7th** [comment]
@sinchb @georgeliuyu 
存在这种情况：一个 pr 里包含多个 commit, 每个 commit fix 一个 issue
这种情况通常出现在批量改小 bug 的情况下
是否只做到一个 commit  对应一个 issue 即可，不用把整个 pr rebase 为一个 commit

**Comment by georgeliuyu** [comment]
@ben7th @sinchb @fushang318 你们三人商量一下今天形成决议，然后修改文档，执行。

**Comment by sinchb** [comment]
@ben7th 同意，目的是能有组织良好的timeline。

**Comment by fushang318** [comment]
@sinchb rebase 是否会导致 review 历史记录被删除掉

**Comment by sinchb** [comment]
@fushang318  这个没有实验过，理论上，review的commit应该是跟着pr的，不应该跟着commit

**Comment by georgeliuyu** [comment]
@ax003d 提出：可以考虑在代码仓库的根目录添加一个文件，PULL_REQUEST_TEMPLATE.md，用于存放模板。
可以在不同的项目建立不同的模板，及checklist

**Comment by georgeliuyu** [comment]
@ben7th @sinchb @fushang318  提议：在规范中增加PULL_REQUEST_TEMPLATE.md的内容，前段和后端的可以不同；

**Comment by ben7th** [comment]
已列入 2017.12.13 立会讨论
