### ISSUE TITLE
neo token钱包的创建方式

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#130]
@fushang318 你写一个neo币的钱包方式

**Comment by georgeliuyu** [comment]
https://neotracker.io/wallet

**Comment by fushang318** [comment]
### NEO 币介绍
NEO币是目前国内发展势头最好的一个虚拟货币。
经过几年的发展，已经从最初的几毛钱一个升值到了 750块钱左右一个（在年前虚拟货币整体价格走低前，达到过 1000元左右），未来的价值我个人比较看好  
官网 https://neo.org/  
可以通过这个地址，关注价格 https://www.feixiaohao.com/currencies/neo/

###  NEO 账号介绍
想要保管自己的 NEO币，就需要申请一个自己的 NEO币账号。
一个NEO币账号最主要由两部分组成
1. 私钥（Private Key）    
2. 地址（Address）    

这两部分内容都是一串看起来很乱的字符    

1. 先介绍私钥（Private Key），这串内容需要自己谨慎保管，千万不能让别人知道，因为知道这串字符就相当于有了操作这个NEO账号的所有权利，然后你的NEO币就会被别人拿走啦
2. 再介绍一下地址（Address），这串内容可以比喻成类似银行卡的账号的东西，通过这个地址，别人可以向这个地址转入NEO币，另外需要注意：任何人都可以随意查看某一个地址对应的NEO账号中拥有的NEO币数量
比如 https://neotracker.io/address/AcZ45zxfrVuPmySJj33BBKyLiXBvrjrBNE 可以看到 AcZ45zxfrVuPmySJj33BBKyLiXBvrjrBNE 这个地址下有多少NEO币

### NEO 钱包介绍
NEO 钱包是为了方便管理 NEO账号而存在的一个概念，一般来讲一个NEO钱包会对一个 NEO账号进行管理，有很多工具都可以创建 NEO钱包  
但是这些工具都有各自的NEO钱包文件格式，互相是不兼容的，我推荐使用 https://neotracker.io/wallet 来创建一个NEO钱包

### 创建一个 NEO 钱包

访问 https://neotracker.io/wallet (可能需要翻墙) 
![1](https://user-images.githubusercontent.com/326242/36059161-56dd4120-0e6d-11e8-8924-48a080cf4238.png)




点击 NEW WALLET，进入第二个界面，输入钱包密码，如图
![2](https://user-images.githubusercontent.com/326242/36059162-5dec4bdc-0e6d-11e8-82ca-f756fc6b98e1.png)



点击 CREATE 进入第三个界面，点击 DOWNLOAD KEYSTORE 下载创建好的钱包文件（自己保存好，别丢了），如图
![3](https://user-images.githubusercontent.com/326242/36059164-6479fe9a-0e6d-11e8-9fb7-4db558ceebbb.png)



下载完钱包文件后，点击 CONTINUE 进入第四个界面，会显示出你的NEO 账号的私钥（Private Key）， 如图
![4](https://user-images.githubusercontent.com/326242/36059167-6978050e-0e6d-11e8-9d6a-9267be12f9ec.png)



点击 PRINT PAPER WALLET，会打开一个新界面，并同时打开打印设置，把打印设置界面关闭，这个界面上显示了你的 NEO 账号的最主要的两个信息私钥（Private Key）和地址（Address），还在等什么，赶紧复制保存到安全的地方，如图
![5](https://user-images.githubusercontent.com/326242/36059169-6fd6bb70-0e6d-11e8-8cec-7b09bcf7612f.png)



关闭上图的界面，回到第四个界面，点击 CONTINUE 进入第五个界面，钱包主页，如图
![6](https://user-images.githubusercontent.com/326242/36059170-745e42f8-0e6d-11e8-9bf3-257a860f6327.png)



好了，你的 NEO 账号和钱包就已经创建好了
如果想要退出钱包，可以点击 MENU 中的 CLOSE WALLET,如图
![7](https://user-images.githubusercontent.com/326242/36059171-78806b0e-0e6d-11e8-816b-dcc98819cd15.png)


### 通过 NEO 钱包文件打开钱包主页
访问 https://neotracker.io/wallet (可能需要翻墙) 
![1](https://user-images.githubusercontent.com/326242/36059172-7def91f0-0e6d-11e8-8f72-4ac93291e852.png)



点击 OPEN WALLET，如图
![8](https://user-images.githubusercontent.com/326242/36059173-83050562-0e6d-11e8-9e3c-9bc2e9346121.png)



进入第二个界面，选择左侧的 Keystore File,然后点击右侧的 SELECT WALLET FILE 选择创建 NEO 钱包时，下载的钱包文件，然后输入钱包密码，如图
![11](https://user-images.githubusercontent.com/326242/36059174-8859a298-0e6d-11e8-86a7-cde7293e6c4d.png)


点击 UNLOCK 进入钱包主页

### 通过 NEO 账号私钥打开钱包主页
访问 https://neotracker.io/wallet (可能需要翻墙) 
![1](https://user-images.githubusercontent.com/326242/36059175-8d3ec2fc-0e6d-11e8-94c4-272479f0a875.png)



点击 OPEN WALLET，如图
![8](https://user-images.githubusercontent.com/326242/36059178-92c8423e-0e6d-11e8-8717-38e870cf7f92.png)


进入第二个界面，选择左侧的 Private Key,然后在右侧输入你的NEO账号私钥（Private Key），如图
![9](https://user-images.githubusercontent.com/326242/36059180-975e6134-0e6d-11e8-812d-717d31650c15.png)

点击 UNLOCK 进入钱包主页


### 几个建议
- NEO钱包其实不是必须的，而是为了操作方便和减少泄露私钥的可能性而设计的一个东西，看自己情况和习惯来确定是否使用钱包文件，公共场合建议使用钱包文件
- NEO账号的私钥和地址两个内容一定要备份保存好，NEO账号的私钥和地址两个内容一定要备份保存好，NEO账号的私钥和地址两个内容一定要备份保存好
- NEO账号的私钥一定不要让别人知道，NEO账号的私钥一定不要让别人知道，NEO账号的私钥一定不要让别人知道

**Comment by fushang318** [comment]
另一个不翻墙就可以创建NEO钱包的说明  
http://sibbay-files.oss-cn-hangzhou.aliyuncs.com/share/create_neo_wallet.mp4

**Comment by alisahuxu** [comment]
@fushang318 我们昨天获奖的伙伴，要把自己的地址公布在issue#131里，才能发放奖励对吧？

**Comment by fushang318** [comment]
@alisahuxu 是的，需要把所有人的地址汇总一下（千万不要给成私钥啊，233）

**Comment by ben7th** [comment]
@fushang318 这个需要整理成文档

**Comment by fushang318** [comment]
变更 deadline:2018-05-03  统计遗漏
