### ISSUE TITLE
1.15-2.10 ICP发放通知

### ISSUE THREAD

**Issue by shero3** [sibbay-ai/public#132]
本次ICP统计已经完成，审核工作也已完成。
@ben7th @fushang318 @sinchb 麻烦于今日完成审批流程，以便我能在明天之前发放完毕。
 @sibbay-ai/all 在此，也预祝各位小白的小伙伴们新年快乐，新的一年心想事成，万事如意！

**Comment by fushang318** [comment]
收到，新年快乐~

**Comment by alisahuxu** [comment]
收到，辛苦了shero.新年快乐，万事如意！

**Comment by sinchb** [comment]
收到，happy new  year!

**Comment by shero3** [comment]
@georgeliuyu 本次ICP已全部发放完毕，ICP发放表也已完成。
deadline：2018-02-12
size：2

**Comment by shero3** [comment]
deadline: 2018-04-14

**Comment by fushang318** [comment]
deadline: 2018-04-14
