### ISSUE TITLE
协作：MRI互动文案润色优化

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/public#134]
这周进行一次MRI互动文案的润色优化，工作内容和顺序如下
1. 提取所有文案到石墨文档，由 @fushang318 完成， deadline: 2018-02-27下午三点前
2. 对石墨文档中的文案进行润色，具体组织由 @alisahuxu 进行
3. 把润色后的文案写回MRI脚本中，目前是手动操作，有 @fushang318 完成， deadline: 2018-03-04 下午八点前

**Comment by alisahuxu** [comment]
好的。

**Comment by fushang318** [comment]
@alisahuxu 这个是我的第一部分工作的ISSUE https://github.com/sibbay-ai/public/issues/135

**Comment by fushang318** [comment]
@alisahuxu 

提取的文本文档：https://shimo.im/doc/qxdezxqnlP8BG7vy

**Comment by fushang318** [comment]
@alisahuxu 

我增加了一个EXCEL格式的纯文本 https://shimo.im/sheet/aahsqgcpbmoRNaNQ
应该会更方便一点
可以创建这篇文档的副本，然后直接填写修改后的内容，对照更方便一些

**Comment by fushang318** [comment]
目前大家没有好的想法，另外有其他的安排（找产品人员专门来设计）
所以先关闭了
