### ISSUE TITLE
MRI互动文案润色优化

### ISSUE THREAD

**Issue by alisahuxu** [sibbay-ai/public#137]
来自 #134

个人想法：小白的语言务必简洁明朗，选项也力求简洁，让用户在最短时间做出反应。
已经完成第一次润色优化：https://shimo.im/doc/ITBDYDHDSUwdHHwZ

有几处疑惑，已经在石墨文档中用大号+下划线字体标注，请协助回答@@fushang318

**Comment by alisahuxu** [comment]
deadline: 2018-03-02 17:00前

**Comment by fushang318** [comment]
@alisahuxu 在文档评论中回复你了

**Comment by alisahuxu** [comment]
@fushang318 
根据excel要求，修改了一下：
https://shimo.im/sheet/KpSId2NQbRw7sSoD

**Comment by fushang318** [comment]
@alisahuxu 给你评论了

**Comment by alisahuxu** [comment]
只有一处，已经修改了：
https://shimo.im/sheet/KpSId2NQbRw7sSoD
@fushang318

**Comment by fushang318** [comment]
@alisahuxu 我增加了一列专门介绍 占位符含义的内容  
要不还是等黄老师完成第二轮润色后，我在录入吧..
录入后我整体录几个视频

**Comment by fushang318** [comment]
@alisahuxu 我先按照原始的文案把全部互动录像解释一下逻辑，当然我会有优先级的一段一段的录制

**Comment by fushang318** [comment]
@alisahuxu 我把现有互动的逻辑介绍了一下，另外还有视频演示  
https://shimo.im/docs/YaXu7NBXNbgxSbaN  
可以根据互动URL找到和 excel 的纯文本的对应，帮助润色工作的进行

**Comment by alisahuxu** [comment]
https://shimo.im/sheet/aahsqgcpbmoRNaNQ
https://shimo.im/docs/YaXu7NBXNbgxSbaN
@skytian1 
请对应石墨文档，修改润色。

**Comment by skytian1** [comment]
@alisahuxu不好意思啊，没办法打开这个文档，我没有权限

**Comment by skytian1** [comment]
https://shimo.im/doc/aAXtcd1sqg8WXmFE/ 「例假管理bunch1-经期定位」https://shimo.im/doc/CWCnelx74loimPQr/ 「例假管理bunch2」
https://shimo.im/doc/aIItL6lOgjI79Mgr/ 「例假管理bunch3经期结束建议」 @alisahuxu 请查收对应石墨文档

**Comment by alisahuxu** [comment]
@skytian1 权限已经添加，你可以打开了。

**Comment by alisahuxu** [comment]
@skytian1 请自己单独开设一个issue提交例假管理。每个issue只能对应一个工作，这样便于你的工作统计。请知悉~

**Comment by alisahuxu** [comment]
@fushang318 这个issue现在要做说明吗？因为已经有新的策略了。

**Comment by fushang318** [comment]
@alisahuxu 虽然这个尝试是失败的，但是你是有提交物的..就算有新的策略，这个该怎么算还是怎么算吧？你自己判断，我提交的东西都有算工作量

**Comment by alisahuxu** [comment]
目前大家没有好的想法，另外有其他的安排（找产品人员专门来设计）
所以先关闭了
关联的#134已经关闭，作为分支任务，选择关闭。
