### ISSUE TITLE
关于健康日记的讨论

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/public#138]
https://github.com/sibbay-ai/public/issues/136
关于健康日记的记录形式，大家在会议中的想法可以在这里进行记录并讨论。
也欢迎其他同事，进行补充和讨论。
@sibbay-ai/all

**Comment by aixinhuang** [comment]
健康日记中建议增加体温计录，女性备孕或感冒发烧可用到。
特别是女性备孕有的医生会有每日记录体温要求，根据体温变化了解排卵期，连续体温可用曲线呈现。（也是未来母婴纪录的潜在记录者）

**Comment by fazhen** [comment]
我觉得对于备孕期女性，可以将“体温”放在导航页，参考“体温”、“血压”的形式每天记录，未必一定要在日记中体现。

**Comment by ben7th** [comment]
看了大家的讨论，是不是可以这样认为，随着用途向特定人群扩展，会有很多的时候，需要把一些特定医学指标像血压血糖体重那种，单独拎出一个功能来输入

**Comment by georgeliuyu** [comment]
@fazhen 对的，女性：体温、   婴幼儿：身高、xx
