### ISSUE TITLE
小白社区贡献者ICP流程培训-kavonm

### ISSUE THREAD

**Issue by maohuaming** [sibbay-ai/public#142]
对新加入小白社区的贡献者kavonm进行ICP流程及规范培训。

**Comment by fushang318** [comment]
@maohuaming 好了

**Comment by sinchb** [comment]
对于这两个人的ICP认证和培训，如果被认证人超过1天没有时间回应和处理，可认为认证失败。 @fushang318 @maohuaming

**Comment by fushang318** [comment]
@fushang318 @maohuaming 嗯，可以讨论一下看看是否补充道文档中

**Comment by maohuaming** [comment]
@fushang318 
被认证者——kavonm发布的issue链接：https://github.com/sibbay-ai/public/issues/140
issue编号：140#

**Comment by maohuaming** [comment]
@fushang318 申请开发 Size:0.3 DeadLine: 2018-03-08

**Comment by fushang318** [comment]
@maohuaming 标记好了

**Comment by fushang318** [comment]
@maohuaming
一个建议:  以后可以把被认证者申请认证的ISSUE，作为你的ICP ISSUE

**Comment by maohuaming** [comment]
@fushang318 这个issue请重新设置一下deadline，内容如下：
deadline：2018-03-09

**Comment by fushang318** [comment]
deadline：2018-03-09 

这个上个月没有结算吗？

**Comment by fushang318** [comment]
只需要统计还没有结算的

**Comment by maohuaming** [comment]
@fushang318 刚刚查了一下记录，这个3月份已经统计过了。但是不知为何会统计到4月份的结果里。

**Comment by fushang318** [comment]
哦，是这样，最后一个 可能是你的 issue 列出了所有的 issue，不一定是3月份的
