### ISSUE TITLE
例假管理文案提交

### ISSUE THREAD

**Issue by skytian1** [sibbay-ai/public#143]
来自 #137 
例假管理文案设计 @alisahuxu

**Comment by skytian1** [comment]
https://shimo.im/doc/aAXtcd1sqg8WXmFE
https://shimo.im/doc/CWCnelx74loimPQr
https://shimo.im/doc/aIItL6lOgjI79Mgr @alisahuxu已经再次修改

**Comment by alisahuxu** [comment]
OK,注意：以后你的size要在issue里面向我申请，右侧的Label是我给你标注的，这次就算了。

**Comment by skytian1** [comment]
了解，后续size会直接向你申请。 @alisahuxu

**Comment by skytian1** [comment]
@alisahuxu 申请开发 size:1 Deadline: 2018-03-17
