### ISSUE TITLE
让TA随时查看我的数据-  邀请页面的设计

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#144]
![image](https://user-images.githubusercontent.com/16983441/37070344-ef81ec22-21f1-11e8-9268-49e9e8cb8fe7.png)

场景描述：
1、病人发出这个邀请给医生的微信，让医生随时了解自己的情况，以便得到医生的建议；
2、子女“偷偷”将父母的邀请发给自己，以便可以冒充医生随时监督父母；
设计内容：一句话+一张图  仅仅针对场景1即可。

@alisahuxu @fangrongxaing

**Comment by fangrongxaing** [comment]
好的

**Comment by alisahuxu** [comment]
好的

**Comment by alisahuxu** [comment]
@georgeliuyu 小白现在支持单独的页面了吗？

**Comment by fangrongxaing** [comment]
![202020](https://user-images.githubusercontent.com/33997808/37209548-a6301b2a-23e0-11e8-96fc-b1a580238fb9.png)

@所有人 修改的版本，欢迎大家提意见。咋们可以在这个issue上讨论～

**Comment by maohuaming** [comment]
患者可以要穿病号服，这样更容易辨别是一位患者。

**Comment by fushang318** [comment]
@sibbay-ai/all

**Comment by sinchb** [comment]
病患的表情有点狰狞，是不是换一个比较和谐的。。

**Comment by fangrongxaing** [comment]
![cc](https://user-images.githubusercontent.com/33997808/37248633-6d035c80-2512-11e8-99a6-72a6885ba0f2.png)
![xx](https://user-images.githubusercontent.com/33997808/37248635-6d2eeec2-2512-11e8-9d05-6c53c94090d2.png)
![zz](https://user-images.githubusercontent.com/33997808/37248639-8201c360-2512-11e8-9d4b-55903d8d9272.png)
不能用病号服。因为小白健康的人群不应该是医院的患者。应该是回家后的患者。

**Comment by georgeliuyu** [comment]
@alisahuxu @fangrongxaing 建议：1、我们针对的是健康，不仅仅是病人所以不建议用“病患”；2、提出申请的目的是希望接受者能用心关心“我”，文字例如：“请你随时关心一下我，我会听话的”；3、图案可以用抽象一些，且文字也可以不用在图中；4、邀请和推荐使用小白不是这个，会另外设计。

**Comment by georgeliuyu** [comment]
![image](https://user-images.githubusercontent.com/16983441/37249081-370d416e-251b-11e8-8d0c-5b4b04f6b873.png)
上面第2点的文字，可以放在这里。

**Comment by georgeliuyu** [comment]
@fangrongxaing  今天晚上你参加一个会议。

**Comment by alisahuxu** [comment]
收到，会尽快修改。

**Comment by alisahuxu** [comment]
为您推荐一个靠谱热心的诊疗小帮手——小白健康

**Comment by georgeliuyu** [comment]
@alisahuxu 理解有出入，这样我们今天语音一下。

**Comment by georgeliuyu** [comment]
@alisahuxu @fangrongxaing 时间9点

**Comment by alisahuxu** [comment]
我上午很忙，请问，下午可以吗？

**Comment by georgeliuyu** [comment]
晚上9点

**Comment by fangrongxaing** [comment]
应该结束了吧。
