### ISSUE TITLE
效率指数(EI) - 算法讨论

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#15]
### 目的： 

- 防止工作量虚报
- 淘汰落后

### 规则：
每半年review一次，本指标仅仅是比较意义上的指标。  
能识别落后即可。  
前期可简化，后期不同工种可以有不同的计算方式

**Comment by georgeliuyu** [comment]
一些参数:   
- pr代码行数/size
- (review的comment行数)/(review size)

**Comment by sinchb** [comment]
* 有一个点需要考虑，统计必然是要在一定量的基础上的，如果统计样本过低，可能导致差异过大。
* 参数方面可以增加committer的主观判断，然后和其他量化指标做一个加权处理。
* 另外就是只做分级处理。分KO和OK两种，会比较好。

@georgeliuyu

**Comment by georgeliuyu** [comment]
@sinchb 
1. 对的 :+1:，要基于一定的量，你们可以考虑一个基数，每月累计size是多少；
2. 不要加主管判断，全自动统计，有问题到下一次调整算法；
3. KO和OK这个不太理解，你可以解释一下：

**Comment by ben7th** [comment]
@sinchb @georgeliuyu 对于主观判断，还是按照判例法的原则来做：

- 先判断哪些主观判断可能有通用意义；
- 不能从数据上找到依据，但有通用意义的主观判断，看是否能通过规矩来形成数据依据；
- 本来就有数据依据，且具有通用意义的主观判断，直接纳入；
- 通过工具统计所有的数据依据，更新统计工具/算法的代码；

**Comment by sinchb** [comment]
@georgeliuyu @ben7th 

* 其实在统计的基础上，做一个KO和OK的判断，也是一种“基于数据统计的主观判断”。
* 再比如，类似投票选举则是一种“主观判断的统计”
我认为适当加上主观判断，可以减少不成熟的数据统计算法造成的“误判”问题。

> 先判断哪些主观判断可能有通用意义；
* 比如沟通上描述问题是否清晰
* 比如代码是否符合规范，函数和结构是否清晰合理（0comment的PR其实是质量很高的PR）
* 比如逻辑是否清晰，是否能快速理解业务等。

**Comment by ben7th** [comment]
@sinchb 可以引入 codeclimate 这样的与 github 结合非常紧密的代码结构质量检查服务来检验提交质量

**Comment by georgeliuyu** [comment]
@sinchb 是否KO是否能理解为点踩、OK理解为点赞？如果是这样，并以此作为EI的因素之一，是可以的。也能实现量化的自动统计。

**Comment by sinchb** [comment]
我们issue的comment的点赞其实是一个随性的主观判断。 我说的KO指的是你统计中最后面的5% @georgeliuyu

**Comment by georgeliuyu** [comment]
@sinchb 你说的：“有一个点需要考虑，统计必然是要在一定量的基础上的，如果统计样本过低，可能导致差异过大。”
@sinchb @ben7th @fushang318 大家提一下每月多少作为基数？

**Comment by sinchb** [comment]
* 如果半年一统计，统计长度应该放宽到半年，灵活性更高。
* 每个开发人员，每天写超过100行代码已经不错了。
* 我建议将文档也囊括进去。
* 我建议半年达到2000行，文档数量达到8篇。

@georgeliuyu @ben7th @fushang318

**Comment by georgeliuyu** [comment]
@sinchb 
- 不是半年一统计，而是半年review一次算法；
- 包含文档
- 这个指标的目的不是贡献量，而是效率。 150行/3D  = 50

**Comment by ben7th** [comment]
@georgeliuyu 

> @sinchb @ben7th @fushang318 大家提一下每月多少作为基数？

一般团队里各种评价取的基数都是在团队成员的平均取值作为定义的基础，在此基础上乘系数；
