### ISSUE TITLE
小白社区贡献者ICP流程认证测试-skytian1

### ISSUE THREAD

**Issue by skytian1** [sibbay-ai/public#152]
@maohuaming

**Comment by maohuaming** [comment]
@fushang318 申请开发 size:0.3 Deadline:2018-03-12

**Comment by fushang318** [comment]
@skytian1 @maohuaming 你们约个时间，集中进行认证吧

**Comment by maohuaming** [comment]
@fushang318 由于skytian1为非技术人员，ICP流程认证测试size，申请修改为0.5。

**Comment by fushang318** [comment]
@maohuaming 好了，应该是进行了一些培训+操作不熟练，所以多花了一些时间

**Comment by fushang318** [comment]
@maohuaming 这个怎么处理
