### ISSUE TITLE
用药历史的显示

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#154]
需求内容：
1、在用药界面的下端显示用药历史；
2、点击进入先是历史的情况：用药目的、效果等等；
3、在用药历史页面有再次服用的按钮；
要进行设计。

@ax003d @ben7th @sinchb @Yidadaa

**Comment by ben7th** [comment]
@georgeliuyu @sinchb

需求 1 是否可参考目前疾病页面中已经停止跟踪疾病的显示？

**Comment by georgeliuyu** [comment]
@ben7th 对
