### ISSUE TITLE
症状管理历史

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#155]
需求内容：
1、在症状界面的下端显示症状历史；
2、点击进入先是历史的情况：症状阶段，用药情况等等；
3、在症状历史页面有再次跟踪的按钮；
要进行设计。

@ax003d @ben7th @sinchb @Yidadaa

**Comment by ben7th** [comment]
@georgeliuyu @sinchb 

需求 1 是否可参考目前疾病页面中已经停止跟踪疾病的显示？

**Comment by georgeliuyu** [comment]
@sinchb 对

**Comment by fushang318** [comment]
@ben7th 这个怎么样了
