### ISSUE TITLE
疾病的历史显示

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#156]
需求内容：
1、在疾病界面的下端显示疾病历史；
2、点击进入先是历史的情况：疾病发生的情况，用药及效果等等；
3、在疾病历史页面有再次跟踪的按钮；
要进行设计。

@ax003d @ben7th @sinchb @Yidadaa

**Comment by ben7th** [comment]
@georgeliuyu @sinchb 

目前疾病界面下端已有过去停止跟踪的疾病的显示，是否已符合需求 1？

根据需求 2, 3 需要实现历史状况页面，实现再次跟踪的操作，以及对应的微服务 API

**Comment by georgeliuyu** [comment]
@ben7th 符合，建议采用UI做一个设计进行区别 @fangrongxaing 
2需要做一个汇总显示

**Comment by fangrongxaing** [comment]
好的

**Comment by ax003d** [comment]
![disease](https://user-images.githubusercontent.com/753663/37502507-fdd2d34a-290d-11e8-9932-a67181318776.png)

@georgeliuyu @ben7th 这个页面需要增加文字提示，哪些是正在跟踪的疾病，哪些是历史疾病。
另外，如果一个疾病多次跟踪，是显示一条记录，还是显示多条记录？
我感觉显示一条记录就好了，点击进去可以查看过去多次发生的历史。

**Comment by georgeliuyu** [comment]
@ax003d 对的 :+1:
