### ISSUE TITLE
小白社区贡献者ICP流程认证规则制定

### ISSUE THREAD

**Issue by maohuaming** [sibbay-ai/public#159]
@fushang318 根据几次ICP流程认证的经历，总结了8条规则。以便完善ICP流程认证规则。

**Comment by maohuaming** [comment]
@fushang318 申请开发 size:0.1 Deadline:2018-03-13

**Comment by fushang318** [comment]
@maohuaming 今天2018-03-14了

**Comment by fushang318** [comment]
deadline: 2018-03-21
