### ISSUE TITLE
【通知】拟于 2017-12-03（周日）进行工作扩大会议，说明 ICP 众合体系

### ISSUE THREAD

**Issue by ben7th** [sibbay-ai/public#16]
所有小白健康的开发者：

### 小白拟定于 2017 年 12 月 3 日（周日）进行一次工作扩大会议，沟通以下内容：

- ICP 众合体系的规范，奖励机制
   https://github.com/sibbay-ai/public/blob/master/README.md

- 实际执行过程中的一些实践方法

- 对现有规范文档的讨论总结
   https://github.com/sibbay-ai/public/issues/11
   https://github.com/sibbay-ai/public/issues/12
   https://github.com/sibbay-ai/public/issues/13
   https://github.com/sibbay-ai/public/issues/14
   https://github.com/sibbay-ai/public/issues/15
  
- 确定开始执行 ICP 众合体系的决议

### 会议时间

2017 年 12 月 3 日（周日） 21:00

### 参与者

所有小白健康的开发者（Committer, Contributor）皆可参与

### 会议形式

通过会议工具 zoom 进行；可自行访问 https://zoom.us/ 下载客户端；
具体会议地址（URL）将在会议开始前 30 分钟通过微信群和此 issue 公开；

希望大家阅读目前的公开规范，以及积极参与 issue 讨论，贡献自己的意见建议，以及提出疑惑；
感谢所有人的支持 ~

-----

12.3 update:

会议地址：https://zoom.us/j/316975223

**Comment by ben7th** [comment]
Contributor:

@arnkorty @ax003d @choufeng @defcyy @fushang318 @kavonm @lixinxuan @NiuShy @wb14123 @yeyuexia @Yidadaa

Committer:

@fushang318 @sinchb @ben7th

**Comment by ax003d** [comment]
@ben7th 日期写错了吧，应该是 12 月 3 日

**Comment by ben7th** [comment]
> @ben7th 日期写错了吧，应该是 12 月 3 日

@ax003d sorry 已改正

**Comment by ben7th** [comment]
会议结束，关闭
