### ISSUE TITLE
12Week  目标要求

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#163]
## 必须完成的目标要求： 
无，各个team完成自定目标。

@ben7th @fushang318 @ax003d @sinchb @yeyuexia @shero3

**Comment by georgeliuyu** [comment]
大家注意要引用这个issue

**Comment by ben7th** [comment]
前端，暂定目标：

- 实现 feed 里图片的显示
- 实现用药，疾病，症状下停止跟踪后记录的查看
- 优化引导页等页面的加载，减少卡顿和视觉跳跃

**Comment by fushang318** [comment]
@
