### ISSUE TITLE
提交icp的统计数据的比较

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#166]
@shero3 你提供给我本月统计的icp issue和pr的详细列表； @ben7th 配合
@Mengjianhua-c 你重新计算2月16日00:00 到 3月16日00:00的icp issue和pr。
我要做核对。

**Comment by Mengjianhua-c** [comment]
[icp_result.zip](https://github.com/sibbay-ai/public/files/1823910/icp_result.zip)
@georgeliuyu  附件是最新的统计结果

**Comment by shero3** [comment]
https://shimo.im/sheet/gL2SL7cIb00yLZW6   这是宋亮这边最新统计的结果  @georgeliuyu
