### ISSUE TITLE
关于新人员进入相关规则的通知

### ISSUE THREAD

**Issue by shero3** [sibbay-ai/public#169]
小白健康自2018年1月上线以来，有许多新成员以及岗位开始进入小白的体系中，故在此背景下做如下规定，如有意见可随时与我沟通，以使我们的架构能不断完善：

1.有新成员加入时，先由各team的Committer或者相关任务负责人面试新成员，对其专业能力进行初步判断，如对新成员能力认可后，则将该成员引入ICP体系
2.需要引入ICP体系的新成员，committer或者相关任务负责人需提供新成员的简历信息以及对新成员的评价，给出相关建议，由shero洽谈相关薪资以及对相关规则进行说明，新成员对此无异议后进入ICP认证
3.由shero通知负责ICP认证人员对新成员进行ICP认证，目前是由@maohuaming负责ICP认证事宜，认证完成后将认证结果告知@shero3以及@fushang318，并将新成员加入到通讯录中，必须是完成认证加入到通讯录中的人员才可以作为ICP体系的成员，进入ICP发放的流程中。

以上是新成员进入的相关规则流程，如有疑问或错漏之处欢迎指正……
@sibbay-ai/all

**Comment by fushang318** [comment]
收到 @shero3

**Comment by sinchb** [comment]
收到 @shero3

**Comment by georgeliuyu** [comment]
@shero3 @fushang318 @sinchb @ben7th @ax003d 新同学先采用码市发包的方式进行合作。确认不错后引入icp。

**Comment by fushang318** [comment]
@georgeliuyu 收到

**Comment by fazhen** [comment]
收到 @georgeliuyu

**Comment by fushang318** [comment]
@shero3 可以关闭了吧？

**Comment by shero3** [comment]
@fushang318 可以
