### ISSUE TITLE
【Disease】新增获取疾病历史接口

### ISSUE THREAD

**Issue by ax003d** [sibbay-ai/public#170]
来自：https://github.com/sibbay-ai/public/issues/165
周目标：#164

* URI
```
event.app.func.disease_history.get.v2
```
* 描述
只需要返回历史疾病的 bmesh，name 即可，并且同一个 bmesh 只返回一次。
* Response
```
[{
  "bmesh": "xxxx",
  "name": "xxx",
  "monitoring": true # 是否症状跟踪
}]
```

**Comment by kavonm** [comment]
@ax003d 申请开发
size: 1 Deadline: 2018-03-21

**Comment by kavonm** [comment]
@ax003d 此issue的开发工作共耗费1.5 size

**Comment by sinchb** [comment]
@kavonm @ax003d 最好能写出超出的原因，以后如何改善等。

**Comment by ax003d** [comment]
deadline: 2018-03-22
