### ISSUE TITLE
增加审批草稿的选择列表-前端实现页面并集成API

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/public#178]
需求来自：
https://github.com/sibbay-ai/public/issues/175
https://github.com/sibbay-ai/public/issues/176

**Comment by fushang318** [comment]
@bqx619 后端API已经设计好了，详细信息在  #176

**Comment by fushang318** [comment]
@bqx619 请申请size 和 deadline

**Comment by bqx619** [comment]
@fushang318 申请开发 Size: 1 Deadline: 2018-03-22

**Comment by fushang318** [comment]
@bqx619 API已经实现了，推送到了测试环境

**Comment by bqx619** [comment]
@fushang318 
记得那天似乎说到一个排序筛选出未审核, 待审核的草稿
当数据分页加载时, 最优是需要一个可以传递草稿 type 的 API , 返回和**获取当前待审核草稿列表**这个 API 一致的结构
从而筛选出结果

**Comment by fushang318** [comment]
@bqx619 
记得那天似乎说到一个排序筛选出未审核, 待审核的草稿

这个是编辑者看到的列表需要的

审核者不需要这个列表

目前做的需求不包括这个编辑者列表筛选功能

我们这次做的只包括那天讨论的文档中的需求一

咱们一个一个做

**Comment by bqx619** [comment]
ok

**Comment by bqx619** [comment]
@fushang318 完成

**Comment by bqx619** [comment]
Deadline: 2018-03-22

**Comment by bqx619** [comment]
Deadline: 2018-03-22

**Comment by bqx619** [comment]
@fushang318 这个issue可能需要您帮忙处理一下

写上deadline, 现在我写好像已经没用了
PR引用, 我不是assigness 现在写也没用了
