### ISSUE TITLE
需要一名可以长期参与小白后台管理系统的前端开发人员

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/public#18]
需要一名可以长期参与小白后台管理系统的前端开发人员
需要在满足小白众合的基本要求情况下，技术方面的要求如下
1. 熟悉VUE框架
2. 有一定的UE,UI设计能力

**Comment by georgeliuyu** [comment]
@fushang318 如果已经确定了开发者，你第一个任务会给他什么？如果能明确则就把这个内容作为一个需求写一个icp的issue。如果不能明确，那建议先明确。
