### ISSUE TITLE
【运维】疾病历史 name 字段的填充脚本

### ISSUE THREAD

**Issue by ax003d** [sibbay-ai/public#180]
进入 disease 容器，执行如下命令：
```
root@8b78524246f5:/work# python scripts/fill_name.py 
7 disease monitors has no name
14 disease histories has no name
10 total bmeshs
10 disease infos founc
```

**Comment by fushang318** [comment]
1. 我需要把你写的脚本移植到 https://github.com/sibbay-ai/data-migration 按照标准迁移流程进行
2. 目前的迁移流程中代码的PR不方便 review,我会在这次改进
3. 我需要补充单元测试
4. 这个任务我会先在测试环境运行迁移
5. 生产环境的迁移需要单独选择时间

@ax003d 申请开发  size: 0.3 deadline： 2018-03-23

**Comment by ax003d** [comment]
deadline: 2018-03-23
