### ISSUE TITLE
体重数据问题讨论

### ISSUE THREAD

**Issue by ax003d** [sibbay-ai/public#181]
目前有 2 个地方存储体重数据，一个是体重，一个是医学指标中的体重。
我们是否需要合并和迁移？

@ben7th @fushang318 @sinchb @kavonm @georgeliuyu

**Comment by fushang318** [comment]
@ax003d 这个是历史遗留问题？应该是以前外包数据库结构设计造成的吧？

肯定是要合并的，但是什么时候进行合适不好评估，因为不知道工作量

是否可以先把这个数据的合并需要做的事情设计出一份计划，评估出工作量再选择时间？

**Comment by sinchb** [comment]
这件事 @kavonm 正在做，等他给出方案设计，包括数据迁移的。 @ax003d @fushang318

**Comment by fushang318** [comment]
@sinchb 收到

**Comment by georgeliuyu** [comment]
@ax003d 这个可以close了？

**Comment by ax003d** [comment]
之前迁的是身高，体重后面找时间迁移吧，还有血压、血糖。
