### ISSUE TITLE
public不要随便增加文件

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#186]
![image](https://user-images.githubusercontent.com/16983441/37691941-6b89ae96-2cf0-11e8-8062-4cbeee433330.png)

@fushang318 @maohuaming 将《小白社区贡献者ICP流程认证规则》合并到《贡献者认证流程》中

@shero3 @ben7th 《2月发放明细.xlsx》要删除，以后不要上传。

@ben7th @fushang318 @ax003d @sinchb @alisahuxu @fazhen 知晓

**Comment by fushang318** [comment]
@georgeliuyu 好的，已知晓

将《小白社区贡献者ICP流程认证规则》合并到《贡献者认证流程》中由  @maohuaming 来操作吧

**Comment by sinchb** [comment]
@georgeliuyu 已知晓

**Comment by ben7th** [comment]
@georgeliuyu 创建了一个删除文件的 pr
https://github.com/sibbay-ai/public/pull/215
