### ISSUE TITLE
【需求】数据库索引建立以及数据访问规范

### ISSUE THREAD

**Issue by sinchb** [sibbay-ai/public#19]
## 背景
之前的数据库数据都没有建立过索引，随着数据量越来越大，没有索引，必然会遇到严重的瓶颈。

## 需求
1. 梳理目前服务中用到的所有查询，分db_name/collection_name 来统计。
2. 针对每个models，给出若干索引建议。
3. 注意区分Single Field Index 和 Compound Index
4. 对于Compound Index，注意给出各个field的排序规则。

## 涉及到的项目

```
sr-models
sr-user
sr-reminder
sr-drug
sr-medindex
sr-test
sr-symptom
sr-disease
sr-sns
sr-treat
```

## 验收
  * 以PR形式给出一份JS文档，一是为了查阅，二是为了方便导出给运维同学创建脚本去 build MongoDB索引。
  * 在models中的Document定义的docstr中，加上对应的index说明，以便未来开发者开发。
  * 以PR形式给出一份文档，用于规范开发者对DB的操作。
  * 甚至可以对小白后端代码的数据定义、查询解耦等提出建议。

## 奖励
实际ICP数量将根据需求规格书中明确定义的需求量给出，开发过程严格遵循小白ICP体系

## 要求
* 熟悉Python3
* 非常熟悉MongoDB以及Mongoengine

## 报名
请在此issue下comment，我（@sinchb）会统一处理。

## 参考文档：
https://docs.mongodb.com/manual/indexes/
https://docs.mongodb.com/manual/applications/indexes/

@fushang318 看是否需要补充。

**Comment by sinchb** [comment]
@fushang318 @georgeliuyu

**Comment by georgeliuyu** [comment]
@sinchb 打上icp的label

**Comment by georgeliuyu** [comment]
@ax003d @wb14123 这个任务你们觉得方便入手吗？

**Comment by ax003d** [comment]
@georgeliuyu 我先处理 https://github.com/sibbay-ai/cooperation-issues/issues/109

**Comment by sinchb** [comment]
我来接这件事情，需要 @fushang318 配合

**Comment by fushang318** [comment]
@georgeliuyu 需要我做什么

**Comment by sinchb** [comment]
@fushang318 基本index都建立好了，我们抽个时间，在test上跑一下脚本吧，周三晚上会议结束后操作如何？

**Comment by fushang318** [comment]
@sinchb 好的

**Comment by sinchb** [comment]
@fushang318 我似乎放鸽子了。。我们再约个时间吧，明天我联系你，白天操作下也行。

**Comment by sinchb** [comment]
后端工作完成，测试环境索引已经建立
