### ISSUE TITLE
更新贡献者认证流程增加认证规则

### ISSUE THREAD

**Issue by maohuaming** [sibbay-ai/public#191]
@fushang318 更新贡献者认证流程增加认证规则。

**Comment by maohuaming** [comment]
@fushang318 申请开发Size:0.1 DeadLine:2018-03-21

**Comment by maohuaming** [comment]
@fushang318 这个issue需要你重新设置一下deadline，内容如下：
deadline：2018-04-02

**Comment by fushang318** [comment]
deadline：2018-04-02
