### ISSUE TITLE
产品头脑风暴会议

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#194]
小白请到几位做产品设计的同学，从不同的角度对小白的产品进行了建议和梳理；
我们的目标是：记录和分享
1、任务卡模式设计
设计内容：https://pro.modao.cc/app/qDpCAsIJZiwPJlNMqyQkQjt0nPXZ80M   密码：222222
交流录音：https://zoom.us/recording/play/DIBnXJiZSj7xuXTAODr3PIY6m4AWPhQt4yzDGBYovXbjdVBxn_8IgvAEHPvnk6hG

2、婴幼儿为重点
https://shimo.im/docs/zxTO5o4XvsYaoxag
https://invis.io/PUGCSYP4A62 需要vpn打开
3、互动设计
https://shimo.im/docs/ZkrNTnEEhqMLnwvv
建议使用app：lark  (ios必须美国账号才能找到）

建议周日上午10:00进行一次头脑风暴。
主讲人： Gowbi，aka，二毛  （每人30分钟以内）
会议id：https://zoom.us/j/9552592803
建议参加人员：
@ben7th @ax003d @WangWanyue @sinchb @fushang318 @alisahuxu 
其他有兴趣人员均可参加。

**Comment by ben7th** [comment]
收到 (￣▽￣)

**Comment by fushang318** [comment]
收到 (￣▽￣)

**Comment by alisahuxu** [comment]
收到

**Comment by WangWanyue** [comment]
收到

**Comment by georgeliuyu** [comment]
@ben7th @ax003d @WangWanyue @sinchb @fushang318 @alisahuxu 因为有同学时间冲突，改在周日上午10：00

**Comment by fushang318** [comment]
好的

**Comment by fushang318** [comment]
会议的录像地址如下

主题: 产品头脑风暴会议
日期: 三月 25, 2018 10:05 上午 北京，上海
https://zoom.us/recording/play/dGsRp6GxUsruCuAhhadgnpsg_Ornatovl8OntwjSJDqyYClg5OfyPQBj-IG3SVXk

**Comment by akakenle** [comment]
关于母婴这个产品这两天考虑了一下，整理里一个脑图说明产品框架及功能作用。
脑图链接：https://shimo.im/docs/NmPZQImd3b8kH7qT/
关于产品迭代规划逻辑是：一期上线先满足用户基本功能，记录、病历、社区。其它辅助功能可以后期逐步迭代，如支持家人共同编辑、多个宝宝等等。
