### ISSUE TITLE
小白社区贡献者ICP流程认证-WangWanyue

### ISSUE THREAD

**Issue by maohuaming** [sibbay-ai/public#198]
对新加入小白社区的贡献者WangWanyue进行ICP流程认证。

**Comment by fushang318** [comment]
不好意思，按照新的流程应该由  @ax003d 或者我来创建这个ICP ISSUE 的，下次注意
我来标记ICP

**Comment by fushang318** [comment]
@maohuaming 

@WangWanyue 已经和 @shero3 沟通过了，可以进行ICP认证啦

**Comment by fushang318** [comment]
标记 deadline 吧

**Comment by maohuaming** [comment]
@fushang318 Deadline：2018-03-23

**Comment by maohuaming** [comment]
@fushang318 申请size：0.5

**Comment by georgeliuyu** [comment]
@maohuaming @fushang318  认证一个人要工作4个小时，效率很低啊！

**Comment by maohuaming** [comment]
@fushang318 此issue请帮忙重新设置一下deadline，内容如下：
deadline：2018-04-02

**Comment by fushang318** [comment]
deadline：2018-04-02

**Comment by fushang318** [comment]
1

**Comment by fushang318** [comment]
2
