### ISSUE TITLE
贡献者认证--@lvhongqiang

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#199]
github账号：@lvhongqiang
@shero3 这是一个前端的开发同学，以前做过小白的项目，技术水平和责任心都很好，你与该同学进行一下沟通，确认icp要求的细节；确认后交给 @maohuaming 进行认证

**Comment by fushang318** [comment]
@georgeliuyu 没有这个账号 ” lvhongqiang09”

**Comment by shero3** [comment]
@georgeliuyu 是什么岗位呢？

**Comment by georgeliuyu** [comment]
前端开发 @shero3

**Comment by georgeliuyu** [comment]
认证完成 @shero3 @maohuaming

**Comment by shero3** [comment]
@maohuaming 可以开始认证

**Comment by lvhongqiang** [comment]
@georgeliuyu 申请延期到2018-3-29，因工作原因晚上只有十点后有时间，29号及以后可以白天操作

**Comment by georgeliuyu** [comment]
@lvhongqiang 哦,我以为你现在就有空

**Comment by georgeliuyu** [comment]
deadline:2018-3-29 @maohuaming 延期

**Comment by georgeliuyu** [comment]
@maohuaming @lvhongqiang 这个issue结束了吗？
@ben7th 知晓

**Comment by georgeliuyu** [comment]
@maohuaming 吕小强的微信号：lvhongqiang09

**Comment by lvhongqiang** [comment]
@georgeliuyu 认证没有通过，@maohuaming说我使用的是旧版认证说明文档，今天已经发给我最新版。现在重新约定认证时间，但我只有晚上有空，最早要下周二可以白天认证。
