### ISSUE TITLE
VUE前端，请证明你行！

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/public#20]
## 任务
熟悉现有的后台管理系统业务和代码（ICP工作量为一天）

## 招募流程和要求
1. 首先需要你初步证明你熟悉VUE框架和有一定的UE,UI设计能力（可以是你以前作品的截图或者是 github 版本库代码 或者其他你能证明自己的方式）
2. 确认接下来一两个月你有一定的时间能够保证参与工作 
3. 我提供给你相关代码和文档，你来熟悉现有业务和代码，并需要你完成一篇文档的编写，请用石墨文档编写
4. 我会找人 review 你的提交物（文档）
5. 我会根据 review 结果给出你是否通过了招募的答复，不管你是否通过了招募，都会给你ICP工作量为一天的奖励

我会提供给你
1. 后台管理测试环境的访问权限
2. 源代码版本库的访问权限
3. 一些现有文档

你编写的文档内容包括：
1. 对现有业务的理解
2. 对现有业务的疑惑和问题
3. 现有的代码哪些地方可能可以改进，不管是业务上，还是操作体验，或者是代码质量

## 接下来的开发工作
接下来后台管理的开发工作包括
1. 症状数据的草稿编辑和草稿审核功能的完善
2. 新版权限控制的开发
3. 参考症状数据的草稿编辑和草稿审核功能，完成医学指标数据，医学检测数据，疾病数据，药品数据，治疗数据的对应功能

## 要求
1. 熟悉VUE框架
2. 有一定的UE,UI设计能力
3. 接下来一两个月你有一定的时间能够保证参与工作 

## 报名
请在此issue下comment，我会统一处理。

## 奖励
只要你进行了招募流程中第 3 点的工作，不管你是否通过了招募，都会给你ICP工作量为一天的奖励

@georgeliuyu @ben7th 你们看看有什么需要补充

**Comment by georgeliuyu** [comment]
@fushang318 简化内容后，增加一个功能实现，在码市上发个包。

**Comment by ben7th** [comment]
@fushang318 @georgeliuyu 码市类似发包可以多写一个要求，即：报名者需来此 issue 回复

**Comment by georgeliuyu** [comment]
@fushang318 好主意！

**Comment by georgeliuyu** [comment]
@fushang318 已经发到码市：https://mart.coding.net/project/11451

**Comment by ax003d** [comment]
@fushang318 麻烦给我开下代码权限，我看看看

**Comment by fushang318** [comment]
@ax003d 已经给你了~
