### ISSUE TITLE
申请阅读后端代码，并提交理解文档

### ISSUE THREAD

**Issue by Mengjianhua-c** [sibbay-ai/public#204]
@ax003d 申请阅读后端代码 Size: 1.5 Deadline: 2018-04-07

**Comment by sinchb** [comment]
@Mengjianhua-c 这个deadline已经过了，是否遇到了问题？ @ax003d

**Comment by Mengjianhua-c** [comment]
@sinchb tornado框架看了几天的资料，然后fc也花了一段时间，预估的时间不足 @ax003d 我提交了一个理解文档[analysis](https://github.com/sibbay-ai/sr-wiki/blob/doc/mengjianhua-sr-understand/sr_analysis.md)，下一步尝试搭建开发环境

**Comment by sinchb** [comment]
理解文档，以pull request提交，并关联这个issue。 超出deadline，需要作出延迟申明，否则这个issue的size可能会被程序标记为作废。 @ax003d @Mengjianhua-c

**Comment by Mengjianhua-c** [comment]
@sinchb 近期由于个人原因，空余时间不够充足，另外在实际阅读后端代码中需要学习了解的内容超过预估时间，所以经过和 @ax003d 协商后，申请调整size

**Comment by ax003d** [comment]
deadline: 2018-04-11
