### ISSUE TITLE
症状申请添加的文案修改

### ISSUE THREAD

**Issue by ax003d** [sibbay-ai/public#205]
来自：https://github.com/sibbay-ai/operating/issues/62

申请添加症状，目前直接显示“添加成功”，实际上只是“添加申请成功”。
@alisahuxu 给的建议是，修改为“您的症状已经在后台审核，预计几小时通过后会显示，请耐心等待。”
我觉得可以修改为：
“该症状已经提交后台审核，请耐心等待。”

@ben7th @georgeliuyu 

![add_sym](https://user-images.githubusercontent.com/753663/37816204-19743a86-2ead-11e8-8649-c980a92dc6de.png)

**Comment by georgeliuyu** [comment]
@ax003d 同意

**Comment by Yidadaa** [comment]
我来处理。

@ben7th 
Size: 0.1
Deadline: 2018-03-27

**Comment by Yidadaa** [comment]
修改已完成，此issue关闭。

**Comment by ben7th** [comment]
deadline: 2018-03-27
