### ISSUE TITLE
分享小白小程序后的文案

### ISSUE THREAD

**Issue by ax003d** [sibbay-ai/public#207]
来自：https://github.com/sibbay-ai/operating/issues/62

@alisahuxu 建议分享小白小程序后，文案应显示“感谢分享”，而不是“OK，小白已记下了!”
我觉得可以再润色下，“成功发送分享链接！感谢您对小白的支持！”

@fushang318 @ben7th 这个文案是在 MRI 中修改，还是在前端修改？
@georgeliuyu 

![3q](https://user-images.githubusercontent.com/753663/37816950-e72e5f4a-2eaf-11e8-821d-5dae8052b8fb.jpg)

**Comment by georgeliuyu** [comment]
@ben7th 建议先做成固定图片。

**Comment by fushang318** [comment]
@ax003d 这个是在互动脚本中修改的

**Comment by georgeliuyu** [comment]
@fushang318 你把所有关于互动的建议统一关联到一个issue,这次设计一次性解决

**Comment by fushang318** [comment]
好的 @georgeliuyu
