### ISSUE TITLE
【前端】治疗的历史显示

### ISSUE THREAD

**Issue by ax003d** [sibbay-ai/public#210]
周目标：#164

增加了 2 个接口：
* 获取治疗历史列表
https://app.swaggerhub.com/apis/sinchb/Sibbay/1.0.0#/health/list_treat_history
* 获取治疗历史详情
https://app.swaggerhub.com/apis/sinchb/Sibbay/1.0.0#/health/get_treat_history_detail

@ben7th

**Comment by ben7th** [comment]
收到 (〃'▽'〃)
