### ISSUE TITLE
对前端开发赵冰龙进行 ICP 认证的申请

### ISSUE THREAD

**Issue by ben7th** [sibbay-ai/public#212]
目前已由 @ax003d 和 @ben7th 对赵冰龙进行了电话沟通和问卷填写。

为便于进一步工作，需要赵冰龙进行 ICP 认证，以便参与后续 ICP 任务。

认证步骤参考[《贡献者认证流程》](https://github.com/sibbay-ai/public/blob/master/%E8%B4%A1%E7%8C%AE%E8%80%85%E8%AE%A4%E8%AF%81%E6%B5%81%E7%A8%8B.md)

@shero3 与赵冰龙进行必要沟通后，可安排其按照流程进行认证，并确定认证对接人。

此 issue 作为认证过程记录 issue，认证过程中在其他代码库创建的 issue 均在此引用。

**Comment by shero3** [comment]
@fushang318 目前已与赵冰龙确认相关规则以及日薪标准，可进入ICP认证流程

**Comment by maohuaming** [comment]
@shero 请提供一下赵冰龙的联系方式。

**Comment by shero3** [comment]
@maohuaming 已通过微信给你联系方式

**Comment by maohuaming** [comment]
@fushang318 DeadLine：2018-03-27

**Comment by maohuaming** [comment]
@fushang318 申请size:0.2

**Comment by fushang318** [comment]
@maohuaming 应该向 @ben7th 申请

**Comment by maohuaming** [comment]
@fushang318 了解。

**Comment by ben7th** [comment]
@maohuaming OK

**Comment by fushang318** [comment]
这个 deadline  有效？
@maohuaming

**Comment by maohuaming** [comment]
@ben7th 此issue请帮忙设置一下deadline，内容如下：
deadline：2018-04-02

**Comment by ben7th** [comment]
deadline：2018-04-02
