### ISSUE TITLE
mri-mri 实现两个修改bunch 的HTTP API

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#22]
这两个HTTP API只会用于 MRI仿真器

第一个HTTP API 是：清空数据库中的所有bunch
第二个HTTP API是：把提交的一到多个bunch保存到数据库

以前的 post /mri/reload_bunchpool HTTP API 标记为带废弃

清空数据库中的所有bunch

post /mri/clear_bunchpool 不需要参数。
把提交的一到多个bunch保存到数据库，如果  uri 对应的bunch 已经存在就是修改逻辑

post /mri/add_bunchpool
```
REQUEST
    HEADERS
        Content-Type:application/json
    BODY
        [
            {
              "uri": "mri.func.xxx",
              "beads": []
            }
        ]
```

**Comment by yeyuexia** [comment]
建议改成 /mri/bunches DELETE delete all
 /mri/bunches POST  add

**Comment by fushang318** [comment]
@yeyuexia 好

记得 @ 我，不然收不到通知

**Comment by yeyuexia** [comment]
@fushang318 ok 顺便我在mri/后面加了/system/ 就不特别全部在每张卡上说明了 这个卡我估0.5 你review下

**Comment by yeyuexia** [comment]
好吧 我错了 现在我们的util/web.py 目前不支持delete的重载的样子orz 我先再过一下再看看吧
path先暂时搁置

**Comment by fushang318** [comment]
@yeyuexia 
嗯，因为小程序要走 阿里云API网关，这个有一定限制，所以当时全部用的POST
你先考虑清楚吧，给出确定能够实现的方案

**Comment by fushang318** [comment]
@yeyuexia 
记得今天完成这个，并和 @NiuShy 协同好
![image](https://user-images.githubusercontent.com/326242/33801059-c9fcd180-dd89-11e7-9c8d-a74688cfed7e.png)

**Comment by yeyuexia** [comment]
@fushang318 申请开发 size: 0.5
代码已经提交了 还是用的delete 你可以看下先

**Comment by fushang318** [comment]
@yeyuexia 
请按照CIP工作流程来
1. 你给出 deadline 和 size 
2. 我审核标记为 in progress
3. 你进行开发和提交PR
4. 我会安排人review 你的PR
5. 合并结束

如果在开发前包括设计沟通工作，需要
1. 在ISSUE写出设计文档，可以让相关人看懂
2. @ 相关人进行讨论

**Comment by fushang318** [comment]
@yeyuexia 这个的PR我看到了，已经帮你关联了ISSUE和PR，下次注意关联 
我已经 review 完了你的PR，我在看看 @georgeliuyu 是否 reivew 完了  
如果全部review 完，我会通知你

**Comment by fushang318** [comment]
@yeyuexia|
你提交的SIZE是这个ISSUE和 #40 一共的吧，为了方便统计，我把 0.5 拆分到这两个ISSUE吧

**Comment by yeyuexia** [comment]
API
/mri/system/bunches DELETE     remove all bunches
/mri/system/bunches POST  add one or batch bunches
body:
[
{
    "uri": "mri.func.xxx",
    ...
}
]

**Comment by fushang318** [comment]
@yeyuexia 你为啥不用 markdown 格式...

**Comment by yeyuexia** [comment]
……忘记这茬了233

**Comment by NiuShy** [comment]
@fushang318  @yeyuexia 
是不是还需要一个修改的api？还是说修改就是先删除后新增的模式
还有 body体请补充完整吧，
如果文件内容没有uri是怎么请求的，
比如新建文件时是没有内容的，又或者说新建文件默认初始化内容的uri  ？
如果默认初始化 请示例初始化模版

**Comment by fushang318** [comment]
@NiuShy 
1. 如果 bunch uri 不变，直接通过新增API提交一次就是修改
2. 如果 bunch uri 有变化，就需要先通过删除API删除旧的，然后通过增加API提交新的
3. 文件内容没有 uri 就提示 文件内容没有通过校验，因为没有 uri
4. 文件校验方面完整逻辑如下
  - 每个 bunch 必须有 uri, 取值和文件路径有个对应关系，如果没有对应，提示没有通过校验不允许保存
  - 每个 bunch 必须有 condition，取值随意
  - 每个 bunch 必须有 beads，取值是数组
5. 新建文件模板如下
```
{
  "uri": "和路径有一个对应关系",
  "condition": "False",
  "beads": [
    {
      "suburi": "AA",
      "condition": "True",
      "show": "显示",
      "cmd": {
        "type": "s_choice",
        "choice": [
          {
            "c": 1,
            "d": ""
          },
          {
            "c": 2,
            "d": ""
          }
        ]
      }
    }
  ]
}
```
比如新建了一个文件在版本库路径是 `gen/mri/test@lifei.json` 那么 uri 就是 `mri.test@lifei`

今天如果有其他事情需要我协调，微信找我吧，我外出有事情
