### ISSUE TITLE
申请阅读小程序代码，并提交理解文档

### ISSUE THREAD

**Issue by ax003d** [sibbay-ai/public#226]
为了理解前端代码，方便后续工作开展，申请阅读前端小程序代码。

**Comment by ax003d** [comment]
@ben7th 申请开发 Size：1 Deadline：2018-3-31

**Comment by ben7th** [comment]
@ax003d 同意

建议可以从以下几个角度来入手：
- wepy 框架
- 目前的小程序目录结构组织
- api client 实现
- 功能和代码的对应
- oss 相关操作的实现
- mri 交互的实现

过程中我可提供答疑支持，可以通过 issue 和电话沟通的形式进行

**Comment by ax003d** [comment]
deadline: 2018-03-31
