### ISSUE TITLE
新用户进入互动

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#229]
@martinyan2015 
### 1、基本信息部分：
- 介绍突出：记录、分享和隐私安全（可以弱弱的说一句，你的日记有小白会随时进行关注和分析，并给你建议）
- 年龄增加：20-29 、40-55和55以上三个阶段
- 在此阶段free talk的响应方式。
### 2、数据录入
- 40岁以上的才询问血压和血糖；
- 建议先询问症状和和疾病；
- 23-50的女性要询问是否进行经期管理；

botmock的讨论功能有bug，打开一次只能加一个
@fushang318 有补充吗？

**Comment by georgeliuyu** [comment]
说明一下，当用户增加一个症状时小白会启动针对这个症状的对话流。这个如何协调起来。你可以试试“腹痛”  @martinyan2015

**Comment by georgeliuyu** [comment]
@martinyan2015
这是运营出的一个介绍文案，你参考：
Hi，我是小白，您的健康数据智能管家！通过健康数据的记录，您可以和社区伙伴分享健康生活的经验，还能获得专业医生的诊疗建议。拥有超强加密技术的小白时刻在您身边，保障数据安全，让您隐私无忧！

**Comment by fushang318** [comment]
@georgeliuyu 没有补充

**Comment by georgeliuyu** [comment]
@martinyan2015 把成果的链接放在这里。通给一下你需要设计的表情的文案。

**Comment by martinyan2015** [comment]
@georgeliuyu  好的

**Comment by georgeliuyu** [comment]
![image](https://user-images.githubusercontent.com/16983441/38007316-77624062-327b-11e8-8623-9e40f689b8a5.png)
![image](https://user-images.githubusercontent.com/16983441/38007325-7e2d7740-327b-11e8-87b9-f4d548cfedac.png)
![image](https://user-images.githubusercontent.com/16983441/38007336-8bcba2dc-327b-11e8-9955-9c0c1c72b096.png)
“很不幸”不建议使用哦

@martinyan2015 这个一个同学的建议。可参考。

**Comment by martinyan2015** [comment]
botmock对话链接：
基础信息：https://app.botmock.com/view/33ac72b0-2f12-11e8-8001-b9377b0ec045
第一次录入信息：https://app.botmock.com/view/dbeddf00-2f3b-11e8-8a31-9f5b65a187b4
再次进入：https://app.botmock.com/view/d9c18180-2f64-11e8-9bc7-2bd35b6f1ce4
月经query：https://app.botmock.com/view/ef335390-2f90-11e8-95ad-5fdee5e06c70

**Comment by martinyan2015** [comment]
需求文档链接：
V0.5(用户研究&产品分析):https://shimo.im/docs/ZkrNTnEEhqMLnwvv/
V0.8(需求list&产品设计):https://shimo.im/docs/LXloYgBzcf4eNT40/

**Comment by martinyan2015** [comment]
V1.0(对话话术优化)：https://shimo.im/docs/vYah1sBMbf45vXgN/
