### ISSUE TITLE
mri-mri 实现一个设置系统时间的HTTP API 

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#23]
这个HTTP API只会用于MRI仿真器
需求是：MRI仿真器需要可以调整系统当前时间，这样才能调试一些和时间相关的功能

HTTP API 设计

post /mri/set_system_date
```
REQUEST
    HEADERS
        Content-Type:application/json
    BODY
        {
            timestamp: 1512549252  # UTC timestamp
        }
```

**Comment by yeyuexia** [comment]
建议api改成 /mri/system/date PUT

**Comment by fushang318** [comment]
@yeyuexia 请给出size 和 deadline

**Comment by yeyuexia** [comment]
size: 0.2 deadline: 2017-12-11

**Comment by yeyuexia** [comment]
话说我发现这个我没法测试怎么办……你们项目里面提供的docker环境不全我没法在真实环境下测试……

**Comment by yeyuexia** [comment]
API  /mri/system/date PUT {"timestamp": 11111111}

**Comment by yeyuexia** [comment]
https://stackoverflow.com/questions/29556879/is-it-possible-change-date-in-docker-container
看了下 可能要花更多的时间 没有之前想的简单
size: 0.5 deadline 2017-12-13

**Comment by fushang318** [comment]
@yeyuexia 嗯，没问题，这个咱们微信讨论过方案了

**Comment by fushang318** [comment]
@yeyuexia 想到一个BUG，如果设置过一次时间偏移以后，再次设置时间时，逻辑就不对了吧？

**Comment by yeyuexia** [comment]
@fushang318 不会吧？应该是可以的

**Comment by fushang318** [comment]
@yeyuexia 
![image](https://user-images.githubusercontent.com/326242/34075592-44bb922c-e306-11e7-81bc-8640363b8942.png)

红色部分取出来的时间是偏差后的时间  
在已经设置过一次时间后，以后的计算时间偏差都不是基于正常时间，而是基于偏差后的时间，这样计算出来的偏差值是不对的

**Comment by yeyuexia** [comment]
@fushang318 嗯 如果是这样的话那确实是不对的
这个要改么 得在查下看看有啥解决办法

**Comment by yeyuexia** [comment]
@fushang318 我今天再提交一个版本fix这个问题把

**Comment by fushang318** [comment]
@yeyuexia OK
