### ISSUE TITLE
【紧急】启动卡顿，体验差

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#231]
![image](https://user-images.githubusercontent.com/16983441/37952359-1927b576-31d2-11e8-907e-b030fd5a5766.png)

可能的解决途径：1、技术上优化；2、增加一个小白等待的gif。3、你们的好主意

@ben7th @ax003d @Yidadaa @WangWanyue

**Comment by ax003d** [comment]
@ben7th 先把框架显示出来，再填充内容会不会好点？

**Comment by ben7th** [comment]
@georgeliuyu @ax003d 我今天优先处理此问题

**Comment by ben7th** [comment]
已初步改善视觉问题，已发体验版，本周会再做一次逻辑上的优化

**Comment by Yidadaa** [comment]
@ben7th 

先做一下profile吧，如果是网络耗时问题，就做一下本地缓存；如果是代码逻辑冗余，就需要精简代码了。

**Comment by ben7th** [comment]
deadline: 2018-04-15
