### ISSUE TITLE
关于通过小程序中向外转发的相关特性总结

### ISSUE THREAD

**Issue by ben7th** [sibbay-ai/public#236]
#### 通过小程序可以向外转发什么内容？

小程序的转发可以在微信聊天中转发一张卡片，其他人看到这张卡片后，点击卡片可以打开该小程序

#### 可以向什么地方转发？

可以转发给自己的微信好友，和自己所在的微信群

#### 可以怎样发起转发？

- 点击小程序页面右上角的“...”图标，出现的菜单里有“转发”（需要开发者在此页面做一些声明，否则没有这个菜单）
- 点击特定按钮，可以触发转发（需要开发者为这个按钮添加逻辑）

#### 转发时，哪些内容是可以由小程序开发者定义的？

- 转发标题可以自定义（默认是小程序名称）
- 看到这个转发的人，点击卡片进入的页面，可以自定义
- 可以自定义一些参数，这些参数在用户点击卡片进入小程序时会传入进来
- 转发卡片带的图片，可以自定义

#### 转发是否可以跟踪？

- 可以，转发时，如果是转发给群，可以获得一个转发信息标识（shareTicket），通过这个标识，可以知道是转发给了哪个群（只能知道群 id，不能知道其他信息。也就是说只能做跟踪用）
- 群内的微信用户，通过这个卡片点进来的时候，可以根据群 id 是否匹配，判断是通过哪个群的转发回来的。

#### 相关开发文档见此，供参考：
https://developers.weixin.qq.com/miniprogram/dev/api/share.html

若有相关讨论，也可在此 issue 进行

@georgeliuyu

**Comment by georgeliuyu** [comment]
@ben7th  @alisahuxu 公众号插入小程序能指定进入页面和自定义参数吗？

**Comment by ben7th** [comment]
@georgeliuyu 见我以前发过的这个 issue:
https://github.com/sibbay-ai/public/issues/44#issuecomment-350203428

**Comment by georgeliuyu** [comment]
@ben7th  @alisahuxu ![image](https://user-images.githubusercontent.com/16983441/38123625-b5c6ff70-340e-11e8-83cc-006637e927ab.png)
这里能作为参数吗？

场景是：
A用户在治疗小腿肌肉拉伤的过程很成功，他的日记是xx月xx日-xx月xx日。我们可写一篇推广的文章介绍这个病例。读者能点击文中的小程序按钮，直接进入小程序看该用户的日记。

**Comment by georgeliuyu** [comment]
@alisahuxu @fazhen

**Comment by alisahuxu** [comment]
目前A用户通过微信公众号，只能进入小程序A用户自己的界面。
如果A用户没有关注过B用户，不知道是否能在社区看到B。
@ben7th @georgeliuyu

**Comment by ben7th** [comment]
针对公众号进入小程序是否能带参数，进行了新的实验。实验过程：

- 把一个公众号关联到小白健康
- 在小白健康引导页增加传入参数的捕获并打印到 debug 控制台

实验结果如下：

### 从图文素材打开小程序

![image](https://user-images.githubusercontent.com/322486/38172606-ec6ed55a-35e1-11e8-977d-e09862f761ca.png)

三种图文素材：文字链接，图片链接，卡片链接，均可在路径上设置参数。小程序内均可识别参数

![image](https://user-images.githubusercontent.com/322486/38172639-8bb90a04-35e2-11e8-98f9-eccaccd8a6de.png)

![image](https://user-images.githubusercontent.com/322486/38172637-7d9d9354-35e2-11e8-932e-4984911249aa.png)

### 从自定义菜单进入小程序

![image](https://user-images.githubusercontent.com/322486/38172651-e53d79fc-35e2-11e8-83aa-996f3e88e4a8.png)

![image](https://user-images.githubusercontent.com/322486/38172835-c684b68a-35e5-11e8-9aa5-77990b5e87ea.png)

从自定义菜单进入小程序，可以识别参数

### 分包加载的页面限制

如果小程序做了分包加载，公众号只能直接进入最外层页面，不能直接进入分包内的页面

**Comment by georgeliuyu** [comment]
@ben7th 这个应该是一个icp issue

**Comment by ben7th** [comment]
deadline: 2018-04-15
