### ISSUE TITLE
小白社区贡献者ICP流程认证-zhaobinglong

### ISSUE THREAD

**Issue by maohuaming** [sibbay-ai/public#237]
对小白社区贡献者-zhaobinglong进行ICP流程认证。

**Comment by maohuaming** [comment]
@ben7th 请打上ICP标签，谢谢。

**Comment by maohuaming** [comment]
Deadline：2018-03-30 @ben7th

**Comment by maohuaming** [comment]
@ben7th 申请size:0.3

**Comment by maohuaming** [comment]
@ben7th 请处理一下，谢谢。

**Comment by ben7th** [comment]
@maohuaming OK

**Comment by maohuaming** [comment]
@ben7th 此issue请帮忙设置一下deadline，内容如下：
deadline：2018-04-02

**Comment by ben7th** [comment]
deadline：2018-04-02
