### ISSUE TITLE
mri-mri bad bead 丢弃 

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#24]
在mri的执行过程中，一旦出项一个bad bead，就会造成交互无法继续下去的问题。所以一旦发生这样的问题：

条件：没有bead return，即是问题发生；

处理：
将此bead 标记为已执行；然后取下一个bead to stage
确保sentry能拿到错误的消息。

**Comment by ax003d** [comment]
@georgeliuyu 这样处理是否不太合适？
有些 bead 是需要上一个 bead 的回答的，如果没有回答，可能无法如何选择下一个 bead。
bad bead 情况，是否可以考虑终止当前 bunch 的执行，返回错误信息给用户，同时后台记录错误信息，然后选择另外一个 bunch 继续执行？

**Comment by georgeliuyu** [comment]
@ax003d 
1、这是一种极小概率的事件，后期会加校验，用户端不建议知晓发生问题；  
2、break bunch丢弃太多，绝大多数问题是没有关联性的；  
3、这里要求sentry能正常工作的目的就是让后台知晓。

**Comment by ax003d** [comment]
@georgeliuyu 申请开发 Size：0.5 Deadline：2017-12-28

**Comment by georgeliuyu** [comment]
@ax003d 同意
