### ISSUE TITLE
mri-mri 读取用户医学检查信息的 m-lang 方法

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#25]
需求来源于 sibbay-ai/mri-wqa#5

需要读取用户医学检查信息的 m-lang 方法

**Comment by georgeliuyu** [comment]
本需求先拆分出一个需求规格书撰写的issue

**Comment by georgeliuyu** [comment]
mlang的内容见：https://shimo.im/doc/t9y37ed4Uv0WQV9z   第11章

**Comment by ax003d** [comment]
@georgeliuyu 这个可以关闭了
