### ISSUE TITLE
健康数据的数据源调研

### ISSUE THREAD

**Issue by kavonm** [sibbay-ai/public#252]
来源：https://github.com/sibbay-ai/public/issues/249
@ax003d 
调研是否可以通过后台从微信运动、小米运动、华为运动等获取数据

**Comment by kavonm** [comment]
@sinchb @ax003d 申请开发
size: 1 Deadline: 2018-04-04

**Comment by ax003d** [comment]
@sinchb 和 @kavonm 沟通过了，因为该 issue 是本周目标之一， @kavonm 下午 5 点之前无法完成，所以我会接着处理该 issue
@sinchb 申请开发 Size：0.5 Deadline：2018-4-8

**Comment by sinchb** [comment]
@ax003d ok

**Comment by sinchb** [comment]
@kavonm 超过deadline，无法完成，需要提前告知。

**Comment by ax003d** [comment]
deadline: 2018-04-08
