### ISSUE TITLE
统计历史上为小白做过贡献的数据

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#253]
@shero3 以码市和猪八戒为依据，统计所有的发包历史并按照现有标准着换位size。形成贡献者数据表。
表格式：

| github 账号| 开始时间 | CI|
|---|---|---|
|@shero3|2017-xxx|n|

@sibbay-ai/all 所有人知晓，并进行核对。

**Comment by shero3** [comment]
@georgeliuyu 那这个统计就是仅限于有github账号的人员？

**Comment by shero3** [comment]
@georgeliuyu 目前还在为小白工作的人员基本都有github，但是之前的一些人员肯定是没有了，那就不列举了

**Comment by shero3** [comment]
以下是为小白做过贡献并且有github账号的人员的贡献数据，各位可以核对一下是否有误。
@sibbay-ai/all 如有遗漏未统计者，可以回复并@我，我会再补充

| github 账号| 开始时间 | CI|
|---|---|---|
|@shero3|2018-1|7.1|
|@sinchb|2017-1|67.6|
|@fangrongxaing|2017-5|43.5|
|@alisahuxu|2018-1|13.5|
|@fazhen|2018-1|15.4|
|@lixinxuan|2017-10|15.6|
|@fushang318|2017-3|121.85|
|@yeyuexia|2017-5|26|
|@arnkorty|2017-10|13.7|
|@lvhongqiang|2017-1|6|
|@maohuaming|2018-1|3.2|
|@NiuShy|2017-11|13.5|
|@ben7th|2016-12|101.7|
|@wb14123|2017-10|22.9|
|@WangWanyue|2018-3|1|
|@pimgeek|2017-10|5.5|
|@bqx619|2017-12|14.3|
|@choufeng|2017-4|46.1|
|@Yidadaa|2017-10|29.5|
|@ax003d|2017-10|36|
|@martinyan2015|2018-3|7.2|

**Comment by sinchb** [comment]
这个包括我16年的贡献值嘛，似乎没法统计，当时是用excel表格统计的。 @shero3 @georgeliuyu

**Comment by georgeliuyu** [comment]
@sinchb 你提供一下数据，我来确定

**Comment by shero3** [comment]
deadline: 2018-04-14

**Comment by fushang318** [comment]
deadline: 2018-04-15
