### ISSUE TITLE
【设计】小白健康-健康成就的功能梳理

### ISSUE THREAD

**Issue by zhaobinglong** [sibbay-ai/public#255]
绘制健康成就流程图，整理所需元素

申请开发 deadline:2018-05-05 size:0.4  @ben7th

**Comment by georgeliuyu** [comment]
![image](https://user-images.githubusercontent.com/16983441/38292374-1b33cb62-3816-11e8-9f07-f710ff009f53.png)

**Comment by zhaobinglong** [comment]
关于小白健康成就的逻辑梳理，流程图如下 #
![default](https://user-images.githubusercontent.com/8922614/38295925-53a5400a-3822-11e8-859e-5aade9ba1e9a.png)

绘制了两张效果图，方便说明：
1：个人日记和成就页面
![wechatimg802](https://user-images.githubusercontent.com/8922614/38296174-17119b9c-3823-11e8-87a1-2bcc05e07930.png)

2：分享页面
![wechatimg803](https://user-images.githubusercontent.com/8922614/38296345-a9a634b8-3823-11e8-8966-136ce225a987.png)

**Comment by zhaobinglong** [comment]
![image](https://user-images.githubusercontent.com/8922614/38464599-f7750fbc-3b42-11e8-8424-b2379aa276dd.png)


健康成就需要包含的属性：
- 成就标题
- 开始时间
- 结束时间
- 所在医院
- 主治医师

激活事件：
场景一：当小白在向用户采集信息的时候，由小白询问用户是否康复，如果用户回答是，小白则提示用户完成了一个康复成就，进入成就编辑页面，自动输入成就标题/结束时间

**Comment by ax003d** [comment]
@zhaobinglong @georgeliuyu 这样看来，健康成就是用户自己输入的，不是根据之前的日记信息自动生成的，对吧？

**Comment by fushang318** [comment]
变更 deadline:2018-05-15
