### ISSUE TITLE
各微服务间时区处理不同

### ISSUE THREAD

**Issue by ax003d** [sibbay-ai/public#258]
各个微服务间创建数据库记录时，时区不统一，导致查询时会出一些异常。
比如 MRI 中，创建身体状况和心情，使用的是北京时间。
SNS 服务查询是按 UTC 时间进行查询，导致当天 16:00 以后输入的说说无法显示。

**Comment by sinchb** [comment]
我记得，在后端服务里有两种时间：1）timestamp，2）utc的datetime  这两种理论上都是utc的。是哪个服务，使用了北京时间存入了数据库？ @ax003d

**Comment by ax003d** [comment]
@sinchb MRI 服务

**Comment by ax003d** [comment]
MRI 服务已修改，关闭此 issue
