### ISSUE TITLE
【数据迁移】用户身高迁移到医学指标中

### ISSUE THREAD

**Issue by ax003d** [sibbay-ai/public#260]
来自：https://github.com/sibbay-ai/public/issues/249

**Comment by ax003d** [comment]
@fushang318 申请开发 Size：0.3 Deadline：2018-4-4

**Comment by fushang318** [comment]
Deadline：2018-4-4

**Comment by fushang318** [comment]
@ax003d 
deadline 新的格式要求是单独一个 comment 顶栏写

**Comment by ax003d** [comment]
@fushang318 由于代码结构调整，申请调整 size 为 0.4

**Comment by fushang318** [comment]
Deadline：2018-04-06
