### ISSUE TITLE
【前端】feed动态全部引入富文本渲染

### ISSUE THREAD

**Issue by Yidadaa** [sibbay-ai/public#264]
来源：#250

配合后端完成富文本后端渲染功能。

Size: 1
Deadline: 2018-04-07

@ben7th

**Comment by Yidadaa** [comment]
@ben7th 

记得及时标注一下这个issue的各项信息……

**Comment by ben7th** [comment]
deadline: 2018-04-11

**Comment by Yidadaa** [comment]
功能完成，关闭issue。
