### ISSUE TITLE
官网完善—网页制作

### ISSUE THREAD

**Issue by alisahuxu** [sibbay-ai/public#270]
@pimgeek 

以下是官网制作的公开招募信息，供参考。
https://github.com/sibbay-ai/operating/issues/82

我这边可以提供内容的支持，完善目前缺失的界面内容（www.sibbay.ai）
如果你需要设计支持，可以告诉我。

**Comment by pimgeek** [comment]
@alisahuxu 申请开发 Size：0.5 Deadline：2018-04-13

**Comment by pimgeek** [comment]
申请开发：@alisahuxu [Size:0.5]

**Comment by pimgeek** [comment]
完成此任务所需的文本内容由 https://github.com/sibbay-ai/operating/issues/90 提供

**Comment by pimgeek** [comment]
@alisahuxu 昨天下午我问过 @fushang318 ，他说只有 Commiter 角色才能为 issue 添加 ICP 和 size 标签。
我请 @fushang318 来这里确认一下，避免搞错。 :smiley:

**Comment by fushang318** [comment]
是的
@alisahuxu @pimgeek

**Comment by alisahuxu** [comment]
deadline:2018-04-30

**Comment by ben7th** [comment]
变更 deadline: 2018-05-15
