### ISSUE TITLE
前端设计 - mri 对话气泡的 loading 效果

### ISSUE THREAD

**Issue by ben7th** [sibbay-ai/public#272]
目前小白健康 mri 对话气泡是瞬间冒出来的。而实际用户发出对话，服务对此进行回复时，会有一个请求响应的过程，为了改善体验，可以在这个时候，采用先出现对话气泡，展示 loading 效果，然后等收到服务响应时，再实际显示对话。

参考：（lark 的演示）(需要 fq）
https://www.web.lark.com/

一分五十秒开始，有连续对话的 UI 展示。其中，正在响应中的对话气泡，有三个闪烁圆点的 loading 效果。

需求：设计适合小白健康 MRI UI 的 loading 效果，提交动态图或演示代码。并且，阅读理解小白目前 MRI 部分的代码实现，评估开发工作量。

**Comment by ben7th** [comment]
以对话气泡的 loading 为优先，另外如果有其他可以借鉴的，改善交互体验的设计，也可以引入进来进行讨论评估

**Comment by georgeliuyu** [comment]
@ben7th 
1、所有的wait bead均在进入吓一跳并loading
2、每个bead之间至少loading 500ms（发请求-->loading(500ms)--->到期且收到新的bead后显示）
