### ISSUE TITLE
【互动】第一次和每日的互动润色

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#277]
针对：
1、每日互动：https://app.botmock.com/mocks/f62e7430-3c65-11e8-bf19-b74dc19b6f8d/edit
2、第一次数据：https://app.botmock.com/mocks/f2a523c0-3bec-11e8-bac1-214a20708051/edit
3、freetalk：https://app.botmock.com/mocks/f3f5a430-3bf2-11e8-a3f5-7f2611c83687/edit
进行文字润色
@alisahuxu 安排
@fushang318 配合

**Comment by fushang318** [comment]
@georgeliuyu 好的
