### ISSUE TITLE
mri-mri: m-lang 的疾病API 逻辑问题

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/public#28]
m-lang 中有一个查询疾病的API
```
$DISEASE("ICD10:A00.052").name 
```

逻辑含义是：查询 bmesh 值是 "ICD10:A00.052" 的疾病数据的名字  
但是现在的逻辑有问题，返回值永远是None

**Comment by georgeliuyu** [comment]
@fushang318 收到
