### ISSUE TITLE
日记feed流开发结果review

### ISSUE THREAD

**Issue by WangWanyue** [sibbay-ai/public#280]
@Yidadaa https://github.com/sibbay-ai/cooperation-issues/issues/468

### 【最新】页面问题

- 步数权限未获取时不显示icon
- 没有添加心情和健康状况时不显示相应icon
- 纯文字（症状，疾病，药品等）颜色为#333333
- 指标时间的字体大小应为12px
- 未服药合并显示：**诺氟沙星** | 8:00 11:00 未服药
- 步数icon不能点击，点击药品+疾病icon出现弹窗

### 【明细】页面问题

- 【明细】改为【日记】
- 步数权限未获取时不显示icon
- 没有添加心情和健康状况时不显示相应icon
- 纯文字（症状，疾病，药品等）颜色为#333333
- 指标时间的字体大小应为12px
- 步数icon不能点击，点击药品+疾病icon出现弹窗

**Comment by WangWanyue** [comment]
deadline: 2018-04-13

@georgeliuyu 申请 size: 0.2
修改完成后我会再review一遍

**Comment by georgeliuyu** [comment]
@Yidadaa 你在pr中带这个issue
