### ISSUE TITLE
申请成为小白众和社区贡献者

### ISSUE THREAD

**Issue by icedcoke** [sibbay-ai/public#293]
内容：
@shero3
个人简介：软件开发方面有7年的工作经验，做过桌面程序开发，熟悉当前流行的前端框架，做过小程序开发；后端熟悉php开发，做过后台管理系统和网站开发，希望为社区做程序开发方面的贡献。
承诺：认同小白众和社区的价值观和icp贡献流程。

**Comment by shero3** [comment]
我这边已沟通完ICP等相关事宜
@ben7th 前端人员需要宋亮这边再确认一下，如无问题可进行icp认证

**Comment by ben7th** [comment]
@shero3 @icedcoke 同意进行 ICP 认证

**Comment by maohuaming** [comment]
@shero3 @ben7th @fushang318 @icedcoke 
ICP流程认证测试已启动。启动时间:2018-04-19 11:12

**Comment by maohuaming** [comment]
@shero3 @ben7th @icedcoke ICP流程认证测试结束。结束时间:2018-04-19  17:39
