### ISSUE TITLE
制作小白众和社区icp流程的宣传材料

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#296]
@alisahuxu 请组织制作一个icp流程的宣传材料 
思想：
1、明确核心的思想：一切自己定，自己决定做什么？自己决定多少钱？
2、不要成为后进者
目的：让更多的人了解小白社区，吸引人才。
要求：能点击进入小程序和github的连接。

@ben7th 负责支持和review
@fangrongxaing @

deadline：2018-4-30

**Comment by ben7th** [comment]
收到 ~

**Comment by georgeliuyu** [comment]
@alisahuxu 广告词还是你自己定 :smile:

**Comment by georgeliuyu** [comment]
![image](https://user-images.githubusercontent.com/16983441/39032445-21c56c7e-44a0-11e8-952a-8312c0f1fe78.png)
