### ISSUE TITLE
需求：用户在社区显示自己希望的昵称

### ISSUE THREAD

**Issue by ben7th** [sibbay-ai/public#298]
原因：
- 一些医生用户希望在社区显示自己的名字
- 部分用户希望显示自定义的昵称

初步实现想法：
- 在“配置”模块的“个人设置”页面增加一个开关：在社区里公开昵称
- 打开开关时，弹出确认
- 用户确认后，提交一个请求更新账户配置（实现一个 API）
- 之后，社区里不再显示自动匿名马甲，而是显示该用户的昵称

@Yidadaa @ax003d @ben7th

**Comment by Yidadaa** [comment]
@ben7th 本周由我来推进这个事情？
