### ISSUE TITLE
众和系统UIUE需求

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#3]
1、UI
![image](https://user-images.githubusercontent.com/16983441/32480432-d1420944-c3c9-11e7-9e05-db75f7031b9c.png)

@ben7th 你可以看看

**Comment by ben7th** [comment]
@georgeliuyu 收到

**Comment by ben7th** [comment]
众合指数的影响

- 角色升级依据
- 承接任务时的优先顺序

众合指数的来源

- 根绝 ICP 体系，算法公开

**Comment by ben7th** [comment]
已经实现，关闭
