### ISSUE TITLE
建议写一个《开放会议规范》

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#30]
@ben7th 
根据昨天站会的决议，见周日晚上9:00的会议对外开放：
目的、方式；
建议入下：
1、在固定的地方公式会议链接；
2、任何人均可收听；
3、需要发言的可在issue中提出议题；

**Comment by ben7th** [comment]
我来准备，周五提交 pr 到 public

**Comment by georgeliuyu** [comment]
@ben7th 这个issue，你看看如何处理？

**Comment by georgeliuyu** [comment]
@ben7th 嗯，本想帮你补上这个文档，但是好像觉得没有必要写了。先关了
