### ISSUE TITLE
Coop：mri仿真系统联调协同

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#31]
mri仿真系统协同，可以包括如下工作  
1. 总体负责人： @fushang318  
2. MRI仿真器前端   负责人：@NiuShy 
需要实现的功能： #
3. 新版互动管理需要的MRI http api 负责人：@yeyuexia  备份@georgeliuyu  
要实现的功能： #23 #22  #39 #40
目标：12-18日

**Comment by fushang318** [comment]
@NiuShy 你拆分一下 前端联调工作的ISSUE，我会 review

**Comment by NiuShy** [comment]
@fushang318 好的

**Comment by georgeliuyu** [comment]
@NiuShy @yeyuexia @fushang318 你们协同一下进度。

**Comment by georgeliuyu** [comment]
@fushang318 建议在public建一个milestone

**Comment by NiuShy** [comment]
前端集成issue已拆分  
#34 #35 #36 #37 #38

@fushang318 @georgeliuyu

**Comment by fushang318** [comment]
@NiuShy 你的5个ISSUE我都review 了，没有问题的已经打上标签并指定给你了，没有打标签的需要你再确定一下

**Comment by fushang318** [comment]
@NiuShy 另外我建议你增加一个熟悉现有项目代码的ISSUE， SIZE 是 1，提交物是一篇文档
写出你看代码后对业务和代码的理解和看法，以及疑惑，会有人review ，目的是先了解现有项目代码

**Comment by fushang318** [comment]
@yeyuexia 你看一下

> 新版互动管理需要的MRI http api 负责人：@yeyuexia 备份@georgeliuyu
> 要实现的功能： #23 #22 #39 #40 

看看对需求有什么问题

**Comment by NiuShy** [comment]
@fushang318  熟悉现有项目的issue #41

**Comment by fushang318** [comment]
@NiuShy 
熟悉现有项目的issue #41这个可以开始进行了，你预估一下 deadline 回复到 #41

**Comment by fushang318** [comment]
需求确认和开发计划沟通会
时间：12月8日20点
预计时长：1小时
工具：zoom.us
参会人：
@NiuShy @yeyuexia @fushang318

**Comment by fushang318** [comment]
需求确认和开发计划沟通会
时间：12月9日21点
预计时长：1小时
工具：zoom.us
参会人：
@NiuShy @yeyuexia @fushang318

会议摘要  
@fushang318 向 @NiuShy @yeyuexia 介绍ICP ，介绍要开发的业务

会议决议
1. @NiuShy @yeyuexia 12月10日完成所有工作ISSUE的开发计划排期（deadline）
2. 由 @fushang318 review 计划排期，并打上ISSUE标签标记为 in progress

**Comment by georgeliuyu** [comment]
@fushang318 @NiuShy @yeyuexia 建议：计划调整的时候在这里说明一下情况。

**Comment by fushang318** [comment]
@NiuShy @yeyuexia 你们各自在这里说明一下整体的进度安排和各个部分的deadline 吧

**Comment by georgeliuyu** [comment]
@fushang318 @NiuShy @yeyuexia 这次定下的ddl，希望能保质保量的实现。

**Comment by fushang318** [comment]
@georgeliuyu 目前前端没有碰到问题
后端时间调整实现稍微麻烦一些，@yeyuexia  正在尝试解决方法

**Comment by yeyuexia** [comment]
@fushang318 我提交了 本地测试没问题

**Comment by georgeliuyu** [comment]
@fushang318 针对这次协作，你按照icp的思想统计一下每个人的耗时，就跟在这个issue中。然后根据这个统计组织伙伴们讨论一下优化方式。

**Comment by fushang318** [comment]
@georgeliuyu 好

**Comment by fushang318** [comment]
我手动统计了 https://github.com/sibbay-ai/public/issues/31 这个协作ISSUE的乒乓
除了统计以外，有如下问题先说明一下

1. 参与者有 四人，但是其中一人只有最后在这个 ISSUE 回复了一次
  1.1 他的公司有监控，白天不能上 github
  1.2 晚上我们在微信上沟通了一些问题，所以他并没有在ISSUE中回复
  1.3 后续很长时间他的工作只在自己的ISSUE中进行的记录和 @ 我
  1.4 集成阶段碰到问题时，都是直接去他的工作ISSUE讨论问题

很多ISSUE沟通并没有在协调ISSUE中进行，有些是在微信，有些是在工作ISSUE

手动统计的协作ISSUE时间乒乓如下
1. georgeliuyu  2017年12月7日 GMT+8 下午2:51 发起 issue ，响应人是其他所有人
  1.1 fushang318 2017年12月7日 GMT+8 下午2:54 进行了响应并 @ 了 NiuShy
  1.2 NiuShy 2017年12月7日 GMT+8 下午2:57 针对 1 和 1.1 进行了响应
2. georgeliuyu 2017年12月7日 GMT+8 下午2:57 发起要求，响应人是其他所有人
3. georgeliuyu 2017年12月7日 GMT+8 下午3:06 发起要求，响应人是 fushang318
4. NiuShy 2017年12月7日 GMT+8 下午5:23 针对 1 和  1.1 的相应作出工作提交物
5. fushang318 2017年12月7日 GMT+8 下午10:23 针对 4 的提交进行 review 结果
6. fushang318 2017年12月7日 GMT+8 下午10:24 针对 4 进行了补充
7. fushang318 2017年12月7日 GMT+8 下午10:42 对 yeyuexia 进行了工作提醒，应该是第二天白天我又通过微信和 yeyuexia 沟通了这些问题
8. NiuShy 2017年12月7日 GMT+8 下午11:07 对 5 和 6 进行了工作推进提交
9. fushang318 2017年12月8日 GMT+8 上午8:48 对 8 进行了 review 和回复
10. fushang318 2017年12月8日 GMT+8 上午9:50 通过微信和大家协同好 晚上 8点开一次会议，因为有的同学家里有急事，会议取消
11. fushang318 通过微信和大家协同好 2017年12月8日 GMT+8 下午 9:00 开会
后续很多工作都是在各自ISSUE展开
12. georgeliuyu 2017年12月12日 GMT+8 上午10:46 要求大家计划调整的时候在这里说明一下情况
13. fushang318 2017年12月12日 GMT+8 上午11:27 按照 georgeliuyu 的想法提醒大家补充 deadline 
14. georgeliuyu 2017年12月13日 GMT+8 下午3:16 再次提醒大家，希望大家保质保量完成
15. fushang318 2017年12月13日 GMT+8 下午3:20 响应 14，说明了一下现在的情况
16. yeyuexia 2017年12月13日 GMT+8 下午11:25 相应 14 15，说明了情况

非常抱歉，我能力有限，实在是不知道如何统计时间和次数 @georgeliuyu

**Comment by georgeliuyu** [comment]
@fushang318 这个统计，很有参考价值。

**Comment by georgeliuyu** [comment]
@fushang318 18日的deadline完成了吗？

**Comment by fushang318** [comment]
@georgeliuyu 那要看 deadline 如何定义，现在正在进行测试环境的 review 工作，进行BUG修改

**Comment by georgeliuyu** [comment]
@fushang318 好问题，你周三例会可以提出来讨论一下。或者发一个讨论的issue，大家讨论确定。
@ben7th @sinchb 知晓
