### ISSUE TITLE
ICP的自动化统计

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#32]
这是一个讨论的issue，我在思考所有的需求是否都可从一个讨论开始，而每个具体需求是讨论产生的成果。一个讨论可以产生出多个需求，需求就会是icp issue。
所以讨论是需求的发源地。
这里开始一个讨论的issue，作为尝试。
原则：**一旦明确达成共识，就应该产生一个需求** 
那么icp自动化统计的第一个需求可以是什么？  
这个项目committer是 @ben7th

**Comment by ben7th** [comment]
第一个需求，可以是：根据 ICP 规则，通过 github API 读取所有 issue 和 pr 并统计 CI

**Comment by georgeliuyu** [comment]
那你看看如何拆解出一个有提交物的icp issue

**Comment by ben7th** [comment]
相关的 icp issue
https://github.com/sibbay-ai/public/issues/33
