### ISSUE TITLE
根据目前的 ICP 规则统计 CI

### ISSUE THREAD

**Issue by ben7th** [sibbay-ai/public#33]
### 规则
看公开规范文档

### 统计结果
按表格呈现，例如：

|ICP|size|相关 pr|贡献者|review 者|review size|
|-|-|-|-|-|-|
|#9|0.1|#10|@ben7th|@georgeliuyu|0.1|

### 目标
实现一套程序，通过 github API 读取数据，自动形成上述表格

### 其他要求
- 能够指定统计起止日期
- 对每个开发者做加总

**Comment by georgeliuyu** [comment]
@ben7th issue的pr怎么处理？

**Comment by ben7th** [comment]
@georgeliuyu 对每个 icp issue，找出 相关的 and 已合并的 pr，列在最后的统计结果里。
pr 的 review 工作按 review size 记，和 icp 的开发 size 分开

**Comment by georgeliuyu** [comment]
@ben7th 建议写一个码市的发包文档。

**Comment by ben7th** [comment]
@ben7th 申请开发 
size：2 
deadline：2017-12-20

**Comment by ben7th** [comment]
需要 @fushang318 配合提供查询用 token
https://github.com/sibbay-ai/cooperation-issues/issues/120

**Comment by ben7th** [comment]
已实现第一版代码，目前对所有 pr 进行了扫描对比，统计结果见：
https://github.com/sibbay-ai/icp-stat/blob/feature/ben7th-init-code/output/result_table.md
