### ISSUE TITLE
在小白健康朋友圈中，“取消关注” 的确认对话框似乎有问题

### ISSUE THREAD

**Issue by pimgeek** [sibbay-ai/public#331]
我在小白健康小程序里，打开我已关注用户的列表，然后再点击进入一个以关注用户的时间线，这时点击一个已关注用户的那个【关注状态】，它会提示我是否要取消关注，并给出【取消】和【确定】两个按钮。

![image](https://user-images.githubusercontent.com/1609306/39901792-44caea2e-54fd-11e8-8c81-ced5502e2951.png)

但是即使我点了取消按钮，然后回到已关注的朋友列表界面时，结果依然是变成了不再关注的状态。

这时我要是想在把那个朋友重新关注回来，反而不容易了。😓

强调一下使用意图，我是不小心点错了，我不想真正的取消关注，但是我点那个截图中对话框里的【取消】之后还是取关了。😵

**Comment by Yidadaa** [comment]
@pimgeek 

经确认，的确是取消关注的对话框逻辑出了问题。

**Comment by Yidadaa** [comment]
申请开发 deadline:2018-05-17 size:0.1
