### ISSUE TITLE
2018w20 工作计划

### ISSUE THREAD

**Issue by ax003d** [sibbay-ai/public#337]
1. 我监督的人支持名称备注
2. 扫描添加监督人
4. 关注列表中显示用户最近一次记录时间距离现在多久

<hr/>

3. 新用户注册使用新版 MRI 互动
5. 社区 Feed 中，点击某人的用药和疾病，右上角弹出框需要增加一个关闭按钮
6. 小程序首页的“最新”中添加小红点

**Comment by ax003d** [comment]
第 5 点，弹框是微信的样式，点击对话框外就可以关闭，建议不做处理，和微信样式保持一致

**Comment by ax003d** [comment]
第 6 点，如果 TAB 改成放到上方，是无法添加小红点的，这个 @ben7th 已经给出调研记录

**Comment by ax003d** [comment]
其余的本周可能没有时间推进了

**Comment by georgeliuyu** [comment]
熊医生可以先开始推进，备注我们会尽快解决，一旦确定时间会第一时间通知你。
