### ISSUE TITLE
在小白健康首页，“当前步数” 的数值明显小于 “微信运动” 中的数值？

### ISSUE THREAD

**Issue by pimgeek** [sibbay-ai/public#339]
已经连续好几天发现这个情况，今天决定汇报一下：

- 在小白健康的首页，显示步数 3025

![image](https://user-images.githubusercontent.com/1609306/40034330-0814e4f6-582f-11e8-9d02-fd62f6bb9834.png)

- 在微信运动内部，显示步数 7299

![image](https://user-images.githubusercontent.com/1609306/40034325-029818ae-582f-11e8-834f-637ecdefb697.png)

注：我已经在小白健康的“配置->通用配置”中启用了读取微信步数的选项

![image](https://user-images.githubusercontent.com/1609306/40034456-9c697cde-582f-11e8-95aa-6416a9178e2a.png)

**Comment by ben7th** [comment]
@pimgeek 这个数值也是从微信运动的接口获取的，如果不一致，可能是微信运动内部的问题

**Comment by ax003d** [comment]
@pimgeek 小程序中的步数信息不是实时更新的，每次打开小程序才会去更新步数

**Comment by pimgeek** [comment]
@ax003d 我能理解步数信息并非实时更新，不过即使完全删除小程序，然后再重新安装，重新微信登录，重新授权使用步数，仍然存在这个问题 😕

**Comment by ax003d** [comment]
@pimgeek 你看看小程序中的社区中个人的历史数据，看看之前的步数是否准确。
每次打开引导页，都会获取最近 30 天的步数数据，并更新到数据库中的。

**Comment by pimgeek** [comment]
微信步数的问题，是我看错了，我最近几天在微信运动中打开的都是 “前一天晚上的步数数据”，所以会和小白健康首页上的数值不同。

这个问题是误报，现在可以关闭了。 😅
