### ISSUE TITLE
MRI仿真器生命周期相关的前端集成

### ISSUE THREAD

**Issue by NiuShy** [sibbay-ai/public#34]
需要集成的接口
1. MRI仿真器 启动
2. MRI仿真器 停止
3. MRI仿真器 重启
4. MRI仿真器 重新初始化
5. 模拟用户列表

相关资源

- API文档： https://sibbayms.docs.apiary.io/#reference/0/mrisandbox
- @fushang318  模拟用户列表的接口需提供

size：2

@fushang318

**Comment by fushang318** [comment]
@NiuShy 
有如下几个问题
1. 模拟用户列表目前是前端写死的50个ID，不用从后端接口读取
2. 我预估 size 在 1 左右，你是怎么考虑的

**Comment by NiuShy** [comment]
@fushang318 可以

**Comment by NiuShy** [comment]
@fushang318 申请开发 size：1 ，deadline：2017-12-18

**Comment by fushang318** [comment]
@NiuShy 已标记 In Progress
后端API是我开发的，有问题找我协调

**Comment by fushang318** [comment]
@NiuShy 

MRI仿真器 重新初始化 的后端API如何调用，我没有介绍清楚，我补充一下
重新初始化是
1. 删除 MRISandbox
2. 获取 MRISandbox 状态，等到确定删除完毕
3. 启动 MRISandbox

**Comment by NiuShy** [comment]
@fushang318  已添加 重新初始化功能 ，已提交
