### ISSUE TITLE
MRI事件相关的前端集成

### ISSUE THREAD

**Issue by NiuShy** [sibbay-ai/public#35]
需要集成的接口
1. 事件列表
2. 事件新增
3. 事件删除
4. 事件修改
4. 事件发送

相关资源
- API文档： https://sibbayms.docs.apiary.io/#reference/0/mrivirtualevent/get-syminfodraft

size：1

@fushang318

**Comment by fushang318** [comment]
@NiuShy 这几个接口相对逻辑比较简单，没有什么需要沟通的，按照API文档集成即可  
注意按照ICP规范来提交代码和创建PR

**Comment by NiuShy** [comment]
@fushang318 申请开发 size：1 ，deadline：2017-12-18

**Comment by fushang318** [comment]
@NiuShy 已标记 In Progress

**Comment by fushang318** [comment]
@NiuShy 后端API是我负责开发的，有问题找我协调
