### ISSUE TITLE
【review】关于EI的配对

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#350]
根据本期的配对结果：
1、医疗、平面设计、运营和财务人员不要进行技术类比较；
2、建议@sincb 可以作为备用人员。可以征求一下意见
3、尽量将非技术和技术类的issue分开配对。

可以考虑的手段：增加类型label，根据pr的库决定issue的类型，或者其他。

@fushang318

**Comment by fushang318** [comment]
@georgeliuyu 
可以这样，按照贡献者来区分类型 ，非技术的ISSUE单独一个配对池子来配对

**Comment by fushang318** [comment]
申请开发 deadline:2018-05-23 size:0.5

**Comment by fushang318** [comment]
比预期的麻烦一些，解决了几个小BUG。。

**Comment by fushang318** [comment]
link https://github.com/sibbay-ai/public/issues/348
