### ISSUE TITLE
关于发放平台迁移的通知

### ISSUE THREAD

**Issue by shero3** [sibbay-ai/public#351]
@sibbay-ai/all 之前已经有发过相关的issue，由于税点以及发票等各方面因素，之后的费用发放将不再通过码市或者猪八戒，目前我们选择了小鱼儿平台上，网址：https://www.xiaoyuer.com/
小鱼儿平台目前是收取6%的费用，提现会在1-2个工作日内到账。

现在需要各位贡献者，去小鱼儿平台上进行注册以及认证，将用户名回复至本issue中。

**Comment by maohuaming** [comment]
用户名：13770607057
邮箱：maohuaming1010@163.com

**Comment by ax003d** [comment]
邮箱：ax003d@qq.com

**Comment by zhaobinglong** [comment]
用户名：15101056160

**Comment by bqx619** [comment]
用户名: 17681393942
邮箱: bqx619@gmail.com

**Comment by fazhen** [comment]
邮箱：1951884195@qq.com

**Comment by skytian1** [comment]
用户名：13066980534

**Comment by sinchb** [comment]
用户名： 18616370690
邮箱： sinchb128@gmail.com

**Comment by akakenle** [comment]
用户名：akakenle
邮箱：akakenle@gmail.com

**Comment by ben7th** [comment]
用户名：13811174717 宋亮
