### ISSUE TITLE
 EI 投票系统上线试运行

### ISSUE THREAD

**Issue by shero3** [sibbay-ai/public#352]
小白(Sibbay)众和社区的 效率指数（Efficiency Index) 简称 EI 的 投票系统已经上线试运行
效率指数（Efficiency Index) 的详细介绍请看 https://github.com/sibbay-ai/public#8%E8%AF%84%E4%BB%B7

2018-04-15 至 2018-05-15 这个周期的EI投票已经生成，现在可以投票了（试运行）
需要在 2018-04-15 至 2018-05-15 这个周期有 ICP 贡献的同学登录系统并投票

投票方法如下
1. 访问 http://sibbay-icp-stat-view.oss-cn-hangzhou.aliyuncs.com 并登录
2. 登录成功后，点击顶部导航栏中的 “EI统计“，进入 EI统计月份列表 页面
3. 在 EI统计月份列表 页面，点击 2018_05_15 这行条目的右侧的 去投票，记入投票页面
4. 在投票页面，点击每一行的”投票“按钮，在弹出框中，二选一，选择你认为效率高，质量高的贡献，点击选中，并提交

对投票系统有任何问题反馈，都在该ISSUE下回复即可
@sibbay-ai/all

**Comment by shero3** [comment]
@sibbay-ai/all  所有的贡献者进行上个月的EI评价，截止时间为5月31日24:00。

如有疑问，可回复至此issue：https://github.com/sibbay-ai/cooperation-issues/issues/724

**Comment by fushang318** [comment]
@shero3 我已经完成投票

**Comment by pimgeek** [comment]
@shero3 我也完成了投票，共 7 对。

**Comment by ben7th** [comment]
@shero3 我已经完成投票，共 21 对

**Comment by sinchb** [comment]
@shero3 我已经完成投票，共4对
