### ISSUE TITLE
ICP 认证流程申请：@akakenle

### ISSUE THREAD

**Issue by ben7th** [sibbay-ai/public#357]
### 内容

- 申请者： @akakenle 
- 指导者(mentor)： @maohuaming 
- 人事负责人： @shero3 
- 工作类型：产品设计

### 步骤

- 请 @shero3  与 @akakenle  进行沟通，确认奖励定级标准；
- 沟通完毕后， @shero3  通知 @akakenle  和 @maohuaming  参考 [贡献者认证流程](https://github.com/sibbay-ai/public/blob/master/%E8%B4%A1%E7%8C%AE%E8%80%85%E8%AE%A4%E8%AF%81%E6%B5%81%E7%A8%8B.md) 进行贡献者认证；
- 在本 issue 上记录认证结果；

**Comment by shero3** [comment]
@ben7th 你这边需要给我些人员的相关信息，以及奖励标准的意见

**Comment by maohuaming** [comment]
@ben7th @shero3 akakenleICP流程认证通过。
