### ISSUE TITLE
MRI仿真器系统当前时间的前端集成

### ISSUE THREAD

**Issue by NiuShy** [sibbay-ai/public#36]
需要集成的接口

1. 获取当前仿真器系统时间
2. 更新当前仿真器系统时间

相关资源
- 暂未提供

size：0.5

@fushang318

**Comment by fushang318** [comment]
@NiuShy 

这个需要 @yeyuexia @georgeliuyu 先完成如下两个API的实现才能进行联调工作
获取当前仿真器系统时间 #39
更新当前仿真器系统时间 #23 

需求上注意
1. 前端读取到系统时间后，需要页面上的时间一直在一秒一秒的走
2. 要保证页面上的时间和后端系统时间几乎相一致（误差控制在秒级），可以过一小段时间同步一次

**Comment by NiuShy** [comment]
@fushang318 申请开发 size：0.5，deadline：2017-12-18

**Comment by fushang318** [comment]
这个 @NiuShy deadline 暂定吧，后端API还没有完成

**Comment by fushang318** [comment]
@NiuShy 后端API已经开发完成并且部署了

### HTTP API 地址

这几个HTTP API 的地址 HOST 是 #34 中的 获取 MRISandbox 状态 API 返回的 server_url

### HTTP API 说明

在 #23 #39 回复中有说明
