### ISSUE TITLE
T恤～讨论issue

### ISSUE THREAD

**Issue by fangrongxaing** [sibbay-ai/public#360]
其中共计三套
其中前两套已经淘汰出局了
**第三套（楼梯那个刘总比看好～可以多提那个修改意见哦！😁**https://shimo.im/docs/IWgHW4CAGlYc9B3y/ 点击链接查看「方案3」，或复制链接用石墨文档 App 打开
草案 ，细节都有修改下 大家可以提啊提意见
![9](https://user-images.githubusercontent.com/33997808/40872691-06e7b7f2-6685-11e8-943d-8177992277f3.png)
![88](https://user-images.githubusercontent.com/33997808/40872701-24b88f86-6685-11e8-8379-a8a07c34a0b2.png)

**Comment by fangrongxaing** [comment]
一条一条的台阶是小白字体的拆分
其投影就是小白字体
台阶由下到上
在每个台阶有人的年龄段
从小孩到老人
表示小白可以陪伴一生或是......

**Comment by sinchb** [comment]
楼梯这个有创意， + 1

**Comment by fushang318** [comment]
- 可不可以有黑色或者灰色的T恤
- 我比较喜欢手机和听诊器的那套

**Comment by fangrongxaing** [comment]
![ok5](https://user-images.githubusercontent.com/33997808/40906344-1b4f83a2-6813-11e8-8633-da8de2cf04d6.png)

**Comment by fushang318** [comment]
背景的 小白两个字是什么字体？和 右上是一种字体吗？仔细看貌似是一种字体，但是总感觉和  桥的 毛笔字的飘逸感没有很好的形成一个整体
有没有更贴合毛笔字感觉的字体

额，个人直观感觉哈，我审美比较渣

**Comment by zhaobinglong** [comment]
我觉得右上角放的文字太多，需要留白一些，只保留小白的二维码会更好一些
![image](https://user-images.githubusercontent.com/8922614/41073493-247ca8fe-6a36-11e8-9180-4117414925ac.png)

**Comment by fangrongxaing** [comment]
好的
