### ISSUE TITLE
2018W23 目标@zhaobinglong

### ISSUE THREAD

**Issue by zhaobinglong** [sibbay-ai/public#365]
来源: https://github.com/sibbay-ai/public/issues/362 
风暴行动链接: sibbay-ai/cooperation-issues#758

- [x] MRI仿真器H5细节优化（实现所有的需求，达到待验收状态）
- [x] 处理issue中反馈的前端bug，处理过的issue会链接到这里

**Comment by fushang318** [comment]
MRI仿真器H5 这个本周应该不能完全结束掉，只能是从开发角度整体完成所有功能，但是集成和调整一些琐碎的细节还是需要下周继续做的

**Comment by zhaobinglong** [comment]
好的，本周完成所有功能性的开发，下周完成后续的集成等工作

**Comment by zhaobinglong** [comment]
总size：1.3
