### ISSUE TITLE
ICP 认证流程申请：@zhanhh187

### ISSUE THREAD

**Issue by ax003d** [sibbay-ai/public#368]
### 内容

- 申请者： @zhanhh187
- 指导者(mentor)： @maohuaming 
- 人事负责人： @shero3 
- 工作类型：QA

### 步骤

- 请 @shero3  与 @zhanhh187 进行沟通，确认奖励定级标准；
- 沟通完毕后， @shero3  通知 @zhanhh187和 @maohuaming  参考 [贡献者认证流程](https://github.com/sibbay-ai/public/blob/master/%E8%B4%A1%E7%8C%AE%E8%80%85%E8%AE%A4%E8%AF%81%E6%B5%81%E7%A8%8B.md) 进行贡献者认证；
- 在本 issue 上记录认证结果；

**Comment by shero3** [comment]
@maohuaming 已与@zhanhh187沟通完毕，可以开始进行ICP认证

**Comment by maohuaming** [comment]
@shero3 收到。

**Comment by maohuaming** [comment]
@ax003d @shero3 请提供zhanhh187联系方式。

**Comment by maohuaming** [comment]
@ax003d @shero3 zhanhh的第一次ICP认证结果反馈：由于认证过程中违规次数达到四次，根据现行的认证规则，视为认证不通过。
详细认证过程，请参见如下链接：
[issue]
https://github.com/zhanhh187/authenticationtest/issues/2
https://github.com/zhanhh187/authenticationtest/issues/1
[pr]
https://github.com/zhanhh187/authenticationtest/pulls

**Comment by ax003d** [comment]
@maohuaming @zhanhh187 今天你们沟通个时间，再做一次认证吧

**Comment by maohuaming** [comment]
@ax003d 收到。

**Comment by ax003d** [comment]
认证通过，关闭该 issue
