### ISSUE TITLE
关于图片上传

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#369]
鉴于医疗对图片精度的高要求，所以在存档中上传的图片均要求以“原图”方式上传。
相关考虑：
1、是否同时上传压缩文件（或在后端采用fc自动压缩）
2、在feed流中仅仅显示压缩图片，点击查看则显示原图。
3、上传要有进度条显示。
4、取消9张的限制，但是feed流中最多显示9张

7月1前要实现

@akakenle @ben7th @ax003d

**Comment by ben7th** [comment]
@georgeliuyu @akakenle @ax003d 

其实不用这么麻烦，只需要上传原图就可以了。用于显示的缩略图借助阿里云 OSS 有非常方便的实现，只要图片被上传到阿里云，在他的 URL 上增加参数就可以获取到图片的缩略图。后端不用做任何工作，前端就可以控制。

举例：

原图：
https://oss-public.xiaowhite.com/image/avatar/user/7dddc19a-658c-797c-d11d-1990e94828fb.jpg

100 * 100 缩略图（URL 加参数来获取）：
https://oss-public.xiaowhite.com/image/avatar/user/7dddc19a-658c-797c-d11d-1990e94828fb.jpg?x-oss-process=image/resize,m_fill,h_100,w_100

还有其他一些图片处理都可以加参数实现（如内切圆，获取单色图，锐化等），相关文档：
https://help.aliyun.com/document_detail/44695.html

所以，上述工作可以不用后端处理，前端上传原图就可以了

**Comment by ben7th** [comment]
实际上我正在做的一项整体优化工作就是在每个图片显示的地方（如用户头像）加上合理的参数来获取合适的缩略尺寸显示，来提升性能
