### ISSUE TITLE
MRI github repo api 的前端集成

### ISSUE THREAD

**Issue by NiuShy** [sibbay-ai/public#37]
需要集成的接口

1. 获取仓库文件树
2. 新增文件
3. 删除文件
4. 修改文件
5. 发送pull request

相关资源
- 调试库  https://github.com/sibbay-ai/ms-issue/issues/89
- token   https://github.com/sibbay-ai/ms-issue/issues/89
- github api相关文档  
 - - 内容操作 https://developer.github.com/v3/repos/contents/
 - - 分支操作 https://developer.github.com/v3/repos/branches/
 - -  pull request相关 https://developer.github.com/v3/pulls/reviews/#submit-a-pull-request-review

size：3

@fushang318

**Comment by fushang318** [comment]
@NiuShy 这个需求有一些细节还没有跟你介绍，大概是这样的：
1. 每个后台用户访问这个界面，都会在github 版本库创建一个自己的分支，叫做 ms/<user_login>  如果分支已经存在，就直接读取
2. 读取，新建，编辑，删除，等操作都是在这个ms/<user_login>分支进行
3. 确定编辑完成后，有一个提交按钮，会发起一个PR ,  ms/<user_login>分支 to develop 分支

你看看如果这样的话，需求上你是否能够理解，有没有疑惑

**Comment by NiuShy** [comment]
@fushang318  调整了相关资源和size

**Comment by georgeliuyu** [comment]
@fushang318 确定好人员，要打上 In Progress的label

**Comment by georgeliuyu** [comment]
@NiuShy 根据icp的规范，请加一句下面的文字
![image](https://user-images.githubusercontent.com/16983441/33747955-c982ecec-dc00-11e7-868a-fd39e872af69.png)
说明：自己提出的issue也是可以的。

**Comment by NiuShy** [comment]
@georgeliuyu  晚上会后加上

**Comment by NiuShy** [comment]
@fushang318  我的token并不能访问测试仓库，是不是需要仓库owner的token

**Comment by fushang318** [comment]
@NiuShy 已经给你 https://github.com/sibbay-ai/ms-test-data-mri 版本库最高权限 ，你再试试

**Comment by fushang318** [comment]
@NiuShy 你给出一个 deadline

**Comment by NiuShy** [comment]
@fushang318  申请开发 size：3 ，deadline：2017-12-15

**Comment by fushang318** [comment]
@NiuShy 好的  
昨天晚上到今天中午 ms-view 的develop 合并了一些新版权限管理的代码，因为是整体改动，你最好提前看看有没有冲突..我可以和你一起协调一下这个冲突问题

**Comment by NiuShy** [comment]
@fushang318  github api 前端集成遇到的问题
对文件夹的操作相关

1. 不能只新建文件夹   可以新建形如  a/b/c.json 的格式，会生成文件夹
2. 不能直接删除文件夹  如果文件夹内只有一个文件  删除该文件会删除文件夹
3. 不能修改文件夹

**Comment by NiuShy** [comment]
演示 https://pan.baidu.com/s/1mirFDKs

**Comment by fushang318** [comment]
@NiuShy 

> github api 前端集成遇到的问题
这几个问题是受限于它的API，但是我看你的演示上已经通过其他方式的操作达到修改的效果，没有问题

完成效果非常赞赞赞~

**Comment by fushang318** [comment]
@NiuShy 可以提交PR了

**Comment by NiuShy** [comment]
@fushang318  github api token 需要从环境变量读取
