### ISSUE TITLE
关于用户记录数据的修改限制   P2

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#370]
鉴于医疗数据的严肃性和防止篡改。特别是针对奖励模型和确保公正性原则。
在小白上面记录的症状、疾病、医学指标、用药/治疗和存档的数据在超过7天后就用户就不可进行修改。

P0：紧急且重要
P1：紧急但不重要
P2：不紧急但重要
P3：不紧急也不重要，但是低成本

@akakenle @ben7th @ax003d

**Comment by ben7th** [comment]
@akakenle @georgeliuyu @ax003d 

需要进行的工作：

1. 前端限制
2. 前端对于此种不可保存的情况的显示，和相关提示
3. 后端限制
4. 调用 API 时，此种不可修改的情况下的返回值
