### ISSUE TITLE
关于确保EI评价顺利推进的建议

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#372]
鉴于EI的值是由社区的贡献者相互评价的，且对贡献者有极大的影响。
为确保评价的按时完成，建议社区的奖励发放的条件要包含EI评价完成。
请大家在下面发表意见
2018-6-13 24:00结束
如果通过 @shero3 请写入icp的规范，并按此执行。

@sibbay-ai/all

**Comment by georgeliuyu** [comment]
同意

**Comment by zhaobinglong** [comment]
是否可以增加一个中立票或者弃权票，在贡献者对当前两个选项的工作不了解和无法判断的时候使用

**Comment by shero3** [comment]
根据刘总要求是要在完成评价后进行奖励的发放，那目前的节奏一般是每月的16号会完成icp的统计工作，一般会在17号开始发放，是否EI的评价要求在16号24点之前完成，17号发放之前是否能有一个统计数据给到我，我以此数据作为是否发放的标准 @fushang318 @georgeliuyu

**Comment by fushang318** [comment]
@shero3 
这个需要我们配合完成，现在的投票逻辑是这样的
1. 首先需要确保大家都完成了CI统计
2. 在1 完成的基础上，系统才能正确产生投票并分配给大家
3. 需要给大家两天的时间投票
4. 投票完成，关闭投票，并进行发放

所以时间安排需要规划，现在大家普遍不能保证 17号凌晨完成CI统计，一般都是 17号晚上左右的样子才能完成

**Comment by georgeliuyu** [comment]
有几点建议：
1、到截止时间无效的icp的issue不计入本月，可以计入下月；
2、EI评价后就可提出奖励发放，EI评价越晚则发放越晚；
3、是否一定要调整时间如何调整，建议根据这次发放的情况再进行讨论；
@shero3 @fushang318

**Comment by fushang318** [comment]
嗯

**Comment by georgeliuyu** [comment]
@zhaobinglong @fushang318 从EI设计的结构来说不能有弃权票，否则对被评价者不公平。

**Comment by zhaobinglong** [comment]
@georgeliuyu @fushang318  我的想法是，假设投一票是1分，贡献者选择了中立或者弃权，则两个选项分别获得0.5分，表示这两个被投票的贡献者在本次issue开发中效率和质量打平

**Comment by shero3** [comment]
@georgeliuyu 如果这个月就要按照这个时间来执行的话我这边有点问题，我20-26日外出旅行，这样的话可能我出发前没法完成本月发放了……

**Comment by fushang318** [comment]
搬运 @georgeliuyu 在微信上的留言
```
对了，你说我突然想到个事儿啊，就上次在讨论说，能不能给出零点几分这样一个建议啊，我觉得这个还是有点害处，因为很容易造成大家愿意。习惯性的给0.5跟0.5，因为。比如说他不太有把握，比如说他不太愿意动脑筋。比如说他。我种种原因吗，就是因为这回造成这个结果会是一个。思考成本最低的结果，所以说我的还现在暂时不要去做。这个功能的真假。
```

@zhaobinglong

**Comment by ben7th** [comment]
建议不要各自 0.5 否则容易演化成最后都投各自 0.5
