### ISSUE TITLE
尝试站在远程工作者的视角上，全面介绍小白众和组织的 ICP + EI 协作体验

### ISSUE THREAD

**Issue by pimgeek** [sibbay-ai/public#378]
2018-06-15 中午，通过 @georgeliuyu 得知，小白众和组织的 ICP + EI 协作模式已经初步运行起来，并且通过对各项工作成果及其投票数据的统计分析，可以明显看出哪些成果的被认可度高，哪些成果被认可度低。这些认可度数据，将有助众和组织内的贡献者们及时发现协作中出现的问题，并做出调整和修正。

![image](https://user-images.githubusercontent.com/326242/41449864-39fa92d4-7096-11e8-87ac-5540733cd9b9.png)

做为小白众和组织的内容贡献者之一，我在正式参与小白众和组织之前，就曾做过一次测试任务（介绍一种新型的问答交互方式），对众和协作模式的以人为本，自愿自主，有劳先酬，平等协作等理念产生浓厚的兴趣。

所以，在下一个工作周期内，我决定多方收集信息，**撰写一篇深入、细致的小白众和组织 ICP + EI 协作模式的介绍文章**。初步设想，我将站在远程工作者 / 自由职业者的视角上，以 “未来 50 年将会兴起什么样的工作/协作模式” 为引导，内容主体尝试综合众和理念、亲身体验、原理分析/数据支撑、实际运行效果等，把小白众和组织向更多潜在的协作者们做一次 **充分、全面且令人印象深刻的展示**。

本 issue 将作为此项工作的原始需求描述，和相关信息情报汇总处。 😄

**Comment by pimgeek** [comment]
沙发先占上，在这里随便写一些草稿，以便为自己和其他内容提供者们打开思路 😃

2017-10 刚刚接触众和协作时，我只是作为远程工作者，对其形成了一些初步印象，这包括：

* “接包方”未决定参与项目时，仅做到认真阅读“发包方”的项目文档，就可以获得报酬
* “接包方”决定参与项目时，并不需要把“发包方”当做传统意义上的“甲方”，把自己当作传统意义上的“乙方”，而是成为发言权相对平等的两个“协作方”
* “发包方”可能就项目提出指导性需求，也可能不提
* “接包方”在理解项目的基础上，可以独立自主，或者参考“发包方”的指导性需求，提出自己的改进意见
* “接包方”与“发包方”充分沟通，决定正式落实工作前，由“接包方”提出预计的工作量和截止日期，“发包方”认可后即开始实施。
* 按质按量完工后，“发包方”将通过合法合规的在线外包服务平台，把工作报酬付给“接包方”。

@ben7th @fushang318 @fangrongxaing @fazhen 你们看过上面的介绍后，若有相关信息或情报，也可以发给我，我会设法整合到最终的文章中。 💡

**Comment by georgeliuyu** [comment]
@pimgeek 上面那个图 @fushang318 给新版的更清晰。

**Comment by fushang318** [comment]
@georgeliuyu @pimgeek 我今天完成新版的修改，然后截图贴到这里

**Comment by fushang318** [comment]
![icp stat view](https://user-images.githubusercontent.com/326242/41397937-536269ee-6fe8-11e8-9e1e-176b05ef877f.png)

**Comment by fushang318** [comment]
@pimgeek 更新一下
![icp stat view 2](https://user-images.githubusercontent.com/326242/41449864-39fa92d4-7096-11e8-87ac-5540733cd9b9.png)

**Comment by pimgeek** [comment]
已更新。

**Comment by pimgeek** [comment]
第一受访者：“我觉得最令我困惑的是激励的问题，这是组织生长的力量”。后续讨论过程会摘要显示在此。
