### ISSUE TITLE
MRI仿真器集成启用互动脚本前端功能

### ISSUE THREAD

**Issue by NiuShy** [sibbay-ai/public#38]
需要集成的接口

1. 清空数据库中的所有bunch
2. 把提交的一到多个bunch保存到数据库
3. 删除指定bunch uri

相关资源
- 后台接口 https://github.com/sibbay-ai/public/issues/22  #40 

size：0.5

@fushang318

**Comment by fushang318** [comment]
@NiuShy 

这个需求的详细情况我给你介绍一下
1. 后台用户进入这个界面后，需要读取用户对应分支上的 gen 目录下的所有 json 文件，然后分别调用两个后台接口，保证刷新所有数据到数据库
2. 用户每次新建保存后，编辑保存后，删除保存后都需要调用后台接口，保证同步了最新状态到数据库
3. 同步数据需要有比较人性化的提示，比如进度条  

你看看如果这样，需求上你是否清晰了，有没有疑惑？

然后相关资源和 size 是否需要修改

我觉得相关资源缺少一个删除API，需要后端提供一个删除API
SIZE 0.5 肯定不够吧

**Comment by NiuShy** [comment]
@fushang318  明白了，你看着增加size吧

**Comment by fushang318** [comment]
@NiuShy 
相关资源需要增加  https://github.com/sibbay-ai/public/issues/40 吧
仔细考虑好，相关资源

**Comment by NiuShy** [comment]
@fushang318 #22 上描述了清空的接口

**Comment by fushang318** [comment]
@NiuShy 
用户每次删除文件后都需要调用后台接口，保证同步了最新状态到数据库
如果处于效率考虑是不是只删除比较合适，而不是清空？

**Comment by NiuShy** [comment]
@fushang318  不好意思看错了  ，的确缺失了删除的接口

**Comment by NiuShy** [comment]
@fushang318 申请开发 size：1 ，deadline：2017-12-18

**Comment by fushang318** [comment]
@NiuShy 已经标记 In Progress

后端API已经完成开发，是由 @yeyuexia 开发的，有问题在这里联系 @yeyuexia

**Comment by NiuShy** [comment]
@fushang318  @yeyuexia 
请提供可供测试的api 地址和文档

**Comment by yeyuexia** [comment]
api在每张卡下面写了的 地址你问下 @fushang318

**Comment by fushang318** [comment]
@NiuShy 
### HTTP API 地址
这几个HTTP API 的地址 HOST 是 #34 中的 获取 MRISandbox 状态 API 返回的 server_url


### HTTP API 说明
在 #22 #40 回复中有说明
不过 response 不够清晰，需要 @yeyuexia 补充说明
