### ISSUE TITLE
在icp统计中加入CI表

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#382]
@fushang318 在icp的系统中增加CI的总表，基数以https://github.com/sibbay-ai/public/wiki/CI-%E8%B4%A1%E7%8C%AE%E6%8C%87%E6%95%B0%E8%A1%A8 为准。

**Comment by fushang318** [comment]
这里表里的内容是截止到 5月15日的吗
@georgeliuyu @shero3

**Comment by shero3** [comment]
@fushang318 是的

**Comment by fushang318** [comment]
看到了，CI = 历史累计CI + 当月ES

**Comment by fushang318** [comment]
已经完成
