### ISSUE TITLE
2018_06_15 周期的EI投票开始了

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/public#388]
原计划定于 6月 17日 到 19日 的投票周期，因为如下原因耽搁了
1. @ben7th @zhaobinglong @alisahuxu @bqx619 @shero3 晚提交了 ICP 统计，耽误了一天多
2. @fushang318 实现的的 EI 系统中的配对算法有问题，导致这个月没法正常配对，然后修改算法修复问题，耽误了一天多

现在已经可以正常投票了

请以下成员
@sinchb  @fushang318 @maohuaming @shero3 @ben7th @zhaobinglong @ax003d @fazhen @skytian1 @bqx619 @fangrongxaing @alisahuxu 

登录 http://icp.sibbay.ai/ 完成 2018_06_15 周期的投票
**截止日期是： 6 月 22 日凌晨0点前**

**Comment by zhaobinglong** [comment]
关于EI投票弃权的再次讨论

本轮投票中，有个别任务让我投票是一个很艰难的决定，如：
<img width="1008" alt="wx20180619-170710 2x" src="https://user-images.githubusercontent.com/8922614/41588474-72de7452-73e4-11e8-98ec-1eccbcc915ee.png">

两位贡献者都完成了相关周目标，所处理的工作没有共通的地方，都是各自领域内的任务，没有一个唯一的参考标准来投票，所以我觉得我只能投弃权票，如果没有这一票，我只能随机投

@fushang318 @georgeliuyu

**Comment by fushang318** [comment]
@zhaobinglong 可以随机，我提供一个思路，可以看大家的ISSUE编写规范，这也是一个指标，或者这两个人平时和你沟通时的效率等因素，anyway 都可以参考的

**Comment by georgeliuyu** [comment]
@zhaobinglong 能坚持自己的看法，推动社区进步和改善，很好。EI的方式就是希望发挥个人的主观能动性和创造力。正式为了防止妥协才采用这种二选一的方式，拒绝中庸。希望能发现新的评价角度。建议先运行一段时间后来再看看。

**Comment by fushang318** [comment]
我已经完成投票

**Comment by georgeliuyu** [comment]
@fushang318 已投

**Comment by maohuaming** [comment]
@fushang318 建议将EI统计月份列表的排序方式改成倒序排序，这样一来当月投票的链接就一直置顶，不用滚动到列表最低部去。
![default](https://user-images.githubusercontent.com/28720671/41635493-9cebea94-747b-11e8-95b1-93d1e9924695.png)

**Comment by fushang318** [comment]
@maohuaming 好

**Comment by maohuaming** [comment]
投票完成。

**Comment by sinchb** [comment]
投票完成 @fushang318

**Comment by maohuaming** [comment]
@georgeliuyu EI投票过程中发现一个现象：就是有很多issue的申请开发时间（starttime）与引用该issue的pr的合并时间（mergetime）只间隔了几分钟，但是申请的size却超过0.1甚至更大，是否符合ICP流程的规范？合理的情况应当是：
starttime（申请开发时间）+size（开发耗时）<=mergetime（pr合并时间）<=deadline(任务截止时间）

**Comment by bqx619** [comment]
@fushang318 完成投票

**Comment by alisahuxu** [comment]
已经完成投票
