### ISSUE TITLE
mri-mri 实现一个读取系统时间的HTTP API 

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/public#39]
这个HTTP API只会用于MRI仿真器
需求是：MRI仿真器需要可以读取系统当前时间，这样才能调试一些和时间相关的功能

HTTP API 设计

get /mri/get_system_date
```
RESPONSE
    BODY
        {
            timestamp: 1512549252  # UTC timestamp
        }
```

**Comment by yeyuexia** [comment]
@fushang318 申请开发 size: 0.2  deadline: 2017-12-11

**Comment by fushang318** [comment]
@yeyuexia 好的，我已经标记好了，你可以开发了~

**Comment by yeyuexia** [comment]
API: /mri/system/date
response body:
{"timestamp":1512995350.8567240238}

**Comment by NiuShy** [comment]
@yeyuexia  时间的接口需要配置跨域 支持OPTION 方式

**Comment by NiuShy** [comment]
@fushang318  @yeyuexia 
我这边用server_url 调的几个接口都有这种情况
另 这几个接口head里面需要增加模拟用户的 userid吗？
我看之前发送事件的接口有

**Comment by fushang318** [comment]
@NiuShy 
1. 发送事件的是对应用户的操作所有需要传递 userid，并且发送事件的接口应该解决过跨域问题
2. @yeyuexia 你这次新增的这几个接口都需要支持跨域，你改一下，SIZE咱们最后调整

**Comment by yeyuexia** [comment]
@NiuShy 好的

**Comment by yeyuexia** [comment]
@fushang318 跨域问题我没法自测啊……怎么办……

**Comment by fushang318** [comment]
@yeyuexia 
跨域代码看起来没问题，应该可以用，等 @NiuShy 测试看看
