### ISSUE TITLE
【需求】在社区中能回复内容链接

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#390]
在社区的留言可以回复：
### 1、关联公众号上的文章；
![image](https://user-images.githubusercontent.com/16983441/41634945-a70115c0-7478-11e8-9a9d-e1b82a257f2e.png)
小程序刚刚支持

### 2、其他病友的健康日记
![image](https://user-images.githubusercontent.com/16983441/41635024-0aa550a0-7479-11e8-9520-e707a4ee6acb.png)

### 3、和健康成就
![image](https://user-images.githubusercontent.com/16983441/41635094-706daf72-7479-11e8-8ce9-a72b8edacfc6.png)

@akakenle 6月20日前给出意见
@ben7th @ax003d @fushang318 知晓，产品确定后另给出开发的deadline时间。

**Comment by akakenle** [comment]
这个功能我先放到需求池，放到下个版本中做
