### ISSUE TITLE
icp的github实现

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#4]
在github之上实现icp的管理流程

**Comment by ben7th** [comment]
@georgeliuyu 实现步骤：

1. 使用 codetree 整理标签
2. 规范里程碑的建立，日期指定，延期等方式
3. 规范基于 ICP 和 size 标签的工作量计量

**Comment by georgeliuyu** [comment]
@ben7th 我在想是不是有一些简单的开源的工具能直接用，或者加入到他们的开源项目中去丰富它，或者我们启动建立一个开源的項目。

**Comment by ben7th** [comment]
已经实现，关闭
