### ISSUE TITLE
mri-mri 实现一个删除bunch 的HTTP API

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/public#40]
这个HTTP API只会用于 MRI仿真器

指定 bunch uri ，找到并删除它

post /mri/delete_bunchpool
```
REQUEST
    HEADERS
        Content-Type:application/json
    BODY
            {
              "uri": "mri.func.xxx"
            }
```

**Comment by yeyuexia** [comment]
建议用restful格式， 改成 /mri/bunches/{uri} delete

**Comment by yeyuexia** [comment]
/mri/后面再加个system吧 方便统一管理

**Comment by fushang318** [comment]
@yeyuexia 好

记得 @ 我，不然看不到通知

**Comment by fushang318** [comment]
@yeyuexia 这个的PR我看到了，已经帮你关联了ISSUE和PR，下次注意关联
我已经 review 完了你的PR，我在看看 @georgeliuyu 是否 reivew 完了
如果全部review 完，我会通知你

**Comment by fushang318** [comment]
@yeyuexia 
你再 https://github.com/sibbay-ai/public/issues/22 提交的size 是这两个issue 一共的吧，为了方便统计，我把 0.5 拆分到这两个ISSUE吧

**Comment by yeyuexia** [comment]
API
/mri/system/bunches/{uri} DELETE  delete target bunch
