### ISSUE TITLE
【公告】关于用户意见反馈渠道的建立

### ISSUE THREAD

**Issue by zhaobinglong** [sibbay-ai/public#406]
用户反馈仓库已经建立，该仓库将用来专门发布用户反馈的各种问题，包括但不限于：bug，设计，新想法

1. 所有小白用户（普通用户，医学专家，医生，运营，开发者），都可以在[feedback](https://github.com/sibbay-ai/feedback)仓库中反馈使用中发现的问题
2. 该仓库将由前端开发者定期巡视，并且为每个issue添加适当的标签

该仓库目前由@zhaobinglong负责巡视。请各位同学知晓@gwind @ben7th @fushang318 @ax003d @sinchb  @georgeliuyu 

[去发布一个？](https://github.com/sibbay-ai/feedback/issues/new)

**Comment by ben7th** [comment]
@akakenle @alisahuxu @bqx619 @choufeng @fangrongxaing @fazhen @lixinxuan @lvhongqiang @maohuaming @Mengjianhua-c @NiuShy @pimgeek @shero3 @skytian1 @yeyuexia @Yidadaa @zhanhh187 

补充 at，望各位周知

**Comment by ben7th** [comment]
@zhaobinglong 主要还是提 BUG，因为这里的 issue 需要保证快速处理和发版

**Comment by alisahuxu** [comment]
收到




| |
alisa
邮箱：alisa_huxu@126.com
|

Signature is customized by Netease Mail Master

在2018年07月02日 21:57，ben7th 写道：

@akakenle@alisahuxu@bqx619@choufeng@fangrongxaing@fazhen@lixinxuan@lvhongqiang@maohuaming@Mengjianhua-c@NiuShy@pimgeek@shero3@skytian1@yeyuexia@Yidadaa@zhanhh187

补充 at，望各位周知

**Comment by fushang318** [comment]
收到
