### ISSUE TITLE
熟悉 ms-view前端项目

### ISSUE THREAD

**Issue by NiuShy** [sibbay-ai/public#41]
1. 熟悉现有ms-view代码和业务
2. 对现有项目的理解和想法
3. 提交物：一篇文档

SIZE：1

@fushang318

**Comment by NiuShy** [comment]
@fushang318  申请开发 Size:1 Deadline: 2017/12/09

**Comment by fushang318** [comment]
@NiuShy 好的，已经标记为正在进行中了

**Comment by NiuShy** [comment]
@fushang318  https://shimo.im/doc/yJ57ufOr1FQKZnzc?r=4QNY92

**Comment by fushang318** [comment]
@NiuShy 收到

**Comment by fushang318** [comment]
@NiuShy 你的文档已经review 完了，提出的问题都不错，后续可以根据项目进度安排的实际情况逐渐完善改进你提出的几个问题
我建议：
1. 你可以继续关注这些问题  
2. 逐渐熟悉现在的后台管理开发计划安排和其他功能  
3 在充分了解1，2后，在合适的时机细化成ICP ISSUE进行

**Comment by fushang318** [comment]
已完成
@NiuShy 已经从整体上熟悉了 ms-view 的代码，对于现阶段后续的开发工作已经够用了
SIZE: 1
