### ISSUE TITLE
小白健康T恤尺寸及地址统计

### ISSUE THREAD

**Issue by shero3** [sibbay-ai/public#413]
小白健康的T恤在小嵘和厂家方的多次沟通优化下，马上就要进入制作阶段，所以需要开始进行尺寸以及地址的统计

此次T恤的发放范围为小白健康的贡献者，请各位在2018-7-15日之前在此issue中回复衣服的尺码，我这边会根据各位回复的尺码最后确定各尺码的制作数量，15日之后回复的贡献者可能不一定能给到想要的尺码，敬请谅解！

地址、姓名、电话各位可以微信私信我，各位committer烦请提醒一下各自的contribute，尽快完成这项工作，谢谢！

@sibbay-ai/all 

![_20180712090129](https://user-images.githubusercontent.com/32825620/42607151-0e60b076-85b4-11e8-97e7-d43c06b35c30.png)

![071211033295_06 1 _1](https://user-images.githubusercontent.com/32825620/42610323-9a5079a4-85c3-11e8-85b4-ba365e0afe2e.Jpeg)

**Comment by alisahuxu** [comment]
M

**Comment by zhaobinglong** [comment]
XL

**Comment by fazhen** [comment]
M

**Comment by fushang318** [comment]
XL

**Comment by pimgeek** [comment]
XL

**Comment by bqx619** [comment]
2XL

**Comment by lixinxuan** [comment]
M

**Comment by choufeng** [comment]
3XL

**Comment by choufeng** [comment]
3XL

**Comment by sinchb** [comment]
L

**Comment by maohuaming** [comment]
3XL

**Comment by ax003d** [comment]
M
我们这高个儿这么多！

**Comment by fushang318** [comment]
@ax003d 和个子没关系，主要是胖

**Comment by yeyuexia** [comment]
L

**Comment by ben7th** [comment]
XL

**Comment by akakenle** [comment]
s

**Comment by zhanhh187** [comment]
L
