### ISSUE TITLE
icp认证

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#420]
请安排 @jinniudashu 进行icp的认证。
@fushang318  @shero3

**Comment by fushang318** [comment]
@jinniudashu 
有几个问题初步沟通一下，让我有个基本了解，方便后续安排，请回答几个问题吧
- 你是否熟悉 github ？
- 你是否熟悉 git ?
- 你是否会通过网页 提交代码到 github ？
- 你是否会通过 git 命令行提交代码到 github ？
- 你是否会发 PR 等其他 GitHub 基本操作？
- 你的专业是？后续主要参与哪方面的专业贡献？比如，后端开发，产品设计，区块链模型设计等

**Comment by jinniudashu** [comment]
@fushang318 
你是否熟悉 github ？——不熟悉
你是否熟悉 git ?——不熟悉
你是否会通过网页 提交代码到 github ？——需要1天时间学习
你是否会通过 git 命令行提交代码到 github ？——可以教我几个常用命令
你是否会发 PR 等其他 GitHub 基本操作？——需要1天时间学习
你的专业是？后续主要参与哪方面的专业贡献？——多年前写过编码，最近在学JS和小程序。后续主要参与业务设计、产品设计、区块链模型设计方面的工作

**Comment by fushang318** [comment]
@jinniudashu 好的，我了解了  
你只需要先熟悉通过网页操作 GitHub 能够完成 ICP 流程即可，GIT 和命令行可以视情况了解  
我安排相关人进行 ICP 认证

**Comment by fushang318** [comment]
@maohuaming 你看看大概情况，对 @jinniudashu 进行一下 ICP 认证可以吗

**Comment by maohuaming** [comment]
@fushang318 可以。

**Comment by maohuaming** [comment]
@jinniudashu 明天（周四）有空吗？

**Comment by jinniudashu** [comment]
@maohuaming 可以，具体时间你定

**Comment by maohuaming** [comment]
@jinniudashu 可否提供一下您的QQ号或者微信号？

**Comment by jinniudashu** [comment]
@maohuaming 微信号jinniudashu

**Comment by shero3** [comment]
@maohuaming 请完成ICP认证后告知我，麻烦到时候一并将微信推送给我，谢谢

**Comment by maohuaming** [comment]
@shero3 收到。

**Comment by maohuaming** [comment]
@shero3 jinniudashu的ICP流程认证已通过。
