### ISSUE TITLE
众合社区月报

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#421]
每个月icp流程的统计结果汇总和分析，主要工作内容（以周目标为依据），建议出一份月报，发布在公众号和贡献者社群中。本月开始
@fushang318 负责
@ben7th @ax003d @sinchb 配合

**Comment by ben7th** [comment]
建议可包含以下内容：

- 当月 CI 统计
- 当月 EI 统计
- 当月各个贡献者工作简短概要
- 当月版本更新情况（changelog）
- 重要反馈的处理进度
- 对当月整体工作的简评

可能的一个参考：微信小程序的每周公告：
https://developers.weixin.qq.com/blogdetail?action=get_post_info&docid=00066e3cc88928ed2f178bec256001&token=1049821297&lang=zh_CN&devtools=1

具体哪天发，包括哪些内容，各个内容做到什么程序， @fushang318 来确定
可由我和其他人来配合

**Comment by fushang318** [comment]
大体框架
```
大家好，小白众合社区 7月月报来啦！欢迎大家了解小白众合社区最新工作进展~



# 当月版本更新情况

TODO1 小程序的版本更新情况



#  重要反馈的处理进度

 TODO2 feedback 中 P0 的处理总结



# 当月贡献者 CI EI 和工作简短概要

TODO3 CI EI 表格

TODO4 所有贡献者的工作简短概要



#  对当月整体工作的简评

TODO5 



# 加入小白众合社区

TODO6 用比较简短的方式，介绍并吸引大家加入小白众合社区

更多详细内容请看：https://github.com/sibbay-ai/public

```

共有 6 部分内容需要填充

**Comment by fushang318** [comment]
TODO2 由  @zhaobinglong 完成

**Comment by ben7th** [comment]
## 当月版本更新情况

从 2018-06-20 到 2018-07-20
共发布 1.6.5 到 1.7.6 共计 7 个小程序版本，其中，最主要的更新内容如下：

- 已经能够支持与第三方线下机构的二维码合作推广了；
- 已经可以直接在用药，治疗，疾病，症状中使用自定义医学信息类型，而不用等待申请通过了；
- 优化了记录存档图片上传和最新动态中图片展示的体验；
- 优化了健康日记页面的加载速度；

所有更新还包含 60 余项 BUG 修改和优化，具体见：
https://github.com/sibbay-ai/lt-miniapp-wepy/releases

**Comment by ben7th** [comment]
## 对当月整体工作的简评

从 2018-06-20 到 2018-07-20

小白开发社区围绕合作推广进行了一系列工作，目前用户已经可以在部分线下合作机构通过扫描二维码开始使用小白健康，并引入健康记录专家的监督；

在健康记录专家的团队建设方面，小白正持续进行探索，陆续规范与优化健康记录专家的工作方法，评价体系，奖励制度；建立了每周例会和“周明星”评选制度；

在应用产品方面，通过“夏日风暴”计划，上线了 1.7 版本小程序；接下来，小白会在 UI 视觉设计规范化，记录体验简化方面开展工作，需要进行许多细致的产品梳理和文档工作；

在用户反馈方面，已经建立了专门单独处理的 feedback 通道，并正在逐步改进反馈处理的效率与质量；

**Comment by fushang318** [comment]
@georgeliuyu @ben7th @zhaobinglong @sinchb 
白健康众合社区 2018年7月份月报
https://github.com/sibbay-ai/public/wiki/%E5%B0%8F%E7%99%BD%E5%81%A5%E5%BA%B7%E4%BC%97%E5%90%88%E7%A4%BE%E5%8C%BA%E6%9C%88%E6%8A%A5-201807

公众号我还是觉得需要单独申请一个比较合适，或者暂时使用以后，以后社区庞大的时候在分开？
你们给个意见
