### ISSUE TITLE
mri-mri：实现一个m-lang api 可以用在MRI仿真器中输出日志

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/public#43]
命令如下：
```
$SANDBOX_LOG("log_message")
```

需求是
1. 在 bunch 中可以使用这个命令输出日志
2. 这个日志会通过一个 HTTP API 被前端读取到，用于辅助MRI仿真器的调试
3. 这些日志只会在MRI仿真器环境有效，线上环境会被忽略

应该需要用到redis 来中转日志    

有对这个需求感兴趣的，请按照ICP流程申请 [申请方式](https://github.com/sibbay-ai/public/blob/master/ICP%20%E5%A5%96%E5%8A%B1%E6%9C%BA%E5%88%B6.md#4申请与确认)

**Comment by ben7th** [comment]
已实现，关闭

**Comment by fushang318** [comment]
按照新的规划安排这个事情
