### ISSUE TITLE
关于贡献者分级奖励制度征求意见

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#430]
从小白发展的历程和经验来看，全身心投入的贡献者对小白的发展起到了核心作用，为推动社区的发展，鼓励和吸引更多的贡献者能以全职或半全职的方式投入进来，让更多的同学成为小白社区的中坚力量，同时考虑到全职和兼职同学所承担的风险不同，社区应该有一套完善的建立机制来平衡这种风险。同时鉴于小白的token发行在即，正好是建立全新奖励制度的时机，现就以下问题征求社区的意见：
1、你认为应该分为几种？请说明  （A、B、C...）
2、定义和区分有哪些指标？
3、综合（响应速度、进度保障、协作等等一切可能的因素）来看如果纯兼职是单位贡献是1，那么全职的单位贡献是多少？（在技术水平相同）
4、所有你认为还要要考虑因素？
5、在社区基于“尊重和信任”的原则下，分级是否可以采用承诺制？（就是贡献者自己承诺）

本issue的deadline时间是：8月8日
请在下面留言

@public/all

**Comment by fushang318** [comment]
### 如果是作为主要的劳动输出的工作的话

在如下因素对等的情况下
1. 职业能力相同
2. 做事态度相同

全职和兼职是有太大的区别的，用这个两个词可能不合适，可以叫做：个人工作精力 80% 在这个项目 和 个人精力 20% 在这个项目

区别主要体现在
1. 做事推进效率
2. 响应速度、进度保障、协作等等一切可能的因素
3. 产出的质量稳定性上

> 哪有什么岁月静好，不过是有人替你负重前行


### 如果是作为方案，计划，调研等工作的话

在如下因素对等的情况下
1. 对小白项目了解程度

兼职和全职没有太大区别，就看谁的经验丰富了，经验丰富的人一个小时的产出，比其他人搞好几天还有用，甚至经验不丰富的情况下，有可能做出很错误的产出

**Comment by kimgrace6** [comment]
1.个人建议贡献者分为.A全职B兼职（半特别容易产生歧义）;
2.关于定义与区分，建议全职者，水准一步到位确保社区核心level，能力、响应速度、进度保障作为刚性指标，提高准入门槛，确保杜绝打酱油者;兼职者，只要遵守社区贡献者守则即可，不触碰社区规则红线的，就可松散合作，待社区后期完善后，逐步提升准入要求，筛选更优秀的兼职者;
3.水平相同的前提下，兼职贡献1，全职贡献不少于3比较公平;
4.尽快完善社区贡献者守则;
5.初期建议考核+承诺相结合比较可行！

**Comment by kimgrace6** [comment]
1.个人建议贡献者分为.A全职B兼职（半特别容易产生歧义）;
2.关于定义与区分，建议全职者，水准一步到位确保社区核心level，能力、响应速度、进度保障作为刚性指标，提高准入门槛，确保杜绝打酱油者;兼职者，只要遵守社区贡献者守则即可，不触碰社区规则红线的，就可松散合作，待社区后期完善后，逐步提升准入要求，筛选更优秀的兼职者;
3.水平相同的前提下，兼职贡献1，全职贡献不少于3比较公平;
4.尽快完善社区贡献者守则;
5.初期建议考核+承诺相结合比较可行！

**Comment by pimgeek** [comment]
上面几位大多是从 “通用” 的协作原则去分析的。换句话说，即使大家没在做 **“健康数据记录”** 服务，也有一定的参考价值。

我来补充一个 **4. 考虑因素**，从 “青色组织” 的特点出发考虑。 

上个月抽时间看了《重塑组织》的一些章节，感觉青色组织要想很流畅地转起来，可能还是要多从目标用户、目标客户、部件合格率等角度思考工作价值，（比如在博组客，护士们能够更人性化地关照病患；在FAVI 公司，生产者们对出现故障的汽车零部件高度重视等）。

有时候，人们没对做特别明确的承诺，但还是在坚持做事。比如医生内心要求自己尽量认真回答每位挂号问诊者的问题，那么他们如果负责与小白回答健康日记的用户进行互动，应该也会非常负责。但如果仅仅为了遵守通用的规则而做事，没能进入相关的工作角色，新鲜感过去后，就容易变得疲沓、忘事、甚至拖欠工作。 :sleepy:

所以，如果遇到响应不及时或拖欠工作的情况，一方面要想办法减少任务延期风险，另一方面也要密切结合健康数据记录的业务细节去做沟通，让贡献者清晰地意识到自己的工作在 “服务小白用户” 的过程中扮演的角色。 :smile:

**Comment by sinchb** [comment]
区别全职、非全职，不如评价其参与的深度和长度
* 深度：对某个较小事情，有很深入的研究和参与，往往比新同学有更深的业务背景和洞察力。
* 长度：需要考虑，30天 * 1个月的贡献者 和 5天 * 6个月的持续贡献者哪个对小白有更大的价值。

> 你认为应该分为几种？请说明 （A、B、C...）

基于以上两个方面，我建议
1、参考之前我们讨论郑和柳事件而总结出的结论，分为
* 深度贡献者
* 非深度贡献者
两种。对于深度贡献者，除了参考起贡献频率，也要参考其贡献持续时间。以便为贡献者提供丰富多样的参与形式。
附 [深度参与者管理制度(PR)](https://github.com/sibbay-ai/public/pull/394)

> 3、综合（响应速度、进度保障、协作等等一切可能的因素）来看如果纯兼职是单位贡献是1，那么全职的单位贡献是多少？（在技术水平相同）

对于两者贡献单位，不建议做区分，以size来评价贡献价值（奖励）本身经不起实践。10个人贡献了10个size，和1个人连续贡献了10个size，我可能更倾向去前者。
评价和奖励一个贡献者，并使其能长期参与贡献，而且能使其在小白内无论以何种方式参与，参与时间多少，都能得到相应的尊重和鼓励，是更加值得思考的问题。


> 5、在社区基于“尊重和信任”的原则下，分级是否可以采用承诺制？（就是贡献者自己承诺）

不建议采用承诺制。在奖励模型下，如果采用承诺制，贡献者可能倾向于不作承诺，或承诺的内容充满水分（比如review一个简短pr，我可以承诺在未来一个月内完成）。这种承诺不仅没有意义，而且对于项目进度有害。
所以我更加建议采用集体决策，制定出参与者认可的、可操作范围内的目标。

**Comment by georgeliuyu** [comment]
@sinchb 增加一下解释：承诺制的意思是贡献者自己承诺那个level的方式参与，那么社区就按照那个level进行奖励，这里要有一个严厉的处罚方式。

**Comment by sinchb** [comment]
@georgeliuyu 明白了~
