### ISSUE TITLE
会议机制改进（包括早会、周会）

### ISSUE THREAD

**Issue by ax003d** [sibbay-ai/public#432]
为了提高会议效率，并且鼓励贡献者积极参与重要会议，提出几点会议改进建议：

1. 每次会议都需要有主持人事先开好 issue，并指定何时、何人参与（@ 相关人员），主题是什么，与会人员在会议之前可以在 issue 中补充要讨论的议题
2. 会议开始后，由主持人按议题顺序主持会议的进行
3. 会议结束后，主持人需要提交一份会议纪要，对于需要继续推动的事情，@ 相关人员。会议纪要需要在 cooperation-issue 仓库中创建文件，并提交 PR，作为提交物
4. 根据实际花费时间，主持人获得双倍 size；被 @ 的参与人员，且在会议中有发言的（以会议纪要记录为准），获得 size 奖励；其他未发言参与人员或者旁听人员，没有 size 奖励。

**Comment by fushang318** [comment]
@sinchb @ben7th

**Comment by ax003d** [comment]
@sibbay-ai/all

**Comment by fushang318** [comment]
**最近早立会和周会确实太长了，需要考虑如何缩短**
周会要控制在一个小时内
早立会周一控制在一个小时内，周二到周五控制在半个小时内 


### 早会和周例会
目前主持人就是宋亮或者我，暂时作为 commiter 的义务吧   
如果有SIZE奖励，只会助长无效率会议，不建议这么做  
逐渐调整要沟通的事情内容长短就可以了，比如这次确定以后不再早立会沟通QA的内容  
可以每个人自己折算到后续推进的提交物中 ，在自己的ISSUE中注明即可



### 其他专题立会  
1. 可以有记录和PR
2. 主持人可以做会议纪要和后续推进安排，获得奖励
3. 其他参会人的奖励建议如果有后续推进的，折算到后续推进的提交物
4. 没有后续推进只是一个交接的话，直接获得奖励
5. 即没有起到推进沟通作用，又没有后续提交物的，不获得奖励

尺度可以由主持人来把握，试行一段时间

**Comment by ben7th** [comment]
基本同意 @ax003d 和 @fushang318 的观点，补充意见：

1. 会议纪要可以有奖励，但会议纪要不宜过细。（有的公司开会做会议纪要把每一句话都记了，没有必要）
2. 早会主要处理技术协调，考虑只设置一个计划与执行协调环节，去掉目前的 QA 浏览环节；（QA 分流通过另外的流程处理和保证响应）
3. 周会主要处理总体协调（产品，运营，商务，社区建设，等），考虑设置一个计划与执行协调环节，和一个议案环节
4. 奖励机制要尽可能简化，不宜过细，否则看起来很好但很难执行；另外，固定时间例会，我倾向于对全勤参与或者连续参与给出奖励，而不对单次参与给出奖励。

**Comment by ben7th** [comment]
已加入周三例会讨论议题

**Comment by ax003d** [comment]
@ben7th 
1. 会议纪要不需要记录每一句话，只需要记录本次讨论了哪些议题，各个参会者的主要观点，最终结论或者下一步动作即可
2. 补充一点，每次会议奖励 size 上限为 0.2（主持人为 0.2 * 2 = 0.4）

**Comment by sinchb** [comment]
我觉得，任何一个会议都应该有其目的和结论，这点我赞同 @ax003d 的看法。

目前对于我们来说，主要其实是缩短会议时间。会议有两种
* 一个是低频、时间长、与会人数多的会议
* 另一种是高频、时间短、与会人数少的会议。比如专门的项目讨论，在线沟通同步解决问题。这一类其实可以将花费的时间计算到自己对应的issue或者pr中。

我们可以将会议分类，减少第一种会议，增加第二种会议。第二种会议记录size到对应要做的issue中。
第一种会议（比如例会，主要讨论发展方向、社区建设、产品变更等），暂时没有想到好的办法。可以再周会的时候讨论。

另外不需要向所有人同步或者讨论的事，可以通过issue中@的方式进行沟通。

现在的会议，有时候确实比较多，一个早会 1 小时，一个例会2小时，那么最多占用了一天工作时间的 3/8，将近 40%。

@ax003d @ben7th @fushang318

**Comment by ben7th** [comment]
提案已通过，此 issue 关闭
