### ISSUE TITLE
贡献者实名社交网络建立

### ISSUE THREAD

**Issue by ax003d** [sibbay-ai/public#433]
为了增强小白健康贡献者之间的沟通和交流，希望建立一个贡献者实名社交网络。
在该网络上，需要贡献者提供如下信息：
- 真实姓名
- 所在城市，偶尔可以线下交流
- github，基于 ICP 体系下 @ 的需要
- 微信，方便必要时的沟通
- 在小白中负责的事情
- 个人专长

具体的方案可以有：
1. 使用 facebook 的小组功能，缺点是需要翻墙
2. 使用开源的社交产品，自己搭建
3. 自己开发

**Comment by ax003d** [comment]
@sibbay-ai/all

**Comment by sinchb** [comment]
telegram也不错

**Comment by ax003d** [comment]
@sinchb telegram 只是一个 IM 吧，感觉和微信没有太大区别，没有类似一个论坛的功能。

**Comment by fushang318** [comment]
嗯，核心要解决的是希望大家彼此更了解，这个不容易，但是很有必要..
微信企业版有啥功能，是否可用？

**Comment by ax003d** [comment]
@fushang318 企业微信我感觉还不如钉钉好用。

**Comment by ben7th** [comment]
这个可以作为开发者社区建设专项的一项工作来推进

论坛部分，由于 github 本身已经具有非常强的论坛属性，为了避免重复，可以开一个灌水用 repo，再使用 https://github.com/imsun/gitment 这样的工具整合到别的网页里

**Comment by ben7th** [comment]
已加入周三例会议题

**Comment by ax003d** [comment]
我说说目前存在的问题：
1. 小白社区贡献者众多， 参与时间长短不一，经常开会的时候会不知道谁是谁，在小白中是做哪方面的，对于新加入的贡献者来说，更是如此
2. 参与小白做贡献的大多数人，我觉得在各方面都挺有经验，有自己的专长，如果大家彼此更加了解，可以在自己擅长的领域相互交流吧，也许小白之外的事情，大家也能找到沟通对象
3. 目前的小白社区有点冰冷，大家看到各自只是一个个的网名和各种风格的头像，在我看来有点像是一个匿名社区
4. 微信、钉钉、企业微信都是 IM 工具，大家好像没有这种习惯在上面自我介绍吧，另外，也不方便后面参与的贡献者查看

**Comment by fushang318** [comment]
工作方便，我觉得画个图来说明目前的人员构成比较合适，谁来画一个？

**Comment by sinchb** [comment]
@fushang318 正好我想了解下都有哪些同学，都在做啥，已经有什么有趣的背景和经历，我来吧

**Comment by fushang318** [comment]
@sinchb 好

**Comment by pimgeek** [comment]
你们在哪里画图呢？是手绘的图，还是在线的图？我曾经在 ProcessOn 上面绘制过类似的图。
