### ISSUE TITLE
申请阿里云及相应仓库权限

### ISSUE THREAD

**Issue by bqx619** [sibbay-ai/public#435]
来源: https://github.com/sibbay-ai/cooperation-issues/issues/1041

请求:

- 开通 DataWork 权限 (似乎是单独的控制台)
- 相应放置脚本仓库

@fushang318

**Comment by fushang318** [comment]
@bqx619 我以前操作过，破繁琐，需要同步进行，立会后找我

**Comment by fushang318** [comment]
开通了  https://github.com/sibbay-ai/data-maxcompute-stat 权限

**Comment by fushang318** [comment]
开通了 DataWork 权限

**Comment by fushang318** [comment]
已经开通 jenkins 账号
