### ISSUE TITLE
医疗社区icp认证

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/public#436]
经过培训，金老师已经了解icp标准流程，并可以独立建立issue和pr，认证通过。
https://github.com/sibbay-ai/medical/issues/140
https://github.com/sibbay-ai/medical/issues/142
1.请@fushang318开通金老师在medical中的权限
**用户名kimgrace6
注册邮箱：416188196@qq.com**
如需其他补充资料，可直接  @kimgrace6 金老师
2.为方便医疗社区工作，我申请成为该社区的管理者，请开通相关权限； @fushang318 @georgeliuyu 
3.后续人事相关工作，请 @shero3 跟进

**Comment by fushang318** [comment]
@fazhen 

已经邀请 kimgrace6  进组 ，需要主动访问 https://github.com/sibbay-ai 进入

**Comment by fazhen** [comment]
经多次讲解，黄爱欣已经了解icp标准流程，并可以独立建立issue及pr，认证通过
1.请 @fushang318 开通其在medical中的权限
用户名：aixinhuang
注册邮箱：374872852@qq.com
 @aixinhuang
2.后续人事相关工作，请 @shero3跟进

**Comment by fushang318** [comment]
@fazhen 已经邀请进入 https://github.com/sibbay-ai

**Comment by shero3** [comment]
@fazhen 请将相关通过ICP认证的人员微信推送给我，谢谢
