### ISSUE TITLE
关于 @fazhen 申请成为 医疗社区工作的管理者如何处理

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/public#437]
@fazhen 在 https://github.com/sibbay-ai/public/issues/436 中提到
```
为方便医疗社区工作，我申请成为该社区的管理者，请开通相关权限
```

目的是管理医疗社区工作，包括协调相关人推进工作和 管理 ICP ISSUE 打标签 merge 等

这个如何处理，@ben7th @sinchb @georgeliuyu

**Comment by ben7th** [comment]
通常来说，管理 ICP merge 属于 committer 工作范畴
关于如何产生 committer ，具体制度如何订，建议在周日周会上提出，并由 @ben7th @fushang318 @sinchb 另行找时间讨论（周会上安排讨论时间）

针对 #436 @fazhen 具体需要的权限需要更明确一些

**Comment by fazhen** [comment]
首先我想先确认一件事情：是否只有committer打上标签和指定assignees才可以被合理统计工作量？ @fushang318 

我这里所指的“相关权限”，其实就是指能够打标签和指定assignees的权限。 @ben7th

**Comment by fushang318** [comment]
@fazhen 
目前的逻辑是这样的：只有committer打上标签和指定assignees才可以被合理统计工作量

**Comment by fushang318** [comment]
@ben7th
