### ISSUE TITLE
针对周会议题 “会议机制改进” 进行投票

### ISSUE THREAD

**Issue by ben7th** [sibbay-ai/public#438]
提案来源：
https://github.com/sibbay-ai/public/issues/432

在此周会上进行过讨论：
https://github.com/sibbay-ai/cooperation-issues/issues/1029

周会形成的推进意见：
- 简化早会和周会的环节，早会只保留开发沟通协调环节，时间控制在 30 分钟；周会保留专项沟通协调环节和提案讨论环节，时间控制在 60 分钟；
   通过明确流程减少平时的冗余沟通，减少集中会议协调的内容，由 @ben7th 推进
- 尝试提出引入其他沟通工具，由 @jinniudashu 另行提出提案
- 对每次早会与周会进行会议纪要记录，对每次周会进行参会人记录，先仅记录，不对记录结果进行评判（但会作为将来设计评判规则的参考依据），由 @ben7th 推进

committer @sinchb @ben7th @fushang318 对上述提案进行投票表决，结果将记录在

提案汇总链接：
https://github.com/sibbay-ai/cooperation-issues/wiki/proposals-list

**Comment by fushang318** [comment]
同意

**Comment by sinchb** [comment]
同意

**Comment by ben7th** [comment]
同意

**Comment by ben7th** [comment]
议题投票结果，通过
结论记入：
https://github.com/sibbay-ai/cooperation-issues/wiki/proposals-list
