### ISSUE TITLE
从微信公众号启动

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#44]
目的：
让小程序成为公众号的一个功能模块
要求：
1、从任何第三方的微信公众号，能点击进入小程序；（是否绑定和非绑定有区别）
2、公众号拥有者能配置参数并传递给小程序；
是否还有其他方面的要求。

**Comment by ben7th** [comment]
### 从公众号关联小程序

只有从公众号关联了小程序，才能从公众号跳转到小程序，步骤如下：

1. 公众号拿到小程序的 appid, 通过公众号后台管理界面 `小程序管理 > 添加 > 关联小程序`发起关联请求。需要公众号管理员扫二维码并填写目标小程序的 appid
   ![image](https://user-images.githubusercontent.com/322486/33756159-276cf2a2-dc2f-11e7-88f7-357c65314a05.png)
   填写 appid 并发送关联邀请。

2. 小程序管理员收到关联邀请，并确认通过。

3. 关联完成后，公众号这边可以看到：
   ![image](https://user-images.githubusercontent.com/322486/33756200-562fdc4e-dc2f-11e7-96c7-247a297ff920.png)
   小程序这边可以看到：
   ![image](https://user-images.githubusercontent.com/322486/33756234-7d971504-dc2f-11e7-9483-fea33039f5cd.png)

**以上设置是通过公众号进入指定小程序的前提**
（楼下继续回复）

**Comment by ben7th** [comment]
### 从公众号进入小程序，方式一，关于界面进入

当上述关联完成后，访问公众号的关于界面，将看到以下内容：

![](https://gitlab.com/sibbay/lt/miniapp/uploads/1398123525c8eb1a617dcefe38c84d91/image.png)

点击小程序图标，可以进入小程序。当以这种方式进入小程序时，相关限制如下：

- 不能指定进入哪一页，只能进入首页
- 小程序可以获得用户是从什么公众号进入的（能获得公众号的 appid 作为参数），并据此做额外处理
- 除此之外，不能传特定参数

**Comment by georgeliuyu** [comment]
了解 @ben7th

**Comment by ben7th** [comment]
### 从公众号进入小程序，方式二，从公众号内的消息进入

公众号访问 `素材管理 > 新建图文素材` 时，可以在要创建的素材类型中，选择小程序：

![image](https://user-images.githubusercontent.com/322486/33756471-a70e17e2-dc30-11e7-9af7-10bc29d59034.png)

指定要跳到哪个小程序：

![image](https://user-images.githubusercontent.com/322486/33756508-ccbba27a-dc30-11e7-8b89-e2293fca8ad7.png)

设置如下：

![image](https://user-images.githubusercontent.com/322486/33756523-e0c8263a-dc30-11e7-89c0-56e25d974049.png)

支持三种形式：
文字，图片，小程序卡片

限制如下：
- 可以指定进入哪一页
- 小程序可以获得用户是从什么公众号进入的（能获得公众号的 appid 作为参数），并据此做额外处理
- 除此之外，不能传特定参数

**Comment by ben7th** [comment]
### 方式二的发布效果

![](https://user-images.githubusercontent.com/322486/33756883-76b0a78e-dc32-11e7-8030-bafdcd6d4a1a.png)

上面的三种形式，都可以嵌到公众号发布的文章里。

用户的体验：进入文章  > 通过文章内容打开小程序

注意：无法直接在公众号文章同一级发布一个直接打开小程序的链接。只能嵌在文章里面。

**Comment by ben7th** [comment]
@georgeliuyu 目前就是上面这两种方式了

**Comment by georgeliuyu** [comment]
@ben7th ok，很详细。：+1：
