### ISSUE TITLE
关于增进社区沟通的提案

### ISSUE THREAD

**Issue by jinniudashu** [sibbay-ai/public#449]
加入小白社区近1个月，感受了社区氛围和工作机制，觉得有三点可以改进：
1、成员需要增进日常互动，包括工作性质和非工作性质的；
2、尽量在日常完成具体工作任务的动态交流和进度呈现，把例会时间留给社区建设话题；
3、后续会有越来越多非开发人员加入社区，要为他们提供交流和任务管理平台。

提请讨论以上需求，如认为需要改进，我愿意负责推动改进工作

@sibbay-ai/all

**Comment by pimgeek** [comment]
非常赞同，希望有一些日常群讨论：比如“小白团队”如何直接或间接地触及了大家心目中“希望服务的人群”，得到了哪些“各种参与者很都容易看懂”的反馈信息等等 😀 个人感觉不用太频繁，每周有那么一次明显的讨论热点就够了，这也是我们集智俱乐部注意力与知识管理群的实际情况 😄

**Comment by ben7th** [comment]
已加入提案清单
https://github.com/sibbay-ai/cooperation-issues/wiki/proposals-list
