### ISSUE TITLE
ICP 认证流程申请：@hnuyx

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/public#459]
### 内容

- 申请者： @hnuyx 
- 指导者(mentor)： @maohuaming 
- 人事负责人： @shero3 
- 工作类型：智能合约开发

### 步骤
- @hnuyx 和 @maohuaming  参考 [贡献者认证流程](https://github.com/sibbay-ai/public/blob/master/%E8%B4%A1%E7%8C%AE%E8%80%85%E8%AE%A4%E8%AF%81%E6%B5%81%E7%A8%8B.md) 进行贡献者认证；
- 在本 issue 上记录认证结果；
- @shero3 @fushang318 知晓结果

### 补充
后续新的奖励标准规定为 500元/size，社区会对 size 有新的完整解释，而不是单纯的工作时间

**Comment by maohuaming** [comment]
@hnuyx 请问你大概什么时间方便进行ICP认证？

**Comment by hnuyx** [comment]
看你时间吧，我这几天都有时间的 @maohuaming

**Comment by fushang318** [comment]
好的

**Comment by shero3** [comment]
@maohuaming 麻烦推一下微信给我

**Comment by maohuaming** [comment]
@shero3 微信号：henuyx
