### ISSUE TITLE
关于size定义和执行的修改说明（试行）

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#460]
为进一步推进社区的自我演进，现对size的进行如下调整：
1、取消size标准的差异，都统一为1d=500元
2、个人可自行确定8小时的薪资标准，然后折算为size（如你认为自己的能力标准是700元，那么你报size是时可以增加40%）
3、EI的评价照常；
4、重申一下，管理、协调是都是可以报size。
5、试行开始时间9月16日，试行周期3个月。

@sibbay-ai/all

**Comment by fushang318** [comment]
收到

**Comment by shero3** [comment]
收到

**Comment by sinchb** [comment]
收到

**Comment by kimgrace6** [comment]
收到
