### ISSUE TITLE
ICP认证（南希）

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/public#464]
经过培训，南希 @nancy919已经掌握ICP工作流程，认证已经通过
https://github.com/sibbay-ai/medical/issues/215

**Comment by fazhen** [comment]
请李飞开通南希的相关仓库工作权限 @fushang318 
GitHub账号：nancy919
注册邮箱：lindsay_919@icloud.com


 请AKEN @akakenle 明确给南希开通哪些仓库权限

**Comment by fazhen** [comment]
后续人事相关工作请 @shero3 跟进，我稍后将其微信名片推送给你

**Comment by fushang318** [comment]
@fazhen
已经邀请

> You've invited nancy919 to sibbay-ai! They'll be receiving an email shortly. They can also visit https://github.com/sibbay-ai to accept the invitation.

**Comment by fazhen** [comment]
请注意查收邀请提示 ，并接受 @nancy919
