### ISSUE TITLE
@ben7th 2018-09-17 至 2018-09-24 工作时间说明

### ISSUE THREAD

**Issue by ben7th** [sibbay-ai/public#475]
由于下周本人要进行跨省搬家（从北京搬到广州）；
有不少的物品需要处理，转卖，寄存，物流运输；
办理宽带账号销号，一些银行业务；
并且要与原房东交接；

因此，接下来的一周（17 到 24 号），琐事较多，无法做到及时响应；
每天的早会会尽量参加，但白天和晚上大半时间不在电脑前；
工作方面，会处理一些之前规划的文档撰写和开发工作，一些综合协调多半不能及时进行；

望大家见谅；

**Comment by ben7th** [comment]
@georgeliuyu @fushang318 @sinchb @fazhen @zhaobinglong @bqx619 @akakenle

**Comment by bqx619** [comment]
㊗️ ㊗️ ㊗️

**Comment by fushang318** [comment]
不用的好东西，嫌弃占地方的，邮寄给我，邮费到付 (*￣︶￣)
