### ISSUE TITLE
ms: review 熟悉 ms-view前端项目的文档

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/public#48]
对 https://github.com/sibbay-ai/public/issues/41 的提交物进行 reivew

**Comment by fushang318** [comment]
review 一下 https://shimo.im/doc/yJ57ufOr1FQKZnzc?r=4QNY92   @choufeng

**Comment by NiuShy** [comment]
@fushang318  需要提供下@choufeng 的邮箱

**Comment by fushang318** [comment]
@NiuShy 我已经加了 @choufeng 的邮箱

**Comment by choufeng** [comment]
已回复 @fushang318

**Comment by fushang318** [comment]
@choufeng reivew 结束
SIZE: 0.1
