### ISSUE TITLE
需要对 Jessica124 进行 ICP 认证

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/public#483]
@Jessica124 是一位新加入的财务同学，需要进行一下 ICP 的培训和认证
需要
1. 由 @fazhen 贾老师进行一下 ICP 培训，不要 一对一进行培训，这次正好录制一下ICP培训教程吧，录制好教程以后，交给 @Jessica124 看，并进行一次答疑
2. 贾老师答疑完，没有问题后，由 @maohuaming 对 @Jessica124 进行一次ICP认证

 @shero3 知晓

**Comment by fazhen** [comment]
正在整理培训素材，明天可以给到 @Jessica124

**Comment by fushang318** [comment]
@fazhen OK

**Comment by maohuaming** [comment]
@fazhen 好的。

**Comment by maohuaming** [comment]
@fushang318 @fazhen @shero3 对Jessica124的ICP认证已完成。
