### ISSUE TITLE
广泛征集小白健康社区未来的角色称谓

### ISSUE THREAD

**Issue by ben7th** [sibbay-ai/public#485]
小白健康未来将针对健康记录和健康互助打造社区。
一个健康社区，它的社区形态，一定和我们习惯的 SNS 或微博/twitter 不同，社区里的角色和角色之间的关系，是现实中医生与患者关系的延伸。这样的社区，需要有特定的，具有自己社区文化的角色称谓；

我们希望找到这样一对儿**角色称谓**，姑且称之为 A 和 B 吧。
在这样的关系里，A 像是 B 的医生，监督者，顾问，付出关怀的家人，愿意分享经验的过来人；
未来，我们希望整个小白健康社区，由许多这样的关系组成；
每个人可以作为 A，去关怀很多的 B；也可以作为 B，被很多 A 关怀；

**我们希望给 A 和 B 找到合适的称呼，合适到大部分的人，一眼就能从这对称呼里看出这种关系，不需要我们做多余的解释，就能很快地把含义传达出去；**

我们不希望直接使用“医生” 这个称呼 —— 一来，我们在医学方面远不够专业，无法认定谁真正有资格成为医生；二来，任何人都可以对其他人（亲人，朋友，等等）有关怀，有监督；
我们也不希望直接使用“病人，患者”这个称呼 —— 并非所有人都罹患疾病，一个健康的，生活习惯良好的人在社区里分享健康记录，也应该是一件受欢迎的事情；

经过小范围的短暂讨论，我们觉得自己的想象力还不够丰富，没有想到足够好的称谓词语；
若有朋友能帮助我们拓展思维，哪怕是天马行空，有缘告诉我们，提示我们真正合适的这一对儿称呼 —— 无论是人的身份名词，动物，植物，客观事物，还是哪怕很抽象的词语，我们都表示万分感谢；

欢迎为小白健康社区提供创意 :smile:

**Comment by destinyd** [comment]
个人感觉可以从**“共栖动物”**中挑选一对比较符合小白角色形象的，作为称呼。

参考：[共栖动物_百度文库](https://wenku.baidu.com/view/dad61ec389eb172dec63b704.html)
