### ISSUE TITLE
关于icp中“熟练人员”的一个说明

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#488]
## icp规范中
![image](https://user-images.githubusercontent.com/16983441/45987935-aaf3ab00-c0a6-11e8-8f37-4344f6698141.png)

## 说明：
在这里有个“该领域熟练人员”，其含义是：
1、已经具备该领域需要掌握的工具，例如：进行音频编辑，则相关工具的熟练使用应该是基本技能，则如果不熟悉而需要学习的，则不计入size的统计。
2、已经具备该领域的基础知识，如果贡献者有不足的地方需要自己学习的，不计入size

此外，对于一些全新的内容或工具，但又是需要掌握并使用的，则贡献者可以申请开调研或者学习的icp issue专门处理。

同时重申一下icp的评价对象是”提交物“

所有icp贡献者知晓
@sibbay-ai/all

**Comment by fushang318** [comment]
收到

**Comment by fazhen** [comment]
收到

**Comment by sinchb** [comment]
收到
