### ISSUE TITLE
关于pr的commit的内容规范的决议

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#49]
在 #13 中有两种意见
1、**所有pr在merge之前，必须rebase为一个commit，并有简明扼要的备注信息** （@sinchb 提）
2、**不用把整个 pr rebase 为一个 commit**  ：
一个 pr 里包含多个 commit, 每个 commit fix 一个 issue，这种情况通常出现在批量改小 bug 的情况下
是否只做到一个 commit 对应一个 issue 即可。

这个作为一个决议
@ben7th @fushang318 @sinchb 三位committer通过表决决定，在下面的comment中明确写出自己的意见，选择1或者2：
截止时间：12月13日晚9:00
到时候已投票数为准，如果没有投票的或者投票数相同，由决议的发起者决定。

**Comment by georgeliuyu** [comment]
我不参加表决，建议加以考虑一个角度：制定的规则是否很容易明确进行判断，contributor是否能清晰地知道对错。

**Comment by ax003d** [comment]
可以考虑在代码仓库的根目录添加一个文件，PULL_REQUEST_TEMPLATE.md，用于存放模板。

**Comment by georgeliuyu** [comment]
希望通过此事，建立表决机制。

**Comment by fushang318** [comment]
我弃权

**Comment by ben7th** [comment]
我支持 2，且补充规则描述：

- pr 中可以包含多个 commit，但限制是，每个 commit 必须带有 issue 编号

```
pr
- fix #1 , 修改 xxx bug
- for #2 , 增加 xxx 功能
- fix #1 ,  再次修改 xxx bug
```

这样的 pr 结构可以被允许

**Comment by sinchb** [comment]
我支持1，原因：

1. 多个bugfix建议分多个issue，每个issue对应一个pr
2. 拆分可以方便回滚、reopen、测试
3. 可能每个bugfix的reviewer不同，那么合并在同一个pr中可能无法很好的执行ICP

@fushang318 一般没有关联issue、没有遵循commit、pr规范的，我直接 request change 了，次数多了也就记得了。

**Comment by georgeliuyu** [comment]
@fushang318 @ben7th @sinchb 
现在的情况是1.5:1.5，按照规则由 issue创建者@georgeliuyu下决定。
我建议采用方式1，原因能很明确的提出要求和识别。
结论：**采取方式1**。
进入文档的文字：**所有pr在merge之前，必须rebase为一个commit，并有简明扼要的备注信息**

**Comment by georgeliuyu** [comment]
这个作为决策的案例

**Comment by ben7th** [comment]
@georgeliuyu 收到
