### ISSUE TITLE
Jessica124 ICP培训

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/public#491]
主要工作：
针对非开发人员Jessica124 进行ICP培训。
 请观看培训视频 @Jessica124
1.https://shimo.im/docs/MABHD971H48soi8R/ 《ICP培训视频使用说明V2》
2.https://shimo.im/docs/GJLIpJYHlAUr37Jf/ 《ICP培训视频V2》

请观看培训视频后与我联系，我单独向你解答
相关issue  https://github.com/sibbay-ai/public/issues/483

**Comment by fazhen** [comment]
请留意该issue，待Jessica124培训完成后，请协助认证 @maohuaming

**Comment by maohuaming** [comment]
@fazhen 请问Jessica124的ICP培训预计什么时候可以完成?

**Comment by fazhen** [comment]
视频看完了了吗？有疑问吗？请微信与我联系@essica124

**Comment by Jessica124** [comment]
还没看完，我预计4号可以完成，谢谢@fazhen

**Comment by Jessica124** [comment]
还没看完，我预计4号可以完成，谢谢@fazhen

**Comment by Jessica124** [comment]
还没看完，我预计4号可以完成，谢谢@fazhen

**Comment by fazhen** [comment]
好的👌

**Comment by fazhen** [comment]
@Jessica124  培训已经完成，目前可独立完成issue、分支、pr的创建，并建立关联，相关疑问也已经予以解答。

请 @maohuaming 对其进行ICP认证

**Comment by fazhen** [comment]
微信推送给你名片 @maohuaming
