### ISSUE TITLE
症状同义检索

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/public#493]
现有系统症状添加仅可检索某一术语，能否添加同义词的检索功能，以方便用户添加症状。
如系统中有“小腿疼”，当用户搜索“下肢疼”时，也可以出现出现“小腿疼”。
OMAHA术语集应该可供参考。

我们最好能这两天给出一个解决方案。

@fushang318 @georgeliuyu

**Comment by fushang318** [comment]
1. 后台管理需要提供一个 给症状增加同义词的功能 ，由@fushang318 协调开发
2. 可以由医学人员给症状录入一到多个同义词，等 1 功能做好由 @fazhen 协调录入
3. 把症状同义词加入搜索索引 ，由@fushang318 协调开发

**Comment by fushang318** [comment]
@fazhen 这个事情的 deadline 是什么时候？

**Comment by fushang318** [comment]
已经完成导入 @fazhen
