### ISSUE TITLE
小白（sibbay）众和社区核心价值观的讨论

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#5]
# 小白（sibbay）是谁？
小白是一个基于“众”的形式进行建立并运行的组织。其目标是以大众的医疗健康数据造福大众。
我们希望探索一种基于有偿服务的社区组织模式。
# 社区的哲学
每个成功的社区都有其所坚持的价值观和哲学，小白的坚持：
下面罗列出所有的内容供大家参考和讨论：
## apache的核心（非官方）：

- 协作的软件开发
- 友善的商业许可
- 尊重、信任，基于技术的交互准则
- 严格的执行标准
- 强制要求安全性

## ubuntu的核心哲学：

- 体谅，考虑周全
- 尊重
- 协作
- 有不同意见时，要咨询一下其他人
- 当你不太确定时，要寻求帮助
- 当你没有时间时，请告诉大家

# 请给出你认为小白社区做必须具有的核心价值观：

**Comment by sinchb** [comment]
@sinchb

* 做一件事之前，要有思考
* 尽力，为别人铺路

**Comment by ben7th** [comment]
- 参与者随着合作的深入，需要逐渐参与高门槛工作，以印证在组织内贡献与评级的提升；
（这里的高门槛，**指的是**：需要花精力讨论需求/决策，或需要掌握过去本项目/产品积累的知识；**而不是**：需要特定领域专业知识或技能；）

思考来源：
https://github.com/sibbay-ai/public/issues/7

若总结成一句话，是否可以是：逆水行舟，不进则退

**Comment by sinchb** [comment]
@ben7th 听起来更像是 “水涨船高” 😄
