### ISSUE TITLE
广告词征集

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#501]
作为医生，你当然应该关心你的病人
作为医生，你当然应该随时了解病人的情况
作为医生，你当然应该告诉你病人应该如何记录
作为医生，你当然应该随时给出建议
作为医生，你当然应该让更多的人知道你的成功案例
作为医生，你当然应该受到尊重
作为医生，你当然应该光明正大地得到奖励

也许今天的现实还没有做到，那么小白愿意开一个头

## 你负责关心病人，小白负责奖励你

具体规范：https://shimo.im/docs/NakgqqRD9cwxLB8U 

推广对象：医生或医疗专业的群体

**Comment by alisahuxu** [comment]
申请开发 deadline: 2018-10-20 size:2 @georgeliuyu

**Comment by alisahuxu** [comment]
https://shimo.im/docs/6S0AgupLPeIrmLef/ 《小白健康slogan及奖励机制宣传方案》
https://shimo.im/docs/5XaluISXd90Eerj4/ 《slogan征集文案》
https://shimo.im/docs/Tqz8NEha5PoAXAT8/ 《落地页-文案》

**Comment by georgeliuyu** [comment]
下周一听你讲一讲。

alisahuxu <notifications@github.com> 于 2018年10月11日周四 上午10:29写道：

**Comment by alisahuxu** [comment]
收到




| |
alisa
邮箱：alisa_huxu@126.com
|

Signature is customized by Netease Mail Master

在2018年10月17日 10:03，georgeliuyu 写道：
下周一听你讲一讲。

alisahuxu <notifications@github.com> 于 2018年10月11日周四 上午10:29写道：

**Comment by georgeliuyu** [comment]
@fazhen 你组织一个会议，请金老师一起参加。我们讨论一下。
