### ISSUE TITLE
2018.10.15ICP发放

### ISSUE THREAD

**Issue by Jessica124** [sibbay-ai/public#502]
@sibbay-ai/all
本月icp即将发放，请所有贡献者抓紧时间自行检查各自的issue，在截止日期前完成修改的动作。
请各位将各自工作量截图回复至本issue中，将作为核对的依据，另外各位截图回复的同时要归纳列举一下本月工作内容
最晚请于2018-10-16 中午12点前完成回复，如在此之前未回复的，本月将不做发放，所以请各位务必按照此时间节点完成。
EI投票将于18日凌晨开始，截止至19日中午12点结束，投票完成是ICP发放的前提条件，所以请各位按时完成
@ben7th @sinchb @fushang318 请于2018-10-16将各自contribute的工作量汇总后发起钉钉流程。

**Comment by fushang318** [comment]
![image](https://user-images.githubusercontent.com/326242/46992330-14ae2480-d13c-11e8-992e-4453d2e288d6.png)

@Jessica124 
所有贡献者的 ICP SIZE 已经确认

你可以登录 http://icp.sibbay.ai/ 进入 2018_10_15 的 本月贡献统计 查看

**Comment by fushang318** [comment]
请在19日中午12点前，完成 2018_10_15 周期的投票，以免耽误发放
操作说明
1. 登录 http://icp.sibbay.ai
2. 进入 EI 统计 -> 2018_10_15 进入 投票页面进行投票
3. 确认投票完成并不在修改后，按照视频操作点击 确认投票完成按钮 http://sibbay-files.oss-cn-hangzhou.aliyuncs.com/icp_tutorial/%E9%94%81%E5%AE%9A%E6%8A%95%E7%A5%A8%E7%BB%93%E6%9E%9C.mp4

@Yidadaa
@aixinhuang
@akakenle
@ben7th
@bqx619
@fangrongxaing
@fazhen
@fushang318
@hnuyx
@kimgrace6
@maohuaming
@nancy919
@nullscc
@sinchb
@zhanhh187
@zhaobinglong

**Comment by Jessica124** [comment]
好的

**Comment by Jessica124** [comment]
@sibbay-ai/all 由于本月的20日是周六，ICP发放将在10月22日进行，请知晓，谢谢

**Comment by fushang318** [comment]
@Jessica124 为什么周六不能发放

**Comment by Jessica124** [comment]
申请开发 deadline:2018-11-15 size:2 @fushang318

**Comment by fushang318** [comment]
1
