### ISSUE TITLE
申请补充 CI 贡献值

### ISSUE THREAD

**Issue by destinyd** [sibbay-ai/public#503]
### 贡献内容
- 【小白健康】症状疾病及医检报告模块，小程序开发
- 【小白健康】项目内通用小程序 UI 组件重构
- 小白健康  用药和治疗模块，小程序开发

### 报酬总数
实收：20250（项目总额：22500）

###  时间
2017.03.15

### 是否经过icp认证
无

### 你的以太坊钱包地址
无

@georgeliuyu

**Comment by fushang318** [comment]
link https://github.com/sibbay-ai/public/issues/482
