### ISSUE TITLE
ms-server 如何自动增加到opensearch中

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#51]
现在的医学数据是保存在mongodb中的，可以通过后台管理系统MS进行修改和添加，但是查询用的是阿里的opensearch，需要手工进行数据的添加，是否有自动的方式实现opensearch的更新。

**Comment by georgeliuyu** [comment]
@fushang318 知晓

**Comment by fushang318** [comment]
@georgeliuyu 收到

**Comment by mayf09** [comment]
@georgeliuyu 能调用 开放搜索 api 来更新数据。
我觉得，后端数据保存到 mongodb 的同时，又保存到开放搜索。

**Comment by georgeliuyu** [comment]
@mayf09 opensearch能直接访问mongodb吗？

**Comment by mayf09** [comment]
@georgeliuyu 没看到相关的文档，应该不能
