### ISSUE TITLE
【小白健康】贡献者token发行说明会

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#517]
为进一步深化社区化的开发方式，探索以精确奖励为形式的基于愿景的组织模型（众和），同时融合用户和投资为一体综合通证模型。小白健康决定发行自己的token，并从贡献者奖励开始实施。为此我们决定进行一次说明会：
时间：2018年10月28日（周日）晚上9:00
形式：视频会议   https://zoom.us/j/9552592803
参与人员：所有参与过小白健康贡献的同学

### 特别提示：与你的利益和未来有密切的关系           

@sibbay-ai/all

**Comment by fushang318** [comment]
收到~

**Comment by fushang318** [comment]
以前做过 MRI 和 后台管理，以及运维，还有数据统计的 同学已经通知了

**Comment by fangrongxaing** [comment]
收到
