### ISSUE TITLE
关于认证流程需要配合的事情

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#52]
关于认认证流出，已经提交了相关文档已经提交pr；  
需要@ben7th 协作的：

1. 增加一份《icp协作规范》 包含协作issue模板
2. 认证issue模板
3. 前端pr模板
4. 在pr文档中增加code climate的规范，并给出使用code climate文档或者链接

需要 @sinchb 协作的：
1. 后端pr模板

@ben7th 作为mentor @fushang318 作为申请者做一次演练，所有的过程都@我和陈斌，我在过程中进行解释。

目标：周六完成文稿部分，周日会前完成演练。晚上讨论

**Comment by ben7th** [comment]
收到

**Comment by fushang318** [comment]
好的，我等着被测试 😆

**Comment by georgeliuyu** [comment]
@ben7th 进展如何？

**Comment by ben7th** [comment]
https://github.com/sibbay-ai/icp-test/issues/1
演练 issue

**Comment by ben7th** [comment]
@georgeliuyu @sinchb @fushang318 

由于 ISSUE_TEMPLATE 是对一个项目中所有 issue 生效的，无法划分类型，因此单独创建了用于认证的项目，并提交了 ISSUE_TEMPLATE

https://github.com/sibbay-ai/icp-certification
https://github.com/sibbay-ai/icp-certification/blob/master/ISSUE_TEMPLATE.md

针对 @fushang318 的认证过程演练已在该项目启动：
https://github.com/sibbay-ai/icp-certification/issues/1

**Comment by ben7th** [comment]
已补充 PULL_REQUEST_TEMPLATE

https://github.com/sibbay-ai/icp-certification/blob/master/PULL_REQUEST_TEMPLATE.md

**Comment by sinchb** [comment]
@ben7th 没有权限

**Comment by fushang318** [comment]
@sinchb 给你权限了
