### ISSUE TITLE
设计icpper的名片

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#528]
为了对外联络的需要，针对icp的贡献者设计电子名片。
可以在原来的名片设计的基础上进行修改
内容：
名称抬头：小白健康 icp贡献者
姓名
icp 排名（以参加的时间先后进行排名）陈斌应该是第一个。特出排名
电话
邮件
github账号

这是已经整理 https://shimo.im/sheet/KEoc3f2sEakYY0rB/RIDOC 贡献者名单。 @fushang318 你配合遗漏的部分。

@fangrongxaing 你负责设计
@ben7th 你看看是否要加内容，并进行审核。设计好后，在发放token的时候会给每个人的邮箱
deadline 2018-11-3

**Comment by ben7th** [comment]
### 内容

- 姓名
- ICP 排名（根据参加时间先后）
- 电话
- email
- github 账号

--------

示例：

> 宋亮
> ICP No. ***
> 13*********
> ***@***.com
> github.com/ben7th

**Comment by georgeliuyu** [comment]
@aixinhuang 名单的完善有你负责

**Comment by huangaixin** [comment]
收到 @georgeliuyu

**Comment by zhaobinglong** [comment]
姓名：赵冰龙
电话：15101056160
email： 570869214@qq.com
github 账号：zhaobinglong
出生年月：1992-10-14
城市：深圳

**Comment by georgeliuyu** [comment]
不要初始日期，加小程序的二维码 @ben7th @fangrongxaing

**Comment by ben7th** [comment]
姓名：宋亮
电话：13811174717
email: ben7th@sina.com
github: @ben7th 
生日：1984-10-28
加入时间：2016-12-30
城市：广州

**Comment by bqx619** [comment]
姓名：吴善超
email: bqx619@gmail.com
github: @bqx619 
生日：1994-10-26
加入时间：2017-12-25
城市：湖北武汉

**Comment by choufeng** [comment]
姓名：夏佳
email: xiajia@vip.qq.com
github: @choufeng
生日：1982-10-04
加入时间：2017-1-17
城市：广州

**Comment by nullscc** [comment]
姓名：谢志伟
电话：19873665932
email： jarves@foxmail.com
github 账号：nullscc
出生年月：1992-05-26
加入时间：2018-08-01
城市：深圳

**Comment by sinchb** [comment]
姓名：陈斌
电话：18616370690
email: sinchb128@gmail.com
github: @sinchb 
生日：1989-01-28
加入时间：2016-06-01
城市：上海
