### ISSUE TITLE
关于token发行上线的会议

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#531]
### 1、上线仪式
- 撰写以太坊账号和钱包的使用建议
- 搜集所有的贡献者的以太坊地址，icp的同学要求有一句话（随你说什么）
- www.sibbay.ai的倒计时
- 公布每个贡献者得到token数量
- 在上线仪式上一次性将所有的奖励发放给到所有的贡献者，并把一句话写到以太坊上
- 每个人可以进行查询和提现（提前准备好文档）
- 这次有许多的其他朋友参加
### 2、贡献者名片
- 发行贡献者的具有极客范的名片
- 设计一个用于分享到朋友圈的icp证书（一定要有极客范），icpper要求分享到朋友圈（如兼职同学有风险的可以在这个issue的下面提出来，可不用分享）

上线仪式时间：11月25日 9:00

三个
deadline：
11月15日进行第一次全流程测试，包含所有的文档；
11月20日进行第二次全流程测试演练，包含文档润色；
11月24日进行一次上线前最后演练

谁能来组织这个事情？ committer委员会安排并通知我

@fushang318 @ben7th @sinchb

**Comment by georgeliuyu** [comment]
参与人员： @fushang318 @王靖 @石宏 @爱欣

**Comment by georgeliuyu** [comment]
会议分为：
1、刘宇演讲，新型组织形式的探索与实践
2、贡献者发言（committer设计）
3、SHT的发放（committer设计）
2、3两条的由你们geek做，怎么做都可以，不要有局限！^-^
背景音乐建议imagine

@sinchb @ben7th @fushang318

**Comment by ben7th** [comment]
https://github.com/orgs/sibbay-ai/projects/25
上线仪式规划 project

**Comment by sinchb** [comment]
@georgeliuyu @ben7th @fushang318 这个  11月25日 9:00 是早上还是晚上？因为上次讨论结果是晚上。

**Comment by fushang318** [comment]
晚上
