### ISSUE TITLE
对申请进行技术评估，核心内容-VUE

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#54]
下面3名申请者：
https://coding.net/t/sibbay-hr/p/lt/topic/368818  
https://coding.net/t/sibbay-hr/p/lt/topic/368835  
https://coding.net/t/sibbay-hr/p/lt/topic/368864  
经过第一次初步沟通后，确认其主观意愿和想法基本符合小白的价值观，同时也认真地阅读了小白的众和模式和icp流程并认可基本理念，并且有空余时间。  
现由VUE方面熟悉的同学进行技术评价。  
结论形式（直接写到简历库中）：
**评分**：_采用5分制  3（基本掌握） 4（很熟悉） 5（该领域的专家）_  
**评价**：_从思维方式、创新能力、知识面、协作精神等等方面（但不限于），给出不超过50个字的主观评价_

**Comment by ben7th** [comment]
@georgeliuyu 

我设想的可行评价方式：

- 回答与前端相关，以及与项目协作相关的几个开放式问题（不限于 VUE.js）；
- 对小白目前的前端代码（后台管理 and 小程序）给出点评；

形式：

- 通过石墨文档提出问题，各自通过石墨文档给出回答；

几位申请者用来完成这次技术评价的耗时，从获得问题开始，半天为宜；

若上述方式可行，我在周六（2017-12-16）通过此 issue 发送石墨文档问卷；
几位申请者需要通过 github 账号在此回复，以便我知道该去 @ 谁

**Comment by georgeliuyu** [comment]
@ben7th 这个是在申请者中标之前的评价，所以不宜做得太复杂。同时在确认为认证贡献者之前不宜公开申请者的资料，所以建议通过电话联系。

**Comment by ben7th** [comment]
@georgeliuyu 好，我简化一下

**Comment by georgeliuyu** [comment]
@ben7th 具体你确定

**Comment by georgeliuyu** [comment]
@ben7th 
增加评测人员：
https://coding.net/t/sibbay-hr/p/lt/topic/369107

**Comment by georgeliuyu** [comment]
https://coding.net/t/sibbay-hr/p/lt/topic/369108 
https://coding.net/t/sibbay-hr/p/lt/topic/369110

**Comment by georgeliuyu** [comment]
@ben7th 今天给出测试问卷？

**Comment by ben7th** [comment]
@georgeliuyu 已撰写问卷：
https://shimo.im/docs/S9YAkBtN8UsvncGU/ 「前端开发者，沟通交流问卷」

目前是否已加各评测人员微信？若有微信，直接加我通过微信发送问卷链接；
若未加微信，我去逐个联系；

**Comment by georgeliuyu** [comment]
@ben7th 建议将测试文档，进入github管理。

**Comment by ben7th** [comment]
@georgeliuyu 
问卷可以整理成 markdown 的形式。
被测试者提交的内容也纳入管理吗？纳入的话要建私有库。

**Comment by georgeliuyu** [comment]
@ben7th 嗯，好的，这样有个历史，以后用的时候也方便。
