### ISSUE TITLE
关于推进icp贡献发放审计的工作

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#547]
为了进一步推进小白众和社区的持续发展，我们应该建立项目推进效率的分析和提高，应该进行异常和风险管控。为此财务人员应该做：
- 逐步建立效率分析机制
- 对异常或有风险的项目和贡献者应该进行问询和调查

@Jessica124 负责  
@ben7th @fushang318 @sinchb 知晓

**Comment by ben7th** [comment]
已获知

**Comment by Jessica124** [comment]
收到

**Comment by fushang318** [comment]
已获知
