### ISSUE TITLE
SHT小额发放验证代理申请

### ISSUE THREAD

**Issue by Jessica124** [sibbay-ai/public#548]
刘总：鉴于18号我们将进行小额SHT转账测试，此次发放需要4950个SHT，请给李飞一个代理，代理限额为4950个SHT。
李飞的账号：0xB3B4C9e6BDfD063d5647Fc1c8773EaCFe03cf370
此笔款项将从CA账户（0x9A6372d8b657ec9aC5E08E9Ce6d62C124A3c39be）中支付
@georgeliuyu @fushang318

**Comment by fushang318** [comment]
另外
1. 增加 0x842E83997aFC6905F7dCB2A9bEb9D7fd88Eb6A92 为管理员，用于每天更新价格
2. 设定 SHT 美元价格

**Comment by fushang318** [comment]
合约地址
0x3D9c6C5A7b2B2744870166EaC237bd6e366fa3ef

abi
https://github.com/sibbay-ai/token/blob/master/output/abi.json

owner:0x6Bd5f0f1846F913CfF230014C32aC6F4E4fAd4B0
funding：0x8A0e4B86CD76684057BC0e62B5753F513fC332BB

**Comment by Jessica124** [comment]
代理账户：0x45b35dd33b6040193f3eda9d5fe696998a5c1c02

**Comment by fushang318** [comment]
https://etherscan.io/address/0x3D9c6C5A7b2B2744870166EaC237bd6e366fa3ef
