### ISSUE TITLE
关于促进EI效率值低的同学改善的通知

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#558]
各位committer！
     为推动社区效率的提升，对于EI值较低的同学，特别是连续很低的同学要求committer在审批时要从严管控。
     @Jessica124和committer商量一下。并在下个月给我改善的评估情况。
 
   @ben7th @fushang318 @sinchb 执行。
   @sibbay-ai/all 所有人知晓
                                               
小白社区  刘宇

**Comment by Jessica124** [comment]
收到

**Comment by kimgrace6** [comment]
收到

**Comment by fushang318** [comment]
收到

**Comment by aixinhuang** [comment]
收到
