### ISSUE TITLE
邮箱申请

### ISSUE THREAD

**Issue by Jessica124** [sibbay-ai/public#568]
@sibbay-ai/all
如果各位同学因为工作需要，需要申请小白健康的邮箱，请将邮箱前缀的名字（即xxx@sibbay.ai）报送给我，我汇总后统一处理。截止日期至2018年12月26日中午12点。谢谢

**Comment by aixinhuang** [comment]
我的邮箱：aixin@sibbay.ai @Jessica124

**Comment by fushang318** [comment]
@Jessica124

**Comment by fushang318** [comment]
@Jessica124
