### ISSUE TITLE
新版互动管理 - 1.0 reivew

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/public#57]
所有代码都已经提交部署到了 测试环境
可以通过 http://dbtest.sibbay.net 访问进行 reivew

@NiuShy @georgeliuyu @yeyuexia

**Comment by fushang318** [comment]
@NiuShy 
我先提几个问题
1. 请求 github api 时请求头的 Authorization 没有设置正确，应该是 ”token <github token>”
2. 控制 mri_sandbox 时，需要不断请求后端的 mri_sandbox_status 获取状态，这个请求的心跳需要改的大一些，目前太频繁，会导致API使用次数过多被封掉，改成 5 秒钟一次比较合适
3. 目前的初始化MRI首先于 daocloud 的api 有很大几率会出问题，需要调整成
  3.1 先调用 mri_sandbox_remove，然后等待5秒钟
  3.2 调用 mri_sandbox_start
  3.3  过 5秒调用一次 mri_sandbox_status

**Comment by NiuShy** [comment]
@fushang318  好的

**Comment by fushang318** [comment]
@NiuShy 

> 请求 github api 时请求头的 Authorization 没有设置正确，应该是 ”token ”

这个问题已经通过环境变量修复

**Comment by fushang318** [comment]
@NiuShy @georgeliuyu 
测试环境操作的是  https://github.com/sibbay-ai/ms-test-data-mri  这个版本库

**Comment by fushang318** [comment]
@NiuShy 
修改好 Authorization 后我体验了一下，发现如下几个问题
1. 一个用户第一次启动互动管理时，或者点击初始化后刷新页面，这个时候后端需要启动一个新的 mri_sandbox ,需要的时间比较长，这种情况下，前端已经从 GitHub 读取完了json ，但是 mri_sandbox 还没有启动完毕，这个时候前端调用启用 bunch 的 API 会出错
2. 现在的分支名是 `<user_login>` ，需要改成 `ms/<user_login>`
3. 发送事件的请求，userid 是模拟用户的id ，不是后台管理用户id

**Comment by georgeliuyu** [comment]
请从这里进入
![image](https://user-images.githubusercontent.com/16983441/34092899-9bcf968a-e400-11e7-8f99-2ae161420ab6.png)

**Comment by fushang318** [comment]
@NiuShy 
你看一下我在你PR的回复

**Comment by NiuShy** [comment]
修改相关bug

- 获取沙盒状态频率改为5s
- 分支名改成 ms/<user_login>
- 发送事件的请求header userid 取模拟用户的id
- 重启或者重新初始化时 编辑器相关按钮不可操作
- 修改互动管理链接为新版互动管理

**Comment by fushang318** [comment]
@NiuShy 
还有两个关于重新初始化会出现的BUG，我明天录像说明一下给你吧

**Comment by fushang318** [comment]
@NiuShy 
我已经录像说明了几个BUG的问题，应该是 3 个 BUG，一个需要优化

为了方便你进行BUG修改，我提供给你 daocloud 访问账号，以及一个介绍视频

介绍视频  
http://sibbay-image.oss-cn-hangzhou.aliyuncs.com/review/new_mri_mange_1/mri-sandbox-api%E4%BB%8B%E7%BB%8D.webm

BUG1: 请求5S频率问题
http://sibbay-image.oss-cn-hangzhou.aliyuncs.com/review/new_mri_mange_1/mri-sandbox-api%20%E8%AF%B7%E6%B1%825S%E9%A2%91%E7%8E%87BUG.webm

BUG2: 重新初始化BUG
http://sibbay-image.oss-cn-hangzhou.aliyuncs.com/review/new_mri_mange_1/mri-sandbox-api%20%E9%87%8D%E6%96%B0%E5%88%9D%E5%A7%8B%E5%8C%96BUG.webm

BUG3: 请求顺序导致文件树卡主BUG
http://sibbay-image.oss-cn-hangzhou.aliyuncs.com/review/new_mri_mange_1/mri-sandbox-api%20%E6%96%87%E4%BB%B6%E6%95%B0%E5%8D%A1%E4%B8%BBBUG.webm

优化：刷新 iframe 优化
http://sibbay-image.oss-cn-hangzhou.aliyuncs.com/review/new_mri_mange_1/mri-sandbox-api%20%E5%88%B7%E6%96%B0%20iframe%20%E4%BC%98%E5%8C%96.webm

**Comment by NiuShy** [comment]
@fushang318  好的

**Comment by NiuShy** [comment]
@fushang318  已修改&合并

**Comment by NiuShy** [comment]
另 @fushang318  重新初始化后 ，是根据获取状态接口的异常信息里的 not_find 来确定调用start的

**Comment by fushang318** [comment]
@NiuShy 

> 另 @fushang318 重新初始化后 ，是根据获取状态接口的异常信息里的 not_find 来确定调用start的

额，抱歉，这个应该是我写的API接口的BUG，我微信找你咱们协同修改一下
