### ISSUE TITLE
上线总结和反思

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#573]
2019年1月1日 00:00 小白健康终于正式上线了。
这是所有贡献者努力的结果，也是朋友支持的结果，更是用户包容的结果。
同时这次上线也暴露出很多的问题，建议社区进行一次深刻的总结和反思
#### 那些处于逆境中相互激励一下就能做好的事情；

众和社区的第一条就是尊重与信任，我信任你们：是有能力克服困难的，有能力自我反省和提高的。

更能共建一个受人尊重的社区。

作为创始人，也作为社区的一名贡献者我也会从自己开始反思。

                                       刘宇
@ben7th 建议将今天晚上的会议移到明天晚上，给大家留一些时间思考。每个人都提前准备一下，如果你希望匿名可以发给 @aixinhuang ，由她来宣读

**Comment by ben7th** [comment]
@sibbay-ai/all

**Comment by ben7th** [comment]
收到。我将总结近期开发与运营组织上体会到的问题。

**Comment by nullscc** [comment]
收到

**Comment by zhaobinglong** [comment]
收到
