### ISSUE TITLE
@ben7th 2019-01-16 ICP 补充申请

### ISSUE THREAD

**Issue by ben7th** [sibbay-ai/public#576]
# ben7th 2019-01-16 ICP 补充申请

### 类别：前端开发工作
| issue | pr | size |
| --- | --- | --- |
| [https://github.com/sibbay-ai/lt-miniapp-wepy/issues/843](https://github.com/sibbay-ai/lt-miniapp-wepy/issues/843)<br />在 MRI 中实现通过选项触发的推广中心入口 | [https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840](https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840) | 2 |
| [https://github.com/sibbay-ai/lt-miniapp-wepy/issues/844](https://github.com/sibbay-ai/lt-miniapp-wepy/issues/844)<br />在 MRI 中实现气泡收取的音效 | [https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840](https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840) | 0.5 |
| [https://github.com/sibbay-ai/lt-miniapp-wepy/issues/845](https://github.com/sibbay-ai/lt-miniapp-wepy/issues/845)<br />调整下级气泡的尺寸 | [https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840](https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840) | 0.5 |
| [https://github.com/sibbay-ai/lt-miniapp-wepy/issues/826](https://github.com/sibbay-ai/lt-miniapp-wepy/issues/826)<br />特性：下级气泡上显示直接下级名字 | [https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840](https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840) | 0.5 |
| [https://github.com/sibbay-ai/lt-miniapp-wepy/issues/821](https://github.com/sibbay-ai/lt-miniapp-wepy/issues/821)<br />为互动对话特定选项增加提示箭头 | [https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840](https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840) | 1 |
| [https://github.com/sibbay-ai/lt-miniapp-wepy/issues/846](https://github.com/sibbay-ai/lt-miniapp-wepy/issues/846)<br />简化小白登录授权过程，根据设计优化登录页面内容 | [https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840](https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840) | 1.5 |
| [https://github.com/sibbay-ai/lt-miniapp-wepy/issues/847](https://github.com/sibbay-ai/lt-miniapp-wepy/issues/847)<br />在点击 MRI 普通选项时增加 formId 收集机制 | [https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840](https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840) | 1.5 |
| [https://github.com/sibbay-ai/lt-miniapp-wepy/issues/848](https://github.com/sibbay-ai/lt-miniapp-wepy/issues/848)<br />优化模板通知消息的进入跳转页面 | [https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840](https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840) | 1.5 |
| [https://github.com/sibbay-ai/lt-miniapp-wepy/issues/849](https://github.com/sibbay-ai/lt-miniapp-wepy/issues/849)<br />屏蔽托付记录时切换用户后的一些功能访问 | [https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840](https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840) | 0.5 |
| [https://github.com/sibbay-ai/lt-miniapp-wepy/issues/850](https://github.com/sibbay-ai/lt-miniapp-wepy/issues/850)<br />屏蔽他人帮助收取气泡的功能 | [https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840](https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840) | 0.5 |
| [https://github.com/sibbay-ai/lt-miniapp-wepy/issues/851](https://github.com/sibbay-ai/lt-miniapp-wepy/issues/851)<br />BUGFIX：修正匿名马甲开启和关闭操作报错的问题 | [https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840](https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840) | 0.5 |
| [https://github.com/sibbay-ai/lt-miniapp-wepy/issues/852](https://github.com/sibbay-ai/lt-miniapp-wepy/issues/852)<br />BUGFIX：修正生命力列表的时间显示，加载体验等问题 | [https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840](https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840) | 0.5 |
| [https://github.com/sibbay-ai/lt-miniapp-wepy/issues/853](https://github.com/sibbay-ai/lt-miniapp-wepy/issues/853)<br />修改健康种子传播卡片样式和内容 | [https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840](https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840) | 0.5 |
| [https://github.com/sibbay-ai/lt-miniapp-wepy/issues/854](https://github.com/sibbay-ai/lt-miniapp-wepy/issues/854)<br />优化上下级关系建立跳转页的处理逻辑 | [https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840](https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840) | 1 |
| [https://github.com/sibbay-ai/lt-miniapp-wepy/issues/855](https://github.com/sibbay-ai/lt-miniapp-wepy/issues/855)<br />在 MRI 中实现客服入口整合 | [https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840](https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840) | 1 |
| [https://github.com/sibbay-ai/lt-miniapp-wepy/issues/856](https://github.com/sibbay-ai/lt-miniapp-wepy/issues/856)<br />BUGFIX：修正用户通过分享卡片进入小程序时，授权重复弹出的问题 | [https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840](https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840) | 0.5 |
| [https://github.com/sibbay-ai/lt-miniapp-wepy/issues/857](https://github.com/sibbay-ai/lt-miniapp-wepy/issues/857)<br />在用户设置里增加完全隐私开关，并实现完全隐私的屏蔽访问 | [https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840](https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840) | 1 |
| [https://github.com/sibbay-ai/lt-miniapp-wepy/issues/858](https://github.com/sibbay-ai/lt-miniapp-wepy/issues/858)<br />BUGFIX：修正个人页面记录存档列表无法显示他人数据的问题 | [https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840](https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840) | 0.5 |
| [https://github.com/sibbay-ai/lt-miniapp-wepy/issues/859](https://github.com/sibbay-ai/lt-miniapp-wepy/issues/859)<br />BUGFIX：修正气泡面板与推广 UI 重叠的问题 | [https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840](https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840) | 0.5 |
| [https://github.com/sibbay-ai/lt-miniapp-wepy/issues/874](https://github.com/sibbay-ai/lt-miniapp-wepy/issues/874)<br />2018-12 至 2019-1 代码合并 review 管理 | [https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840](https://github.com/sibbay-ai/lt-miniapp-wepy/pull/840) | 1 |
| 总计 |  | 17 |

### 类别：后端开发工作
| issue | pr | size |
| --- | --- | --- |
| [https://github.com/sibbay-ai/lt-miniapp-wepy/issues/822](https://github.com/sibbay-ai/lt-miniapp-wepy/issues/822)<br />故障排查：打赏报错 | [https://github.com/sibbay-ai/cooperation-issues/pull/1593](https://github.com/sibbay-ai/cooperation-issues/pull/1593) | 0.5 |
| [https://github.com/sibbay-ai/sr-wiki/issues/408](https://github.com/sibbay-ai/sr-wiki/issues/408)<br />收取生命力通知的发送时机调整技术方案 | [https://github.com/sibbay-ai/cooperation-issues/pull/1593](https://github.com/sibbay-ai/cooperation-issues/pull/1593) | 1 |
| [https://github.com/sibbay-ai/sr-wiki/issues/406](https://github.com/sibbay-ai/sr-wiki/issues/406)<br />数据故障排查：当天仅记录了“记日记”用户的动态时间显示错误 | [https://github.com/sibbay-ai/cooperation-issues/pull/1593](https://github.com/sibbay-ai/cooperation-issues/pull/1593) | 0.5 |
| [https://github.com/sibbay-ai/sr-reminder/issues/96](https://github.com/sibbay-ai/sr-reminder/issues/96)<br />方案梳理：对现有通知模板的调整 | [https://github.com/sibbay-ai/cooperation-issues/pull/1593](https://github.com/sibbay-ai/cooperation-issues/pull/1593) | 1.5 |
| [https://github.com/sibbay-ai/sr-wiki/issues/413](https://github.com/sibbay-ai/sr-wiki/issues/413)<br />sns 代码合并故障修正 review | [https://github.com/sibbay-ai/cooperation-issues/pull/1593](https://github.com/sibbay-ai/cooperation-issues/pull/1593) | 0.5 |
| [https://github.com/sibbay-ai/sr-wiki/issues/457](https://github.com/sibbay-ai/sr-wiki/issues/457)<br />方案梳理：通过遍历方式统计传播人数和能量值 | [https://github.com/sibbay-ai/cooperation-issues/pull/1593](https://github.com/sibbay-ai/cooperation-issues/pull/1593) | 1 |
| 总计 |  | 5 |

### 类别：运营支持工作

| issue | pr | size |
| --- | --- | --- |
| [https://github.com/sibbay-ai/mri-co-write/issues/31](https://github.com/sibbay-ai/mri-co-write/issues/31)<br />静态互动编写工具的特性实现和优化 | [https://github.com/sibbay-ai/cooperation-issues/pull/1593](https://github.com/sibbay-ai/cooperation-issues/pull/1593) | 2 |

**Comment by ben7th** [comment]
本月补充申请 SIZE：24

请 @fushang318 @sinchb @georgeliuyu 审核

**Comment by fushang318** [comment]
issue count:27 size:24

**Comment by ben7th** [comment]
@fushang318 👌

**Comment by fushang318** [comment]
这些补充到下一周期进行投票的 ISSUE 在 ICP 系统中都标记为了 deadline过期
这些 ISSUE 是否获得投票，只会影响EI，不会影响CI，所以也不会作为 token 奖励的基数
