### ISSUE TITLE
@Yidadaa 2019-01-16 ICP 补充申请

### ISSUE THREAD

**Issue by Yidadaa** [sibbay-ai/public#577]
# Yidadaa 2019-01-16 ICP 补充申请

|issue|pr|size|
|-|-|-|
|【需求】个人中心变更 <br> sibbay-ai/lt-miniapp-wepy#774|sibbay-ai/lt-miniapp-wepy#776|2.0|
|【个人中心bug】疾病/用药/治疗历史入口进入不显示恢复跟踪按钮<br> sibbay-ai/lt-miniapp-wepy#785|sibbay-ai/lt-miniapp-wepy#786|0.2|
|【个人中心bug】症状详情中，添加跟踪时间展示nan <br>sibbay-ai/lt-miniapp-wepy#781|sibbay-ai/lt-miniapp-wepy#783|0.1|
|【个人中心bug】正在跟踪的用药全部停止后，概况页面空白<br> sibbay-ai/lt-miniapp-wepy#780|sibbay-ai/lt-miniapp-wepy#783|0.1|

**Comment by Yidadaa** [comment]
本月补充申请 SIZE：2.4

请 @fushang318 @sinchb @georgeliuyu 审核

**Comment by fushang318** [comment]
issue count:4 size:2.4

**Comment by fushang318** [comment]
这些补充到下一周期进行投票的 ISSUE 在 ICP 系统中都标记为了 deadline过期
这些 ISSUE 是否获得投票，只会影响EI，不会影响CI，所以也不会作为 token 奖励的基数
