### ISSUE TITLE
从宋亮的沮丧引发的思考

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#579]
从昨天看到宋亮在站会群发出的信息后我就一直在思考问题核心是什么。
从去年token上线，宋亮整体的管理工作，更承担了token网页的几乎全部前后端工作；
到1月1日小白健康正式上线，特别是出现了几次重大事故后，整个团队面临巨大压力的时候，他对相关的技术问题进行了逐行的review，对每一项工作都进行跟进，每天给出进展报告；
再到这次“牵金猪”的活动，他承担了几乎全部的开发工作，昨天已经正式上线了。
而这个过程中也积累下了一些产品的问题和隐患，有些事情也被落下了（例如社区的月报），在全力准备正式在上线的前一天我们的重点用户却出现了严重的使用问题，截止昨天晚上宋亮和李飞已经进行了妥善的解决。
而宋亮的困境表面看是没有时间，或者是任务太多。
也许这次活动后整个开发工作又会回归到正常轨迹，开始有时间处理那些遗留事情；
也许我们会有一段时间的从容
但是从长远看也许我们一定会遇到更多其他的挑战和困境，而这些不是我们能进行计划和预测的；
我的责任不是让大家舒服，而是带领大家走向成功，不是避开困难，而是挑战高峰。做真正能造福大众的事情。
那我们的出路是什么呢？只有一条：team，一个“危则拼死相救、成则举杯相庆”的team，一个放心把后背交出去的team
而我把后背交给了你们，交给了宋亮，交给了李飞，交给了南希、赵冰龙、陈斌、、、
那么宋亮能把后背交给谁：李飞、赵冰龙、张义飞、、？
你能交给谁？谁能交给你？

众和社区已经“用规则给人性按了个家”（奖励制度）
今年是时候要将侧重点放到”团队精神“的建立上了（去实现大家的理想）

@sibbay-ai/all 大家可以留言

**Comment by georgeliuyu** [comment]
![image](https://user-images.githubusercontent.com/16983441/52158910-4e4d7000-26d8-11e9-803e-e7a40c449c61.png)

**Comment by zhaobinglong** [comment]
我的一个想法：鼓励社区用户，健康记录专家，普通用户对小白当下的产品设计提出改进或者更好的替代设计(例如：图片删除点击区域太小，更不能改大)。当建议被产品采纳后，给与提出者token奖励或者其他，通过月报或者社区公告的方式，告知所有用户

目前我们社区QA同学的责任是发现bug，当他们发现可以改进的地方时，也应该被重视

鼓励用户提出自己的建议，然后有奖励机制，一个正向的循环

某些很小的优化：比如说点击区域太小，可以不用大版本迭代，直接提一个issue，我可以利用空余的时间随手去改，比发大版本的效率高

**Comment by zhaobinglong** [comment]
补充：这样唯一会导致一个问题，就是我们的产品记录会比较分散，细节的修改散布在各个issue中

**Comment by georgeliuyu** [comment]
@zhaobinglong 好主意，发动群众是我们最应该做的一个方法。但是如何做到有序，有效率。可以再细化

**Comment by Yidadaa** [comment]
承接@zhaobinglong 的思路，目前社区的很多工作都是靠人力来完成的，包括健康记录专家的留言奖励机制（半自动统计＋微信群组织）、用户的反馈建议（微信群、客服或者直接反馈给开发）、项目的优先级排期等等，这些东西使用人力的好处是对用户很友好，但也有诸多弊端，比如采用人力统计然后再统一给奖励，实时性不强，给用户的激励就不足，如果能自动化进行，然后形成一个排行榜机制，用户的主动性会极大增高。

### 别人的产品是如何做用户反馈的？
首先就本 issue 提到的主题来说，很多的应用都有“反馈&建议”渠道，目前小白的反馈&建议渠道还缺乏规范性，比如对应于支付宝（图一），在支付宝内任意界面截图，支付宝都会展示一个悬浮窗口，询问用户是否需要求助反馈，点击进入后分为**问题求助**和**意见反馈**两个部分，如果点击问题求助，会进入智能客服，里面列出了常见问题，如果用户觉得这些都解决不了问题， 才会转入人工客服。回顾整个流程，遇到问题的用户经过了三次分流，层层分流后才会转入人工客服，同时意见反馈界面给出了清晰明了的问题分类和问题描述引导。微信的帮助反馈界面与支付宝类似，但是没有人工客服。

![图一](https://user-images.githubusercontent.com/16968934/52160685-13a60080-26f5-11e9-9eb6-f376c1274c98.jpg)

此外如果将用户反馈与奖励结合，可能需要参照MIUI论坛或者滴答清单的这种论坛形式的反馈机制，目前用户的反馈基本都在微信上进行，方便是方便了，但是每条反馈不易追踪，而且丢失风险很大，所以可以考虑建设单独的论坛反馈机制，以MIUI论坛和滴答清单为例（图二及图三），用户的每条反馈都会以帖子的形式存在于社区中，其他用户可以随时检索/发布新的功能建议以及问题反馈，管理员也会及时地看到反馈并进行回复。

![图二](https://user-images.githubusercontent.com/16968934/52160885-18b87f00-26f8-11e9-87f7-2fa6d7c2a0be.jpg)

![图三](https://user-images.githubusercontent.com/16968934/52160879-063e4580-26f8-11e9-9409-87af315e10cd.png)

### 小白可以从中学到什么？
1. 建立更加规范的反馈渠道，增加可以上传图文视频信息的反馈页面，使得用户的每条反馈可追踪/可归档/可检索，用户也可以更及时地看到官方反馈，缓解用户焦虑；
2. 提升反馈渠道的易用性，可以借鉴支付宝的截图反馈机制（微信小程序提供了监听用户截图事件的api），增加智能客服（小白本身就有问询机制，这一点优势很大）和FAQ常用问题解答；
3. 将用户反馈与社区奖励挂钩，此条建立在第一条的基础上；
4. 区分用户反馈的优先级，小白的人力是有限的，用户的需求是无限的，用有限的人力完全解决用户的需求是不现实的，所以应当优先解决高优先级的问题，这一准则当然已经从小白建立之初就开始推行了，只不过一直没有形成规范，所以很难发挥出其效果，我认为这一点与第一点同样息息相关，在用户提供反馈时，把用户可能遇到的问题分好类供用户选择，这样更加方便小白管理不同层级的反馈。

**Comment by Yidadaa** [comment]
以上我仅从产品角度提出了针对@zhaobinglong 提议的建议。

本issue的核心问题还是出在了人力资源的管理上，小白的团队运行模式，之前已经在很多次会议中进行过讨论，目前的团队应对日常开发似乎是可行的，但似乎又经受不起密集开发的考验，多个开发任务同时进行时，核心成员往往会第一时间挺身而出参与进去，压力没有分散开，导致出现各种各样的小问题。

那么该如何解决呢，其实我并没有特别成熟的建议，但是我认为CPU的流水线式工作方式可以给我们提供一些灵感，现代CPU为了提升运行速度，都会引入流水线的概念，简而言之，就是将指令的执行过程拆分成固定的几个阶段，比如最常见的五段式：
1. 取指令：读取下一条要执行的命令；
2. 译码：分析指令类型，并准备好CPU内部的硬件资源（负责加减乘除操作的硬件）并从寄存器中读取数据；
3. 执行：执行指令对应的操作，每个操作可能会花费1~N个时钟周期进行；
4. 访存：如果指令运行结果需要写入到主存中，则写入；
5. 写回寄存器：如果指令运行结果会被后续指令用到，则需要写回对应的寄存器。

不难看出，流水线的工作方式，可以完美的映射到团队合作上来：
1. 取指，需求的提出及分析；
2. 译码，安排开发人员，从产品处拿到开发文档；
3. 执行，开发人员开始开发；
4. 访存，非必然工作，比如撰写文档等等；
5. 写回，交付测试并上线。

以上的映射关系并不严谨，因为各个阶段不可能完全分离，但这个映射有助于帮助我们分析问题，所以无伤大雅。

本issue的问题，便是译码阶段出了问题，没有合理地安排开发人力，造成了性能损耗。在CPU中，都会维护一个表，表中记录了各个部件的运行情况，如果部件正在运行，那么要用到此部件的指令是不能进入流水线的，对应到本问题中，我们可以做出以下疑问：
- 产品排期时，是否考虑了开发人力的可用性？
- 安排人力时，是否出现了估计失误，是否出于乐观而给开发人员（包括指派者自己）指派了过多的任务？
- 我们现在是否仍然无法获取准确的人力可用性信息？
- 对于每一个需求的开发，其开发过程是否是可回溯的？如果现在要复盘1.15某个版本的开发工作，能做到准确恢复出该版本的总消耗人力/总开发时间/bug数/平均bug修复时间等等数据信息？如果不能，那么想要解决问题无异于建造空中楼阁。

以上问题，我们可能只能做出是或者否的回答，而永远也不能给出完美的解决方法，但就像NP问题一样，我们可能永远也无法找出多项式时间内的解法，但我们依然可以给出伪多项式时间的近似解法，这并不妨碍我们用来解决实际问题。

**Comment by bqx619** [comment]
承接大家的想法, 觉得针对这一点有些感悟
```
完善建立反馈机制, 防止被更多用户发现(可能已经在某个人记录的 TODOLIST 里面了)
```
结合自己曾经在 18 年的某一段时间, 因为来自各个渠道的事情混杂在一起, 各个方面还都必须要照顾到, 从而使得自己去调研了一系列的 project 管理工具, GTD(时间管理)等等工具, 因为自己在那段时间如果不借助这些工具, 每天会变得一团糟, 典型的结果就是, **我觉得明天要做的事情, 不得不在后天甚至更久才有时间安排, 因为明天会有更重要的事**, 当时的感受可能和 @ben7th 相似. (当时也是几个人一起).

于是我带头使用过: things3, 番茄清单, 奇妙清单, 滴答清单等等管理自己,  在实验室项目里面使用过 teamcity, youtrack, Jiar, worktile, teambition, tower, tapd 等等管理推进项目. 这里不去说这些工具谁好谁坏, 但最后的结果是, 成功的熬过了那段时间, 各方面的事情也都完成的还不错, 事后评估, 团队中的每个人基本都成功的使出了自己能够做到的 110%-120% .

我觉得最大的原因是: 流程的完善, 我打开一个工具可以清晰的知道每一件事:
- 都进行到了哪
- 有哪些事情需要进行但没有进行
- 每件事情大概需要多长时间
- 谁愿意做
- 谁这半天有时间可以做
- 有哪些事情是在第一个迭代中必须完成的
- ...

得益于这一类的研发工具, 使得我们一目了然, 哪怕我们都还初出茅庐, 但也算是成功的做好了应该做的事情. 当然目前 Github 的 issue, project 功能有一定类似, 但是我觉得还无法真正应用到每次迭代上, 需要的辅助工具还是很多.

附一:

- ![image](https://user-images.githubusercontent.com/9692149/52163762-d3a94280-2721-11e9-8aae-d3e113d2b823.png)
<div align="center">图一: 栏目</div>

附二:

- [微信的迭代故事](https://www.tapd.cn/official/case_example/1120106291001001670)

![image](https://user-images.githubusercontent.com/9692149/52163780-59c58900-2722-11e9-83fd-288a4ab96cbf.png)
