### ISSUE TITLE
使用阿里云数+ maxcompute 开发数据统计服务

### ISSUE THREAD

**Issue by ben7th** [sibbay-ai/public#58]
### 1、目标

目前有一些数据存储在 mongoDB 数据库中，需要对这些数据进行一些指标的统计工作

- 使用阿里云数+ maxcompute 读入数据，在数+ 平台编写服务完成数据统计工作，并将统计结果保存到指定目标数据库
- 将服务配置成按一定周期自动运行，从而实现定期对源数据库中的数据进行统计

#### 1.1、选型/环境

- 阿里云数+ maxcompute

#### 1.2、文档

- 通过沟通理解需求后，写一篇设计文档

#### 1.3、开发

- 读取 mongoDB 数据库
- 使用阿里云数+ maxcompute 开发和运行，遵循其平台规范
- 相关代码提交到指定 git 版本库，由运维人员进行 CI/CD 管理
- 统计过程中，对于异常情况输出日志记录

#### 1.4、建议

- 统计要求涉及六类统计项，数十项统计指标。希望先选取其中一类统计项进行实践，完成整个服务架构和调度体系的搭建；
- 在此基础上进一步完成其他统计项；

#### 2.1、阶段和验收

周期：7 天（明确需求后，以开发者承诺为准）

#### 2.2、调整和处罚（码市）

- 可以进行一次时间调整申请，最长不超过 2 天。
- 未申请或已经有过调整的，每延期一天按项目金额的 10% 进行罚款。
- 超过 5 天，需求方有权取消项目。
- 需求方原因造成的延误不包含在内。

#### 3.1、人员要求

- 熟悉阿里云平台以及数+ maxcompute
- 平均 issue 回复时间 30 分钟以内
- 仔细了解 https://github.com/sibbay-ai/public 的内容
- 试用下面小程序后说明胜任原因
  ![image](https://user-images.githubusercontent.com/322486/34093474-5f70c4e0-e403-11e7-8d40-fc32c11ac3d7.png)
  暗号：小白健康日记

#### 3.2、相关规范

gitflow：https://shimo.im/doc/ShtjuiNXqEIF10MV

### 4、费用

1000 （理解需求后按实际承诺工作量计算）

### 5、协作工具

- zoom: https://zoom.us/
- 石墨文档: https://shimo.im/
- github: https://github.com/
- 阿里云账号
- 微信

**Comment by ben7th** [comment]
@georgeliuyu 是否可直接以 issue 链接进行发包？还需要写石墨文档吗？

**Comment by georgeliuyu** [comment]
@ben7th 你建议好，可以以issue直接发包，但要增加原来模板中的内容。

**Comment by ben7th** [comment]
@georgeliuyu 已补充内容并发审批

**Comment by chencang** [comment]
看下
- 数据库设计
- 数据统计指标要求

**Comment by ben7th** [comment]
@chencang 统计指标要求见
https://github.com/sibbay-ai/data-maxcompute-stat
