### ISSUE TITLE
快速迭代的制度建立

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#584]
经过近两年的开发，小白健康的基本功能已经具备，同时也有了一定的用户群体，为了推动小白健康的快速迭代，以适应用户的需求，需要建立相应的制度保障，建议：
-  分级响应机制：对于在feedback中提交的issue（bug和改进）时间承诺：
A：24小时响应：紧急事件、显示错误、不需要产品参与简单的优化等
B：72小时响应：明确看重现的问题、需要产品简单调整的优化等
C：7天响应：较复杂的bug、非新功能但需要产品设计的优化等
分级响应的级别确认和修复指派有feedback的负责人进行，且修复issue有应用bug或改进issue
- 确认机制：
A：bug和优化的用户或者贡献者对结果进行确认
B：确认方式可以是issue上的留言，或者聊天截图
C：确认的负责人是修复者
reviewer要确保物存在
- 发现问题奖励
对于较bug和优化建议的用户或者贡献者，每个被修复的bug或优化，均给予100 SHT的奖励，不进入icp统计和评分。标记由修复者打

@ben7th @zhaobinglong 阅读后、组织讨论。我参加
@sibbay-ai/all

**Comment by zhaobinglong** [comment]
收到

**Comment by ben7th** [comment]
@zhaobinglong 的建议

我想补充一条：A级bug修复后，找反馈者确认后，可迅速上线。不用经过产品确认的流程，涉及到产品的变化，就必须经过产品的确认

**Comment by ben7th** [comment]
@Yidadaa 的建议

我前两天搜集了一下关于小程序用户反馈的工具：
1. 小程序内置了一个用户反馈渠道，小程序论坛的讨论见这里：https://developers.weixin.qq.com/community/develop/doc/00044c6e6841e8a8ade6d6d7d51c00 ，用户反馈后开发者可以在后台查看到，使用方法见我刚刚录制的视频；
2. 腾讯开发了一款小程序插件，名字叫做“吐个槽”，主打一行代码就可以快速让小程序拥有一个专属用户反馈社区，官方介绍见：https://mp.weixin.qq.com/wxopen/plugindevdoc?appid=wx8abaf00ee8c3202e&token=&lang=zh_CN ，使用介绍可以见我刚刚录制的视频。

**Comment by ben7th** [comment]
@zhaobinglong 

我认为：当我们在feedback中收到一个问题，同一时间只给一个人解决，比如说，拿到一个问题，大家都以为是前端问题，这个时候就指派给我，我去解决，那么这个问题就是我负责，在这个过程中，我可能会去找后端协助，但是负责人还是我。如果我在解决过程中，最终发现是后端接口出了问题，那我就指派给后端，这个时候后端就是负责人，最后跟用户确认的也是后端

**Comment by ben7th** [comment]
@nancy919 

问题的严重程度/波及面和技术上的解决/实现难度是分开的维度

**Comment by nullscc** [comment]
对于分级的，我觉得可以单纯从用户感知的层面来判断，比如对于A、B、C三级：
* A级，非常影响用户使用的，会导致用户会反感我们产品的
* B级，出现的问题或需要优化的功能在比较短时间内能收获到用户好感的
* C级，正常功能调整

对于A级，有可能有需要一分为二，比如这个A级bug很复杂，但是完全解决需要很长时间，可以将这个bug分为一个A级和一个B级；
分开的A级表示比较简单粗暴，但是能快速解决问题的；分开的B级表示可以治本的方案

当出现分级冲突时，我觉得可以依产品和运营情况而定，也就是离最终用户最近的有权利拍板这个是什么等级的；应该给离用户最近的一方提供快速而强大的支撑

**Comment by zhaobinglong** [comment]
关于奖励机制：

我很赞同 @ben7th 提的想法，当我们的用户在任何渠道给我们反馈一个bug时，收到这个反馈的社区工作人员快速把它记录进入feedback，产品和开发跟进，确定紧急程度，指派开发者，直到问题解决

当问题解决后，得到用户的确认，我们通过小白小程序给用户发一个微信卡片，用户点开该卡片，可以看到自己反馈的问题和可以得到的生命力奖励，用户点击确认领取，OK，这个奖励进入了用户的生命力历史中，同时，我们在社区每月的公众号推文中，再次书面对用户的反馈标识感谢

为了在生命里历史中显示这个奖励，小白可以增加一种生命力类型，就叫【帮助小白成长】显示在用户的生命力列表

这样，整个反馈的流程从提出，解决到奖励，整个环节就完毕了

@georgeliuyu @ben7th
