### ISSUE TITLE
2019年2月 token贡献奖励数量：25万SHT

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#585]
鉴于春节的推广活动：牵金猪中的突出表现：
- 新增用户超过2k+
- 日活200+
- 用户开始频繁的发送牵金猪的卡片

为鼓励社区在这次活动的设计和实施中卓有成效的工作，本月的token贡献奖励为25万个SHT

谢谢大家！ 祝元宵节快乐

刘宇

**Comment by georgeliuyu** [comment]
@Jessica124 @ben7th @fushang318

**Comment by fushang318** [comment]
收到

**Comment by Jessica124** [comment]
@ben7th @fushang318 @zhaobinglong @bqx619 @nullscc @maohuaming 奖励的Token已发放，请各位注意查收，谢谢
