### ISSUE TITLE
申请成为小白众和社区贡献者

### ISSUE THREAD

**Issue by zibber2015** [sibbay-ai/public#589]
个人简介：工作3年半,工作以php为主,会python,用python写过爬虫,后面会慢慢熟悉
熟悉mysql,redis,
熟悉ansible,elk等运维工具
有微信/支付宝/小程序/app开发经验,做过长连接通讯
希望成为社区一员,共同努力

**Comment by zibber2015** [comment]
我的联系方式 微信/手机号 18902464056

**Comment by ben7th** [comment]
@zibber2015 欢迎 🎉🎉🎉

我是开发者社区的技术负责人

建议可先阅读 https://github.com/sibbay-ai/public 的 README 来了解社区规则 🙂
稍后我会通过微信和你联系
