### ISSUE TITLE
mri仿真UI 颜色调整

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#59]
![image](https://user-images.githubusercontent.com/16983441/34140279-9484bf18-e4b4-11e7-92e7-aeb323ca73ce.png)

调整为下面这个颜色：
![image](https://user-images.githubusercontent.com/16983441/34140366-1e683430-e4b5-11e7-9b5e-bcddbc9be210.png)

**Comment by NiuShy** [comment]
@georgeliuyu 已修改&合并

**Comment by fushang318** [comment]
@georgeliuyu 单独发的这个ISSUE算什么类型的ISSUE，review 吗，是否需要关联到 reivew 的 issue

**Comment by georgeliuyu** [comment]
@fushang318  嗯，同意。下面你定

**Comment by fushang318** [comment]
来自 https://github.com/sibbay-ai/public/issues/57
