### ISSUE TITLE
@Nancy919 2019-02-16 ICP  补充申请

### ISSUE THREAD

**Issue by nancy919** [sibbay-ai/public#593]
# Nancy919 2019-02-16 ICP 补充申请

### 类别：运营工作

| issue | pr | size |
| --- | --- | --- |
| https://github.com/sibbay-ai/cooperation-issues/issues/1648 视频教程-血压 | sibbay-ai/cooperation-issues/pull/1649) | 0.5 |
| https://github.com/sibbay-ai/cooperation-issues/issues/1646 视频教程-体重 | https://github.com/sibbay-ai/cooperation-issues/pull/1647 | 0.5 |
| https://github.com/sibbay-ai/cooperation-issues/issues/1644 视频教程-记录存档 | https://github.com/sibbay-ai/cooperation-issues/pull/1645 | 0.5 |
| https://github.com/sibbay-ai/cooperation-issues/issues/1642 视频教程-医学指标 | https://github.com/sibbay-ai/cooperation-issues/pull/1643 | 0.5 |
| https://github.com/sibbay-ai/cooperation-issues/issues/1640 视频教程-用药 | https://github.com/sibbay-ai/cooperation-issues/pull/1641 | 0.5 |
| https://github.com/sibbay-ai/cooperation-issues/issues/1638 视频教程-症状 | https://github.com/sibbay-ai/cooperation-issues/pull/1639 | 0.5 |
| https://github.com/sibbay-ai/cooperation-issues/issues/1636 视频教程-疾病 | https://github.com/sibbay-ai/cooperation-issues/pull/1637 | 0.5 |
| https://github.com/sibbay-ai/cooperation-issues/issues/1609 策划及设计春节期间推广活动方案 | https://github.com/sibbay-ai/cooperation-issues/pull/1611 | 3 |
| https://github.com/sibbay-ai/cooperation-issues/issues/1610 春节期间「送祝福，牵金猪」前端展示页面 | https://github.com/sibbay-ai/cooperation-issues/pull/1612 | 3 |
| https://github.com/sibbay-ai/cooperation-issues/issues/1613 撰写《牵金猪PRD需求文档》 | https://github.com/sibbay-ai/cooperation-issues/pull/1614 | 2 |

| 总计 |  | 11.5 |

**Comment by nancy919** [comment]
本月补充申请 size
本月补充申请 SIZE：11.5

请 @fushang318 @sinchb @georgeliuyu 审核

**Comment by georgeliuyu** [comment]
这个流程可先按照：committer审核、人事财务审核、然后我批准。 @ben7th 你确认一下是否与上次的issue情况一样。

**Comment by ben7th** [comment]
@nancy919 已知晓，将对上述 issue 和工作内容进行审核

**Comment by ben7th** [comment]
committer - @ben7th 审核结果：

此次补充申请包括运营及策划工作，提交时间均为 2019-02-15 之前；
因标签疏漏导致未及时统计；

工作内容大致如下：
- 7 个视频教程的制作工作，共计 3.5 size
- 春节贺年牵金猪活动的策划方案编写，交互设计，美术设计，共计 8 size

以上共计 11.5 size 有效

**Comment by fushang318** [comment]
我来进行数据迁移，让这些 ISSUE 进入 20190315 的周期内

**Comment by fushang318** [comment]
已经迁移

迁移前
![image](https://user-images.githubusercontent.com/326242/54407670-ae90f200-4719-11e9-9d53-0c9dadeb9d15.png)


迁移后
![image](https://user-images.githubusercontent.com/326242/54407681-bc467780-4719-11e9-8f17-e33b1a39e105.png)

**Comment by georgeliuyu** [comment]
以后这样的补发申请，原则社区是不支持的，仅仅特殊情况可以，由committer先进行标准的icp流程。然后又 @Jessica124 审批确认后由 @fushang318 更具情况计入在当月或者下月统计（可以拆分）。
