### ISSUE TITLE
@bqx619 2019-04 ICP 补充申请

### ISSUE THREAD

**Issue by bqx619** [sibbay-ai/public#611]
# bqx619 2019-04 ICP 补充申请

### 类别：统计回馈 Mlang 开发工作

| issue | pr | size |
| --- | --- | --- |
| https://github.com/sibbay-ai/sr-wiki/issues/626 回馈统计的 MRI-MRI 接口开发 - 治疗/用药/疾病 | https://github.com/sibbay-ai/mri-mri/pull/250 </br> https://github.com/sibbay-ai/sr-models/pull/306 | 2.5 |
| https://github.com/sibbay-ai/sr-wiki/issues/625 回馈统计的 MRI-MRI 接口开发 - 症状/体重/步数 | https://github.com/sibbay-ai/mri-mri/pull/250 </br> https://github.com/sibbay-ai/sr-models/pull/306 | 2.5 |
| 总计 |  | 5.0 |

**Comment by bqx619** [comment]
- 原因: 因 2019-04 月, 自身身体情况不允许, 导致在 2019-04-15 之前无法将这两个 icp issue 正确的标签, 同时这两个 issue 的工作 PR 已经合并, 导致这两个 issue 无法别 icp 系统识别. 故在此申请补充这两个 icp issue
- 共计 size: 5.0
- 请 @fushang318 @ben7th  @georgeliuyu @Jessica124 审核

**Comment by georgeliuyu** [comment]
这个由 @Jessica124 负责审核

**Comment by georgeliuyu** [comment]
@bqx619 这事情直接找 @ben7th 和 @Jessica124 ，可以不用@我

**Comment by bqx619** [comment]
收到

**Comment by fushang318** [comment]
已经处理好
![image](https://user-images.githubusercontent.com/326242/59545040-61583280-8f4b-11e9-83ad-c499fb837660.png)
