### ISSUE TITLE
mri-mri 代码阅读和做一个简单的功能实现

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#62]
### 1、目标

阅读采用python实现DSL（领域专用语言）系统mri，代码量2k+

#### 1.1、选型/环境

- python 3.6  +mongodb +redis

#### 1.2、文档

- 写一篇程序结构文档

#### 1.3、开发

- 实现 https://github.com/sibbay-ai/public/issues/26 的要求

#### 2.1、阶段和验收

周期：7 天（明确需求后，以开发者承诺为准）

#### 2.2、调整和处罚（码市）

- 可以进行一次时间调整申请，最长不超过 2 天。
- 未申请或已经有过调整的，每延期一天按项目金额的 10% 进行罚款。
- 超过 5 天，需求方有权取消项目。
- 需求方原因造成的延误不包含在内。

#### 3.1、人员要求

- 熟悉熟悉python、mongodb、redis等，有很好的规范执行习惯
- 接受小白的众和模式和icp流程，请仔细阅读https://github.com/sibbay-ai/public 的内容
- 有时间
- 试用下面小程序后说明胜任原因
  ![image](https://user-images.githubusercontent.com/322486/34093474-5f70c4e0-e403-11e7-8d40-fc32c11ac3d7.png)
  暗号：小白健康日记

#### 3.2、相关规范

gitflow：https://shimo.im/doc/ShtjuiNXqEIF10MV

### 4、费用

1000 （理解需求后按实际承诺工作量计算）

### 5、协作工具

- zoom: https://zoom.us/
- 石墨文档: https://shimo.im/
- github: https://github.com/
- 阿里云账号
- 微信

**Comment by ax003d** [comment]
@georgeliuyu 这个我来做吧

**Comment by Mengjianhua-c** [comment]
@georgeliuyu 
1、我简单了解了下Python实现dsl的pyparsing库，请问你们的这套dsl是否也是依赖这个库？我阅读了几篇官方提供的demo，比如解析sql语句的，提取sql语句中表名和列名；将特定时间语法比如today转换为Python的datetime；提交的程序结构文档有没有什么具体要求的清单，感觉这个描述也不太具体
2、另外，开发 #26 这个描述的太简单了，能简单说下，要用什么语言实现，是在现有的代码中新增功能？

**Comment by georgeliuyu** [comment]
@Mengjianhua-c 
我们没有用pyparsing，而是直接采用python语法作为mlang，同时用结构化的json作为互动的单元。
因为不是开源项目所以不方便直接给你看代码，能私信一下你的情况吗？ 我的微信是：liuyugeorge
不过有两份文档你可以看看：  
https://shimo.im/doc/6B0RBuihZq8zTLMl  
https://shimo.im/doc/t9y37ed4Uv0WQV9z

**Comment by Mengjianhua-c** [comment]
@georgeliuyu 好的，我对DSL这方面的专业技术不是太了解，文档我先看看了解下，私信已发验证是‘我是孟’

**Comment by haoshijing** [comment]
请问该功能已经实现了吗

**Comment by fushang318** [comment]
@haoshijing   
已经实现了，这个任务是一个熟悉现有系统的任务，目的是熟悉后参与后续开发  
你有兴趣参与这个项目的开发吗？

**Comment by haoshijing** [comment]
可以的啊



在 2018-02-22 09:54:52，"fushang318" <notifications@github.com> 写道：


@haoshijing
已经实现了，这个任务是一个熟悉现有系统的任务，目的是熟悉后参与后续开发
你有兴趣参与这个项目的开发吗？

**Comment by georgeliuyu** [comment]
@haoshijing 可发简历到微信:18017921481
