### ISSUE TITLE
贡献者认证流程.md 里头有一个链接错了

### ISSUE THREAD

**Issue by Yijia-Zhou** [sibbay-ai/public#621]
规则二文档链接第一条
`[ICP入门FAQ文档链接](https://github.com/sibbay-ai/public/blob/master/icp入门FAQ.md)`
这里的链接点开显示404页面，实际应该是
`https://github.com/sibbay-ai/public/blob/master/icp%20FAQ.md` 吧？
不知道在public这里修bug要不要走ICP标准流程O(∩_∩)O

**Comment by Yijia-Zhou** [comment]
还有《ICP奖励机制文档链接》等几个链接也挂掉了……
@georgeliuyu @maohuaming 
顺便问一下现在还有法定工作日每早9点的早会吗？连着几次想要观摩都一直是显示等待会议开始。我用 Python 作后台写过两个小网站，独立开发过一个微信小程序，想多了解一下小白社区的工作状态～

**Comment by georgeliuyu** [comment]
你好，请加我的微信号：18017921481


------------------
Best Regards,
georgeCEO

&nbsp; &nbsp; &nbsp; I want some day &nbsp;You join us

上海尘微科技有限公司
Shanghai sibbay technology Co., Ltd.

+86 18017921481/13501942655 &nbsp;Mob.





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yijia-Zhou"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月15日(星期二) 晚上9:21
收件人:&nbsp;"sibbay-ai/public"<public@noreply.github.com&gt;;
抄送:&nbsp;"georgeliuyu"<georgeliuyu@gmail.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [sibbay-ai/public] 贡献者认证流程.md 里头有一个链接错了 (#621)




还有《ICP奖励机制文档链接》等几个链接也挂掉了……
 @georgeliuyu @maohuaming
 顺便问一下现在还有法定工作日每早9点的早会吗？连着几次想要观摩都一直是显示等待会议开始。我用 Python 作后台写过两个小网站，独立开发过一个微信小程序，想多了解一下小白社区的工作状态～
