### ISSUE TITLE
@ben7th 的请假告知

### ISSUE THREAD

**Issue by ben7th** [sibbay-ai/public#622]
因 2019 年 10 月 16-22 号参与一线下嘉年华活动，个人负责提供网络直播和现场互动技术支持
在此期间请假，具体说明如下：

- 14 号开始会保持在线，但不易实时响应，也不易处理新增的开发工作
- 16 号交通前往杭州，当天不在线
- 17-21 号不能保证在线响应，信息可以发给我，会非实时回复
- 计划 22 号返回，此后恢复工作响应

对此前已安排工作的处理

- 目前正在修改的 BUG, 记录图片显示等问题会在 14 号前合并提交小程序版本
- 原定于下周要进行的 vscode 分享和代码重构方法论分享可以参加，但需提前确定时间，或把代码重构方法论分享延后
- 15 号会集中处理 ICP 标记工作，建议在 14 号或之前把需要标记的清单发给我 @nancy919 @zhaobinglong

**Comment by zhaobinglong** [comment]
收到👌

**Comment by nancy919** [comment]
收到

**Comment by georgeliuyu** [comment]
了解
