### ISSUE TITLE
小白贡献者节互相介绍环节安排和圆桌环节问题征集

### ISSUE THREAD

**Issue by ben7th** [sibbay-ai/public#625]
11 月 25 日小白将举办贡献者节活动，现对活动的以下两个环节进行安排准备：

- 互相介绍环节：每个与会参与者介绍另一名参与者
- 圆桌环节：贡献者讲话环节进行完后，将安排圆桌环节，进行一些问题的回复和交流

**Comment by ben7th** [comment]
互相介绍环节安排：

以下与会者会进行互相介绍：

@fushang318 - 李飞
@ben7th - 宋亮
@nancy919 - 南希
@zhaobinglong - 赵冰龙
@bqx619 - 吴善超
@aixinhuang - 黄老师
@pimgeek - 吴笛

每个与会者简短介绍另一人，在本周五前通过沟通，确定好由谁介绍谁；介绍人确定后，介绍内容可以各自沟通；

**Comment by ben7th** [comment]
圆桌环节安排：

可以预先收集一些社区成员或想了解社区的其他人可能关心的问题或议论点，在贡献者节当天，各自发言环节完毕后，选择一些来提问和讨论。可以把建议的问题回复到这个 issue

**Comment by fushang318** [comment]
按照 icpper 编号来就挺好

**Comment by zhaobinglong** [comment]
跟随社区安排，没有特别要求

**Comment by sinchb** [comment]
介绍之间需要一个环吗，不然会出现， 1个人介绍了其他所有人的情况

**Comment by pimgeek** [comment]
我想介绍 @ben7th (๑•̀ㅂ•́)و✧

**Comment by bqx619** [comment]
跟随社区安排，没有特别要求

**Comment by ben7th** [comment]
根据微信丢骰子确定了介绍顺序，规则如下：

1. 每个人通过微信表情丢一次骰子，丢出 1-6 的数字
2. 按照每个人丢出来的数字，由小到大排列。如果数字一样，按照贡献者编号从小到大排列
3. 排列好后，后一个人介绍前一个人，第一个人介绍最后一个人

----

排序结果：

"NO-2: 宋亮" - 1 点
"NO-8: 吴笛" - 1 点
"NO-30: 南希" - 1 点
"NO-1: 陈斌" - 3 点
"NO-21: 黄爱欣" - 3 点
"NO-16: 吴善超" - 4 点
"NO-25: 赵冰龙" - 5 点
"NO-3: 李飞" - 6 点

----

介绍顺序

宋亮 简介 李飞
吴笛 简介宋亮
南希 简介吴笛
陈斌 简介南希
黄老师 简介陈斌
吴善超 简介 黄老师
赵冰龙 简介 吴善超
李飞 简介 赵冰龙
