### ISSUE TITLE
关于建立mentor制度的征求意见

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#628]
为了推进社区治理的进一步深化，提出mentor（导师）制进行讨论。
目的：
- 关心：关心每一个方面，缩短贡献者的距离，增加归属感
- 促进：严格要求，建立制度化的促进体系
具体规则：
- 每个人都有且仅有一个mentor
- mentor的关系必须得到双方的认可
大家可以给出的建议点：
- 以什么机制确定关系
- 关心和促进如何落地的具体规则：规则之一是”无“

@sibbay-ai/all

**Comment by bqx619** [comment]
### 以什么机制确定关系

1. 现有人员关系的确定, 建议可以先每个人盲选自己的 mentor 和 mentee, 我觉得, 很可能会产生有趣的结果;
2. 之后新人员关系的确定, 可以是: mentee 自己找和 mentor 主动要相结合.


### 关心和促进如何落地的具体规则

1. 每周一, mentor 做 mentee 的工作汇报
2. 每月的 sht 奖励, 可以加一个系数, 可能是: (mentee 的 ei - 0.8 + 1) * mentor 的 ei

**Comment by pimgeek** [comment]
## 关于 mentor 制度落地的想法

也许应该围绕小白产品的某个具体功能特性 / 使用体验 / 研发流程 / 工作方法等展开 mentor / mentee 的互动，避免发散到别处。

这个思考点，是今天临时想到的，因为这两天一直在做网站客服工作。发现客户发产品界面截图过来的时候，自己会高度关注，很容易发现截图中的错漏之处；而自己平时观察产品界面时，容易漫不经心就看过去，或者几乎完全忽略某些细节。

![image](https://user-images.githubusercontent.com/1609306/69796406-f6549c80-1208-11ea-996f-3aae3cd17f39.png)

这个图是修改过的，仅仅用来表达一种自己平时 “熟视无睹”，客户发截图时 “突然兴奋” 的反差。

**Comment by georgeliuyu** [comment]
> ### 以什么机制确定关系
> 1. 现有人员关系的确定, 建议可以先每个人盲选自己的 mentor 和 mentee, 我觉得, 很可能会产生有趣的结果;
> 2. 之后新人员关系的确定, 可以是: mentee 自己找和 mentor 主动要相结合.
> 
> ### 关心和促进如何落地的具体规则
> 1. 每周一, mentor 做 mentee 的工作汇报
> 2. 每月的 sht 奖励, 可以加一个系数, 可能是: (mentee 的 ei - 0.8 + 1) * mentor 的 ei

有创造力的想法

**Comment by georgeliuyu** [comment]
@pimgeek 你的意思是不同的领域有不同的mentor吗？

**Comment by pimgeek** [comment]
> @pimgeek 你的意思是不同的领域有不同的mentor吗？

我考虑得不够清晰，不同领域有不同 Mentor 看上去是比较合理的，不过通常这种领域标签是大家在日常沟通中逐渐形成的印象，而不是通过认领/分配的方式。我目前考虑的主要是 Mentor 制度刚刚启动时的 Bootstrap 过程，或许可以从互相求问开始。 😄
