### ISSUE TITLE
关于探索mentor与icp制度的结合尝试

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#629]
@bqx619 作为 @Yijia-Zhou 的mentor，先进行一下尝试安排：
-  @bqx619 负责对@yijia-zhou的issue进行icp的标注（icp和size）等。
- 探索实现原来的deadline方式。

@fushang318 进行相关的icp后台处理的修改
@bqx619 注意进行，严格要求，特别是review

**Comment by bqx619** [comment]
收到
