### ISSUE TITLE
搭建适用的远程办公环境的设备推荐

### ISSUE THREAD

**Issue by ben7th** [sibbay-ai/public#631]
# 搭建适用的远程办公环境的设备推荐

![image](https://user-images.githubusercontent.com/322486/70202456-b3d51780-1754-11ea-8d22-fc211611bb4b.png)

- ## 一些基本考虑因素
  
  - 如果笔记本本身有摄像头，且能正常工作，可不另买摄像头，只买耳麦；
  - 如果笔记本外接了键盘，会合上工作，需要另配摄像头；
  - 远程工作时不推荐使用声音外放（包括笔记本的外放和音箱等）。外放会导致在远程通话中产生回授音，也就是常说的啸叫（外放声音进入麦克风，再次被外放播出，形成循环导致声波叠加）。**一些质量好的笔记本电脑对其本身的声音外放做了处理，使得不会产生啸叫。应具体自行测试。**
  - 有固定办公位置时，推荐使用多屏幕工作。外出办公时，也可采用便携屏幕。

-------  

- ## 摄像头
  
  由于我们经常开视频会议 (zoom, talkline), 因此需要一个好的摄像头和麦克风。  
  
  摄像头推荐：罗技(logitech) C920  
  简介：罗技作为大外设品牌，在全国有很多的销售商和维修点。这款 C920 摄像头有不错的成像质量，自动调整曝光，焦距等功能。而且摄像头上自带一个降噪麦克风。如果办公场合周围的环境背景音不是很大，这款摄像头的麦克风就比较好用了。  

  [罗技(logitech) C920 摄像头购买链接](https://item.taobao.com/item.htm?spm=a230r.1.14.69.1ac953fbsQIwu1&id=562003013053&ns=1&abbucket=16#detail)  279 元  

  大家可以去这个购买链接(天猫)购买，也可以自己去京东，拼多多等其他网站搜索购买。  
  摄像头一般会和三脚架搭配售卖，三脚架不贵，推荐顺便买一个。注意，三脚架的脚应该要能伸缩。

-------

- ## 耳麦

  如果你所在的工作环境，经常是背景音比较大，比较嘈杂，建议使用耳麦；需要注意的是，耳麦不能太劣质，需要满足基本的质量要求，否则会有大量的线路电流等问题；  
  耳麦的选择比较多，这里随意推荐几款耳塞式的：  

  [小米双单元半入耳耳机 购买链接](https://detail.tmall.com/item.htm?spm=a220m.1000858.1000725.1.73ec5078bW6jXr&id=566278721761&skuId=3760827858192&areaId=440100&user_id=1714128138&cat_id=2&is_b=1&rn=9a978fe8b20516b44215c5face8e9727) 69 元  
  [小米铁圈耳机2 购买链接](https://detail.tmall.com/item.htm?spm=a230r.1.14.16.43a83c64M058FT&id=522888046074&ns=1&abbucket=16)  99 元  

  如果你需要更安静的环境，也可以用头戴式的耳机，例如：  
  [小米头戴式有线K歌耳机](https://detail.tmall.com/item.htm?spm=a1z10.3-b-s.w4011-14756119800.107.1eb948feciInha&id=588003714797&rn=85da0bebc0cadeedaca85417207efca4&abbucket=20)  169 元  

  如果要用无线蓝牙耳机，推荐用贵一些的，不推荐很便宜的蓝牙耳机。原因是蓝牙的频段和 2.4G 的 wifi 会有冲突，在户外公共场所存在大量 wifi 信号的情况下，质量不好的蓝牙耳机经常会断连，或出现信号传输问题，导致收听和说话声音断续。这里就不具体推荐了。  

-------

- ## 便携显示器

  便携显示器无论是固定场所办公还是外出办公都非常实用，有利于灵活地扩展笔记本屏幕。  

  便携显示器有很多品牌，基本上是深圳的液晶屏厂产的，其中很多是大品牌的供应商，贴了自己的牌子。  

  我目前使用的是这个品牌的便携显示器：  
  [便携显示器 网店链接](https://junxuandiy.taobao.com/index.htm?spm=2013.1.w5002-2170704844.2.d4f260473zNNiQ)  

  根据显示器参数，是否有电池，是否支持触摸（一般只有 win10 系统支持触摸，需要问清楚），是否支持 HDR 等，会有不同的价格。可以按自己的实际需要购买和咨询客服。  

  建议可搭配皮套外设，便于携带。  

-------

- ## 显示器支架

  如果用非便携的液晶显示器作为扩展屏幕，可使用显示器支架。目前比较好的新款支架都是气压弹簧设计，可在活动性和固定性上取得比较好的平衡。

  我目前用的是这个品牌：  
  [显示器支架 购买链接](https://detail.tmall.com/item.htm?id=38400144605&spm=a1z09.2.0.0.42ce2e8dIPrDOs&_u=51psabp428f)  

  大家可根据自己的显示器尺寸，放置支架的桌子来进行选择。  

-------

- ## 笔记本扩展坞和一些小外设

  MACBOOK 或者其他有 typec 口的笔记本，平板，可能需要通过扩展坞连接外接显示器，网线，读 sd 卡，USB 设备等，有一个扩展坞会比较方便。

  推荐“绿联”品牌。虽然比别的品牌贵一些，但综合下来是质量最过硬的。

  [绿联网店 扩展坞](https://greenconnection.tmall.com/?q=%C0%A9%D5%B9&type=p&search=y&newHeader_b=s_from&searcy_type=item&from=.shop.pc_2_searchbutton&spm=a1z10.1-b-s.a2227oh.d101)  
  有不少东西，可以按照需求自己选购

-------

- ## 连接线

  一般是网线，HDMI 线，typeC 线和 USB 线用得最多，也推荐在绿联购买。可以在买其他外设时顺便买。

  [绿联网店 线材](https://greenconnection.tmall.com/?q=%CF%DF&type=p&search=y&newHeader_b=s_from&searcy_type=item&from=.shop.pc_2_searchbutton&spm=a1z10.3-b-s.a2227oh.d101)

-------

- ## 收纳

  经常外出的话，需要收纳摄像头，各种连接线，充电器，鼠标，耳麦等，需要比较好的收纳。

  数码产品收纳品牌推荐 BUBM-必优美  
  [BUBM 旗舰店](https://store.taobao.com/shop/view_shop.htm?spm=a230r.1.14.5.6c7d51bcOvMFqw&user_number_id=2780330469)  
  可按自己的需求选购。

**Comment by georgeliuyu** [comment]
![image](https://user-images.githubusercontent.com/16983441/70207581-28648200-1766-11ea-8476-3f828999964e.png)

**Comment by ben7th** [comment]
申请开发 deadline: 2019-12-15
