### ISSUE TITLE
关于提高远程办公室质量的通知

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#632]
CPL贡献者！
小白健康一直在探索新的组织协作方式，而视频办公这是这其中一个重要部分，特别是在通过这次贡献者日的交流，我们发现：在线视频能有效拉近协作者之间的心理距离，同时根据[《众和社区贡献者分级（CPL）规范》](https://github.com/sibbay-ai/public/blob/master/docs/%E8%B4%A1%E7%8C%AE%E8%80%85%E5%8F%82%E4%B8%8E%E5%BA%A6%E8%AF%84%E7%BA%A7%E4%BD%93%E7%B3%BB.md)中的要求，特发送本通知。
另外考虑到设备对远程视频办公质量的影响，@ben7th 同学给出了设备清单： https://github.com/sibbay-ai/public/issues/631 大家可以参考，有经济困难的可以向社区提出资助申请。
同时如果有条件的化，可以优化一下背景，例如粘贴一些绘画，让大家能赏心悦目^-^。
检查时间：12月16日早上9:00-12:00
检查方式：每个人在这个issue下回复，对一个需要整改的同学给出建议。
同时作为mentor的一个提醒内容。
                                           
@sibbay-ai/all_read

**Comment by ben7th** [comment]
提一个公共建议：不说话时，主动关闭 MIC，减少对他人的影响

![image](https://user-images.githubusercontent.com/322486/70588906-30f70580-1c09-11ea-860f-3c4bbc7ac28b.png)
