### ISSUE TITLE
关于mentor确定通知（试点）

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#633]
经过一段时间的意见征求（见 ：https://github.com/sibbay-ai/public/issues/628）现确定开始试行：
1、每个人通过微信私信发给我你希望的mentor（可以多人）
2、每个人通过微信私信发给我你同意接受的mentee（可以多人）
然后由我，进行配对后公布。
截止时间：
12月12日12：00
@sibbay-ai/all
本次涉及人员： @ben7th @fushang318 @nancy919 @bqx619 @zhaobinglong  @yijia-zhou
其中@yijia-zhou 已经有mentor，但是可以成为别人的mentor

**Comment by ben7th** [comment]
👌

**Comment by zhaobinglong** [comment]
收到

**Comment by bqx619** [comment]
收到

**Comment by georgeliuyu** [comment]
结果公布：
南希的mentor：李飞
吴善超的mentor：李飞
李飞的mentor：刘宇
宋亮的mentor：南希
赵冰龙的mentor：宋亮
刘宇的mentor：宋亮
周熠家的mentor：吴善超

**Comment by ben7th** [comment]
👌
