### ISSUE TITLE
小白健康NLU意图测试的比赛

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#634]
为实现以意图为核心的CUI设计探索，现举行UNIT的测试比赛，其规则如下：
提交物：
- 一份意图列表；
- 每个意图一个测试例句集；
- UNIT的二位码
比赛方式，分两个阶段：
第一阶段：
- 12月13日下午5:00前，提交意图集和UNIT二维码，发到站会群，欢迎围观
第二阶段
- 12月16日10:00前，提交测试集（可以扩充意图集）
- 10点开始测试，11:00出结果
测试和评分
- 参赛人：@nancy919（A) @bqx619（B) 小周C
- 采取类似EI的方式打分，满分10，可以拆解，例如：A给B 3分，给C 7分
- 分数直接私信给我，并由我宣布比赛结果。

**Comment by Yijia-Zhou** [comment]
测试例句集大小有要求吗？ @georgeliuyu

**Comment by georgeliuyu** [comment]
评比结果：
吴善超：10
南希：6.8
周熠家:13.2
