### ISSUE TITLE
关于明确基于意图机制的目标明确

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#638]
根据上周的意图测试，请明确下一步引入意图机制实现的目标。
目标以**用户**使用的效果为描述方式。
12月17日上午讨论。
@sibbay-ai/all

**Comment by Yijia-Zhou** [comment]
我做这个东西过程中的想法大概是以下两点：
1. 尽量让用户不需要学习特定的说话方式，而是可以直接用平常口语化的方式说
2. 让这种对口语化表达的识别尽量覆盖整个 疾病/症状出现 -> 加重 -> 确诊 -> 接受治疗并缓解 -> 痊愈 的过程以及检查结果存档等需求

**Comment by bqx619** [comment]
已经开始第一阶段的规划开发: https://github.com/sibbay-ai/ir-wiki/issues/1
