### ISSUE TITLE
调查：icp pr 没有提交物代码

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#640]
https://github.com/sibbay-ai/mri-co-write/pull/114 这个pr没有实际的代码
![image](https://user-images.githubusercontent.com/16983441/71452669-e0170d80-27c1-11ea-815c-7cb1837395c9.png)

请 @ben7th 说明情况。

**Comment by ben7th** [comment]
说明：

- 由于在产生这个 pr 前，对 repo 划分没有沟通清楚，为了尽快开始工作，代码提交到了 sibbay-ai 外的 repo: https://github.com/duck-ai/duck-cui
- 在产生这个 pr 之后，经过沟通，采用 sibbay-ai fork 此 repo 代码的形式，来进行开发，并在此基础上区分属于开源部分和 sibbay-ai 业务支持部分代码的分别提交。目前 sibbay-ai 上 fork 的 repo 是：https://github.com/sibbay-ai/duck-cui
- 由于 pr 产生时在 sibbay-ai 下没有 commit，因此用当时 duck-cui 项目中的 README.md 粘贴到 https://github.com/sibbay-ai/mri-co-write (MRI 静态仿真和 JSON 生成项目) 中来作为 commit
- 现对 pr 中提到的 issue 和对应的 commit 关系整理如下：

|issue|title|commit|
|-|-|-|
https://github.com/sibbay-ai/mri-co-write/issues/115|实现 duck-cui 的代码 webpack 独立打包|https://github.com/duck-ai/duck-cui/commit/ae706b18338024628737387cb81cd1f466684e5e
https://github.com/sibbay-ai/mri-co-write/issues/116|设计 duck-cui 组件代码继承结构，并使用语法糖实现接口|https://github.com/duck-ai/duck-cui/commit/503f6dc38ba65b1acaa3035e3e77de6607ea85e9
https://github.com/sibbay-ai/mri-co-write/issues/117|实现 duck-cui 的 live Demo 的索引页面和内嵌在线示例|https://github.com/duck-ai/duck-cui/commit/f64f2143b4a818364dc9eb51d64f1ea55c48bc9f
https://github.com/sibbay-ai/mri-co-write/issues/118|实现（基于原 mri 仿真器代码提取重构）Loading, Text, MarkdownText, Image, Input 组件|https://github.com/duck-ai/duck-cui/commit/27548657d55fedc6e546240334234f762b82fb8a<br/>https://github.com/duck-ai/duck-cui/commit/cff1732f148fc9fb5b3d4122a87bade14e52ed51<br/>https://github.com/duck-ai/duck-cui/commit/c088a8dc185523e8ea0e328cb0b1a6a889bf1ab9<br/>https://github.com/duck-ai/duck-cui/commit/5b18483d9dfe70acdfe1a53280745d3d501ae609
https://github.com/sibbay-ai/mri-co-write/issues/119|实现 duck-cui 中的图标字体支持，适配 www.iconfont.cn 生成的图标包|https://github.com/duck-ai/duck-cui/commit/5b18483d9dfe70acdfe1a53280745d3d501ae609
https://github.com/sibbay-ai/mri-co-write/issues/110|基于和风天气 API 实现 duck-cui 的一个 api 调用 demo|https://github.com/duck-ai/duck-cui/commit/d2cd7c98f7815b195e742d7f7ad788d32112de8e

**Comment by georgeliuyu** [comment]
也就是说：在提交这个pr进行icp结算时，确实没有将工作成果代码提交到社区代码库。是吗？（回复：是，或者不是即可）

**Comment by ben7th** [comment]
是

**Comment by georgeliuyu** [comment]
从理论上来说：在提交这个icp pr进行结算时，成果代码的版权归属是你的个人repo，而不是社区。是吗？

**Comment by ben7th** [comment]
是

**Comment by georgeliuyu** [comment]
建议先由committer给出处理意见。 @fushang318 @ben7th @sinchb

**Comment by fushang318** [comment]
我的意见是，最好一开始就提交到  sibbay-ai
原因
目前状况下，如果最后完成后一把提交到社区会造成，但个月 SIZE 过多，影响投票

**Comment by ben7th** [comment]
- 目前实际 icp 执行过程中，一直存在没有在 repo 中有实质性 commit 的 pr. 这类 pr 的处理和认定需要有明确指导意见；
- 知识产权方面，对于此项目而言，理论上，属于支持 sibbay-ai 的部分，产权将来归属社区；不属于支持 sibbay-ai 的部分，产权将来归属个人；如何区分是否属于支持 sibbay-ai 的部分，则由协商给出
- commit 在有多个 fork 库的情况下，先提交到哪个 repo 是不可追溯的。https://github.com/sibbay-ai/duck-cui/commits/master 上显示的提交时间是当时该 commit 的提交时间，这些时间点与 commit 的对应在各个 repo 下是相同的，无法区分是先提交到哪个 repo 的。

综上，我的意见：
- 进一步明确各种 icp 工作提交的提交物规范
- 通过 repo 划分，在不同 repo 提交不同代码来决定版权归属。对于一时没有完成划分的，在将来划分后，决定版权归属。commit 至哪个 repo 是无法追溯的。

**Comment by ben7th** [comment]
> 我的意见是，最好一开始就提交到 sibbay-ai
> 原因
> 目前状况下，如果最后完成后一把提交到社区会造成，但个月 SIZE 过多，影响投票

pr 中的所有工作都是这个月的区间进行的。一开始提交和最后提交没有造成 size 差异。

**Comment by fushang318** [comment]
哦，我的意思是
如果按照原则 提交到个人库时，不能算 ICP SIZE 这个前提
那么在如下的场景下
1. 开始几个月不断的向个人库提交内容，这个时候是没有SIZE的
2. 在某一个月时，决定一把把前几个月的成果，一把从个人库提交到社区库
3. 那么这个月会直接把前几个月的工作直接换算成很多 ICP SIZE，相当于这个月核算了前几个月总共的工作，这样会造成 ICP SIZE 过大

**Comment by ben7th** [comment]
> 哦，我的意思是
> 如果按照原则 提交到个人库时，不能算 ICP SIZE 这个前提
> 那么在如下的场景下
> 
> 1. 开始几个月不断的向个人库提交内容，这个时候是没有SIZE的
> 2. 在某一个月时，决定一把把前几个月的成果，一把从个人库提交到社区库
> 3. 那么这个月会直接把前几个月的工作直接换算成很多 ICP SIZE，相当于这个月核算了前几个月总共的工作，这样会造成 ICP SIZE 过大

目前文档类，调研类，运维类，组织讨论/分享等工作都没有实质上对应的代码 commit. 是否要做出规范？
另外 commit 由于无法区分是何时提交到何 repo 的，唯一能追溯的就是 commit 的产生时间。目前我们只对 pr 和 issue 的时间因素做了约束，是否要对 commit 做时间约束？

**Comment by sinchb** [comment]
按照我的理解
1） 如果是归属社区的，那么repo一定需要在社区的repo中创建，或者最起码不是个人github账号下的public repo
2）我觉得调研类，运维类，组织讨论/分享等工作可以没有对应的代码（code），调研报告，运维记录等，都可以作为提交物
3）commit的唯一约束可能是  issue时间 < commit 时间 < pr 时间？

**Comment by georgeliuyu** [comment]
@王靖 请给出你的处理意见

**Comment by Jessica124** [comment]
刘总，就这件事，我的观点是：第一，我们的规则是有了成果才能算Size，然而现在没有成果，为什么会产生Size. 第二，宋亮既然作为社区的commiter，具有独立自主给自己打标签的权利，就更应该严格按照规则执行，他这样的做法违背了规则中给予大家的信任

**Comment by georgeliuyu** [comment]
@nancy919 @bqx619 @aixinhuang @Yijia-Zhou 你们都可以发表一下看法。

**Comment by bqx619** [comment]
我的个人意见是, 首先明确问题的定位.

- 如果这个 pr 只是没有提交代码入正确的库, 但实际上, 是有对应的工作, 可以认为是 pr 提交不够明确
- 那么不涉及到, "信任" or "没有成果"
- 同时这个 pr 对应的 icp issue **不是**没有或者无法找到相应的成果.

**Comment by Yijia-Zhou** [comment]
我看到 duck-cui repo 使用的是 MIT 协议，“被授权人有权利使用、复制、修改、合并、出版发行、散布、再授权及贩售软件及软件的副本”，那么版权归属的问题应该不会有什么实际影响？
并且在 sibbay-ai/duck-cui 的 README 中“开源方式的思考”部分有这样一段“fork 代码到 sibbay org，前期手动管理代码同步”，那么用于同步代码的 commit 和 pr 就可以作为宋亮的 ICP 提交物

**Comment by Yijia-Zhou** [comment]
我看到 [duck-cui repo](https://github.com/duck-ai/duck-cui) 使用的是 MIT 协议，“被授权人有权利使用、复制、修改、合并、出版发行、散布、再授权及贩售软件及软件的副本”，那么版权归属的问题应该不会有什么实际影响？

并且在 [sibbay-ai/duck-cui](https://github.com/sibbay-ai/duck-cui) 的 README 中“开源方式的思考”部分有这样一段
> fork 代码到 sibbay org，前期手动管理代码同步

那么用于同步代码的 commit 和 pr 就可以作为宋亮的 ICP 提交物

**Comment by nancy919** [comment]
我的看法：凡是能找到相应成果或记录的issue都算作有提交物，如：开会、运维、研究等这类没有实际提交物的，但可以追溯或有相关记录的都算。

**Comment by georgeliuyu** [comment]
> 我的个人意见是, 首先明确问题的定位.
> 
> * 如果这个 pr 只是没有提交代码入正确的库, 但实际上, 是有对应的工作, 可以认为是 pr 提交不够明确
> * 那么不涉及到, "信任" or "没有成果"
> * 同时这个 pr 对应的 icp issue **不是**没有或者无法找到相应的成果.

你看看具体pr和issue，并以你观点看看是哪种情况？如果没有权限 @fushang318 你做一个完整的截图。

**Comment by georgeliuyu** [comment]
> 我的看法：凡是能找到相应成果或记录的issue都算作有提交物，如：开会、运维、研究等这类没有实际提交物的，但可以追溯或有相关记录的都算。

@nancy919 你理解这个pr的提交物是什么？1、事情的说明；2、代码

**Comment by nancy919** [comment]
@georgeliuyu 

是的，
1. 事情的说明，必要时列出可证明的知情人；
2. 提交物，如：相关的代码、文档、录像、截图、链接等；

**Comment by bqx619** [comment]
@georgeliuyu 

我看了这个 pr, 以及这个 pr 对应的 issue 和 @ben7th 的说明 https://github.com/sibbay-ai/public/issues/640#issuecomment-568947844

我的意见是:

1. 这个 pr 的内容起码应该包括 https://github.com/sibbay-ai/public/issues/640#issuecomment-568947844 的内容, 所以我认为 pr 不够完整/明确成立
2. 这个 pr 对应的 issue, 可以找到成果代码, 以及对应的 commit (代码在: https://github.com/sibbay-ai/duck-cui)
3. 不考虑 @Yijia-Zhou 提到的版权问题的情况下, 也即是说认为 https://github.com/sibbay-ai/duck-cui 中的所有在 https://github.com/sibbay-ai/public/issues/640#issuecomment-568947844 中提到的 commit 都属于 sibbay 社区的情况下, 我认为这些 issue 不应该被认定为无提交物

因此, 我认为应明确 https://github.com/sibbay-ai/public/issues/640#issuecomment-568947844 提到的 commit 归属于 sibbay 社区, 则此事应认为 pr 不完整, 提交位置不严谨. 反之, 若这些代码无法被属于 sibbay 社区, 则结论亦反之.

**Comment by georgeliuyu** [comment]
> @georgeliuyu
> 
> 是的，
> 
> 1. 事情的说明，必要时列出可证明的知情人；
> 2. 提交物，如：相关的代码、文档、录像、截图、链接等；

我是说你选哪个？ @nancy919

**Comment by georgeliuyu** [comment]
@bqx619 请注意看 https://github.com/sibbay-ai/duck-cui 的创建时间

**Comment by bqx619** [comment]
@georgeliuyu 嗯, 刘总, 我注意到了, 在 https://github.com/sibbay-ai/public/issues/640#issuecomment-568947844 中提到的 commit 其实是提交到 https://github.com/duck-ai/duck-cui 的, 只是 fork 了一份而已. 

> 因此, 我认为应明确 #640 (comment) 提到的 commit 归属于 sibbay 社区, 则此事应认为 pr 不完整, 提交位置不严谨. 反之, 若这些代码无法被属于 sibbay 社区, 则结论亦反之.

所以我提到需要使用一种方法或者解释明确这些 commit 归属于 sibbay-ai 社区, 而不是 public 的.

**Comment by bqx619** [comment]
@georgeliuyu 

https://github.com/duck-ai/duck-cui 创建时间 (UTC) 为 2019-12-04T20:11:01Z
https://github.com/sibbay-ai/duck-cui 创建时间 (UTC) 为 2019-12-18T02:33:28Z

**Comment by georgeliuyu** [comment]
@ben7th 请明确
提交物是代码吗？（是，不是）
代码提交到社区的repo是否有存在客观困难？（存在，不存在）

**Comment by zhaobinglong** [comment]
按照小白社区的基石：

> issue就是一切

@ben7th 的这个issue，记录了他的工作，但是提交物没有在issue中，结果应当被视为不存在。

@ben7th 提及了这么做的原因，这个原因的确存在，但是在社区基石没有变更的情况下，我们还是应当按照社区的基石来操作，然后协调各位贡献者提出新的规则

这次的事件，可以作为一个规则说明的案例，加深各位贡献者和未来新加入贡献者对社区规则的理解

**Comment by ben7th** [comment]
> @ben7th 请明确
> 提交物是代码吗？（是，不是）
> 代码提交到社区的repo是否有存在客观困难？（存在，不存在）

- 提交物是代码
- 代码提交到社区的 repo 不存在客观困难。（需要先申请在社区创建 repo 但这不是客观困难）

**Comment by georgeliuyu** [comment]
@zhaobinglong 的建议很好，这次的事件作为规则的说明案例。我提几个问题给大家思考：
1、判断是否有提交物的依据是什么？
2、在判断过程中是否要将后补内容（如2楼的内容）列入考虑？
3、在判断过程中是否应该考虑主观因素？
4、在判断过程中是否应该考虑客观因素？
5、在判断过程中是否应该涉及对人的评判？

**Comment by fushang318** [comment]
**ICP规则的目的是为了体现 有工作成果就要有报酬，而不是让贡献者的行为仅仅严格符合规则，不能本末倒置
ben7th 这次的行为，我的主观判断是有工作成果，但是客观上提交物不在小白健康主体中
社区应该从制度上引导尽量不要出现这种情况的发生（提交物不在小白健康账号主体中）**

### 判断是否有提交物的依据是什么？
提交内容的目的有多种情况
1. 提交具体的提交物，把劳动成功记录下来，比如代码，设计文档，调研报告等
2. 证明自己付出过智慧和劳动并对社区或者社区其他贡献者的成果做出了贡献，比如运营操作，运维操作，review其他人的工作，测试报告，对其他贡献者提供顾问帮助等

但是提交物放在哪里，这个以前确实没有严格要求
比如有的 第二种提交物，放在了石墨文档或者其他第三方工具上，但是并不一定这个第三方工具使用的是小白健康企业账号
第一种提交物提交到了个人版本库还是第一次，这个社区应当不提倡和避免

还有第二种里很多是不好证明，但是却非常重要的，比如刘总调教教诲其他贡献者，这个我认为很重要
但是如果要把刘总的工作记录成ICP，我是不知道如何客观记录的，因为没法量化，这个事情的效果本身是一个主观的判断


### 在判断过程中是否要将后补内容（如2楼的内容）列入考虑？
如果 提交物提交到了 sibbay 版本库就不存在需要详细说明的情况了
但是如果一份提交物不是非常主流的做法（主流做法是ISSUE和PR都在sibbay 并且 commit 也在 sibbay 中）
应当做补充说明
比如很多第二种提交物是需要补充说明的

### 在判断过程中是否应该考虑主观因素？
一旦出现非主流做法，是应当考虑主观因素的，并且应当尽量把有需求和场景的非主流变成主流

### 在判断过程中是否应该考虑客观因素？
一旦出现非主流做法，是应当考虑主观因素的，并且应当尽量把有需求和场景的非主流变成主流
客观因素应当补充说明

### 在判断过程中是否应该涉及对人的评判？
这个太个人，太主观了，规定是或者否，都没有意义，感性的人是没法不去考虑对人的评判
人不是机器

**Comment by zhaobinglong** [comment]
> 1、判断是否有提交物的依据是什么？
我们目前对提交物的依据就是RP，需要更新这条规则，因为提交物它不一定就是PR，还可能是其他类型的内容
2、在判断过程中是否要将后补内容（如2楼的内容）列入考虑？
后补内容可以是对提交物的说明，我觉得这个可以考虑，

> 3、在判断过程中是否应该考虑主观因素？
> 4、在判断过程中是否应该考虑客观因素？

如果规则合理没有问题，我觉得就不需要考虑其他因素

5、在判断过程中是否应该涉及对人的评判？
不应当

**Comment by ben7th** [comment]
我的看法：

> 1、判断是否有提交物的依据是什么？
依据是是否有可追溯的，有明确可信产生时间的文档，数据，或实物；

> 2、在判断过程中是否要将后补内容（如2楼的内容）列入考虑？
后补内容如果是对“可追溯，有明确可信产生时间”的**补充说明**，则可考虑；
如果是新产生的，不符合上述条件的**新增内容**，则不考虑；

> 3、在判断过程中是否应该考虑主观因素？
规则一旦明确后，不应考虑主观因素；

> 4、在判断过程中是否应该考虑客观因素？
应考虑可追溯，可证实，有记录的客观因素；

> 5、在判断过程中是否应该涉及对人的评判？
不涉及

**Comment by bqx619** [comment]
> 1、判断是否有提交物的依据是什么？

"是否有" 其实很好判断, 有无是简单的选择提. 关键点是 "提交物", 也就是明确了对 "提交物" 的定义后, 这个问题就很好回答了.
目前社区对于 "提交物" 的解释不够应该给以补充. 例如: 使得凡是可以认为属于社区成果的知识类型都应该是提交物.

> 2、在判断过程中是否要将后补内容（如2楼的内容）列入考虑？

判断的过程不可能去类似于这个 issue 一样, 询问当事人甚至社区其他人的意见, 无法给予当事人实时的解释时间.
但是, 当当事人对判断结果不认可时, 应该有**补充**内容的权利, 前提是客观合理.

> 3、在判断过程中是否应该考虑主观因素？

> 所谓“主观”就是表面现象，凭借自己的观点。未经分析推算，下结论、决策和行为反应，暂时不能与其他不同看法的人仔细商讨，称为主观。

此种定义的主观, 不应该考虑.

> 4、在判断过程中是否应该考虑客观因素？

应该考虑, 客观是事实存在的, 不可转移的

> 5、在判断过程中是否应该涉及对人的评判？

不应该涉及, 但是很难做到. 人不是机器, 我们可以将客观作为要求, 但是无法彻底的不参杂主观情绪.
我能想到的方式是, 匿名.

评价的人不知道评价的是谁;
被评价的人不知道谁评价的自己.

**Comment by sinchb** [comment]
> 1、判断是否有提交物的依据是什么？
是否有提交物的依据只有：是否有PR， 这是社区规则自动化的基础。而我们需要做的应该是，不同类型的劳动产出，有不同类型的呈现方式：pr后对应的可以是：
* 代码merge
* 调研报告文档
* 操作记录文档
* 一个PRD文档
* 对某一个问题思考过程和结果
理论上，所有劳动都可以归一到pr

> 2、在判断过程中是否要将后补内容（如2楼的内容）列入考虑？
有一条原则：通过pr，可以找到对应的所有产出物（文档、代码、设计图）

> 3、在判断过程中是否应该考虑主观因素？
 不需要
> 4、在判断过程中是否应该考虑客观因素？
毋庸置疑，我们就是基于客观事实来判定

5、在判断过程中是否应该涉及对人的评判？
> 不涉及，应该集中评价：提交物、劳动成果、价值

**Comment by Yijia-Zhou** [comment]
> 判断是否有提交物的依据是什么？

​	在 issue 和 pr 中可以直接或者通过一次链接跳转看到所有应有的提交物。

> 在判断过程中是否要将后补内容（如2楼的内容）列入考虑？

​	可以考虑每个人在相同时间间隔内有有限次的申诉补充内容机会。

> 在判断过程中是否应该考虑主观因素？

​	不应该。

> 在判断过程中是否应该考虑客观因素？

​	如有客观因素限制，应在原始 issue/pr 中作出说明。

> 在判断过程中是否应该涉及对人的评判？

​	不应该。

**Comment by fushang318** [comment]
刘总的演讲录像
http://sibbay-files.oss-cn-hangzhou.aliyuncs.com/share/meeting/icp_and_sibbay_and_kaiyuan.mp4

**Comment by georgeliuyu** [comment]
### 说明：
>1、判断的依据：
仅仅是icp issue（4.1、凡没有在 issue 中记录的，都没有发生。），可以在issue中引用链接
>2、在判断过程中是否要将后补内容（如2楼的内容）列入考虑？
不接受任何超过16日00:00的补充内容
>3、在判断过程中是否应该考虑主观因素？
不考虑
>4、在判断过程中是否应该考虑客观因素？
可以酌情，例如存在客观实现困难。但应该尽量让EI评审清楚了解提交物
>5、在判断过程中是否应该涉及对人的评判？
不涉及

### 本事件的事实是：
- icp issue表述的提交物是代码
- 在icp issue中、以及该issue所能链接到的地方没有代码提交物（本issue是12月26日创建的，不包含）
- 不存着客观困难造成无法提交该提交物

### 结论
- **没有提交物**
- 鉴于本事件没有提交物，故不涉及知识产权问题。
- EI评审人员有责任及时发现没有提交物，或者提交物不清楚情况并向社区committer预警。

本次调查结束。
