### ISSUE TITLE
讨论：“对于申报了icp size，但是没有提交物”的处理

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#641]
### 1、目的和原则
小白健康是一个基于“尊重与信任”的社区，其核心是也就是“疑罪从无”，同时如何保证这样的社区能持续有效的生存和进步，配套的处罚原则是需要的。
### 2、方式
就是如何量化和执行。

大家可以发表一下意见。

**Comment by ben7th** [comment]
根据我在 https://github.com/sibbay-ai/public/issues/640#issuecomment-568952701 的回复：

> 确定版权归属不属于 sibbay 的部分，对应的 ICP SIZE，在后续以某种方式扣除

由于结论为不涉及版权问题，则按因为没有提交物导致 ICP 无效来处罚。

扣除内容和形式包括：

- 已支付费用（在下月或后续月费用中扣减）
- EI（系统上调整）
- SHT（销毁罚款）

扣除额度应为原 ICP 对应额度加上一定数量的罚款

**Comment by georgeliuyu** [comment]
@ben7th 
建议不仅仅针对这次事件来提建议。

**Comment by pimgeek** [comment]
我提一个建议，不是事后做处理的建议，而是事前预防偏差的建议 😅：

* 匿名收集团队成员在日常工作中产生的 “不适感”（ @bqx619 在 #640 中提到过匿名收集，提醒我了 ）
* 可以考虑每周收集一次，不舒适感可能会变成下意识的 “绕开流程走”
* 设立一定的门槛，这个我还没想好怎么设置，目的是为了减少 “冲动的不适感反馈”，导致日常工作被过度干扰
* 收集的内容尽可能简单，比如 3 等级的不舒适程度 + 不舒适的场景描述 / 建议的解决思路、方案等
* 不必追求场景描述或解决思路特别清晰，因为以后还有可能继续匿名提交
* 可视化展现 “不适感” 的总体情况，允许团队成员把 “缓解不适感” 当成日常任务去解决
* 如果问题得到解决，大家通过可视化报告看到后，可考虑给予 SHT 奖励
* 如果问题一直没能得到解决，因为大家都看到了，也可以考虑用其它方式解决

一句话总结，**让 [房间里的大象](https://worktile.com/blog/okr/okr-ceo) 露出痕迹。** 😃

**Comment by ben7th** [comment]
> @ben7th
> 建议不仅仅针对这次事件来提建议。

针对“无提交物”和其他以后类似的任务执行/完成不当的处理规则的通用建议：

- 定性：基于简单的规则判断是否适用该处理规则
- 定量：基于可追溯的记录来判断影响范围并定量，定量时列举可追溯记录
   - sibbay repo 内的 issue
   - ICP 系统数据
- 执行：基于定量进行处罚

**Comment by georgeliuyu** [comment]
关于社区处罚的量化的基本原则就是：
- 使得机会成本大于收益
- 处罚不能过大，否则会呈现风险成本远远大于收益，这会使人成天纠结于条款细节。
具体方式：
涉及金额*1.2/发现概率

本次处罚决定如下：
发现概率按照：50%
涉及金额 size：12*1.2/0.5=28.8  在后面的贡献中逐步扣除
涉及token：按照这个月的token获得总数*1.2/0.5 ,由本人进行销毁
@jessica @sibbay-ai/all

**Comment by ben7th** [comment]
金额 size 扣除，我个人申请按多个月进行
token 具体数量，需要 @jessica 告知基数

**Comment by Jessica124** [comment]
关于宋亮的处罚：
涉及金额Size：28.8个，本月贡献中已扣除11个Size，还需扣除17.8个Size。经过与宋亮和刘总沟通，同意其用token来抵剩余的17.8个Size。兑换率按照现行的1SHT=0.115RMB来进行折算，折算后是77391.3个SHT
涉及的token：12月宋亮的token数量是73754.16个SHT，根据计算需销毁的token数量为：177009.98个SHT
总共需销毁的token数量为：77391.3+177009.98=254401.28个，本月将由财务销毁94702.36个SHT，剩余部分159698.92个SHT将由宋亮本人在2021年1月15日之前自行销毁
@ben7th
