### ISSUE TITLE
关于引入新同学@haomingdave熟悉小程序代码的安排

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#648]
引入 @haomingdave 同学进行贡献尝试，首先从小程序入手：
- @fushang318 开放小程序代码库给 @haomingdave 
- @zhaobinglong 给新同学做一下小程序框架的介绍，并在石墨文档上提供密码授权（或有 @fushang318 处理）
- @haomingdave 完成以下任务：
  - 了解现有小程序，向 @zhaobinglong 提交分析报告
  - 做一个尝试开发，可将前期实现的语音输入加到rpc中 ，与@zhaobinglong对接
  - 参与新产品的讨论 与 @nancy919 对接

**Comment by fushang318** [comment]
https://github.com/sibbay-ai/lt-miniapp-wepy 已经授权   @HaomingDave

**Comment by fushang318** [comment]
https://shimo.im/doc/L2TH9cmKRPMScrIB  已经授权 @HaomingDave
