### ISSUE TITLE
如何快速读懂issue

### ISSUE THREAD

**Issue by fangrongxaing** [sibbay-ai/public#65]
在issue中对于重要信息怎么表示，或是可以通过举例子说明?

**Comment by fushang318** [comment]
没明白你的意思，issue 只是一种形式，和在 word 里编写一遍文章没有区别

**Comment by fangrongxaing** [comment]
好的👌

**Comment by ben7th** [comment]
@fangrongxaing 

issue 是工作的沟通途径，无论是发 issue 还是读 issue
都需要清楚地说明/获取两个关键信息

- 需要做什么/有什么问题
- 希望由谁来做/由谁来回答这个问题（@ 其他人）
