### ISSUE TITLE
关于Size申报说明

### ISSUE THREAD

**Issue by Jessica124** [sibbay-ai/public#650]
@bqx619 由于本月（4月）的Size数量较大，需要请你做一个补充说明，谢谢支持与理解！
@georgeliuyu 刘总，请知晓，谢谢

**Comment by bqx619** [comment]
> date: 2020-04-20

# 针对财务问询 "本月 size 数量大" 的回复

## 说明

- 本月 size 数量: **38.5**

- 本月 size 分布:

size 大小 | 数量
--- | ---
0.2 | 6
0.3 | 1
0.5 | 2
1.0 | 2
1.5 | 12
2.0 | 5
3.0 | 2

- 本月 size 个数: 30

## 回复

1. 其中 size 小于 1 的为琐碎正常开发, 具体做了什么, 可以看 issue 标题及内容知晓;
1. 其中 size = 1 的 2 个 issue, 为**线上互动预览工具**的新功能开发, 就我个人来说, 没有突发需要说明得内容, 都是在需要开发得时候, 做了相关得工作;
1. 其中 size = 1.5 的 issue:
    1.  9 个对应了**vscode mri 插件**的第一个版本开发, 根据社区规定, 仅仅以提交物作为 size 的衡量, 每个 issue 都可以在关联 pr 找到对应的代码文件, 同时特殊的是, 这 9 个 issue 虽然在本月计算 icp, **但其开发周期仅仅为在本月收尾, 实际编码包括了 2,3 月份, 但因为其为达到可合并代码阶段, 所以并未在 2, 3 月份发起 icp**;
    1. 2 个对应了意图互动的开发, 意图互动, 涵盖了新版意图的设计及对应的互动实现, 1 个对应了 MLANG 的意图接口的功能开发(数据结构转换), 没有突发需要说明的内容.
1. 其中 size = 2 的 issue,  2 个对应了**vscode mri 插件**的第二个重要版本: 0.0.6 的开发, 实际开发的内容在 issue 和 released 里面有相关说明; 剩余 3 个,  开发的内容和产物, 可以通过标题/issue 内容明确;
1.  其中 size = 3 的 issue, 分别是对 kitymindmap-editor 导图的二次开发, 和 data-mri 代码结构和 mlang/models/utils 的引入支持使得 data-mri 可以单独运行相应的编译后的 py 两项完成内容多的任务.

**Comment by Jessica124** [comment]
各位同学，关于Size的提交，建议大家尽量每个月提交，否则可能会带来一些问题：1.某个月Size较大，财务会要求提交补充说明，2.如果涉及到之前月份Size未申报的，在核算SHT奖励时，财务只会用当月实际产生的Size作为基数进行核算。谢谢大家的支持与理解！
