### ISSUE TITLE
申诉：对本年度三、四月份的issue进行重新审核 @Nancy_919

### ISSUE THREAD

**Issue by nancy919** [sibbay-ai/public#651]
申诉：

希望对本人本年度三、四月份的issue进行重新审核。

**三月issue：**

![WechatIMG540](https://user-images.githubusercontent.com/42829996/80167871-1485c380-8614-11ea-98e7-56006a53d979.jpeg)

**四月issue：**

![WechatIMG539](https://user-images.githubusercontent.com/42829996/80167881-18b1e100-8614-11ea-9a99-963c5d74c2d2.jpeg)

申诉原因：

1、自认为自己在工作中，认真负责，没有怠慢或偷懒，偶尔会犯错，但也在常理范围内；
2、有严格按照社区规则提交issue：以结果为提交物，凡是没有产出的工作，即便付出时间也都有按照社区规则处理；
3、产品的工作，总是需要进行一些不太容易产生结果的事情，例如：思考、沟通、调研、与用户沟通等等；但呈现出来的结果（也许还会被推翻）相对技术来说，比较不占优势，不容易看到其中付出的努力，因此投票的时候容易失分；
4、目前要从事产品、设计、运营、测试、文案、客服等多个角色，事情多且杂，在角色的切换过程中，使得在某些领域里的专业度不够高，要学习的东西也很多。但其他成员对待产出的结果，是按一个较高的标准来看，因此会出现一些失分的评价。
5、总之，对自己工作上的付出，谈不上很优秀，但也问之无愧。

**Comment by nancy919** [comment]
请审核人批准。 @fushang318 @georgeliuyu

**Comment by georgeliuyu** [comment]
建议 @fushang318 提前组织大家学习一下申诉机制的流程。

**Comment by Jessica124** [comment]
1.经过与南希确认，同意按照《关于ICP EI调整的规定（暂行）》来执行。
2.与刘总的沟通后，鉴于申诉机制的并未在ICP系统中实现，而社区推出了新的《关于ICP EI调整的规定（暂行）》https://github.com/sibbay-ai/public/issues/653，而maintainer认为该贡献者4月EI评价值本来应该进行调整，故建议：
- 由maintainer将该贡献者的EI调整到0.8，作为达标月份
- 补发4月的扣除的贡献size，并在下个月一起发放

**Comment by fushang318** [comment]
![image](https://user-images.githubusercontent.com/326242/80690863-021ef480-8b02-11ea-857b-57015531da91.png)

**Comment by fushang318** [comment]
已经在 ICP 系统调整为 0.8
