### ISSUE TITLE
2020 年 4 月 27 日 晚会沟通 ICP 系统的建议

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/public#652]
一些建议，排名不分先后

1. 刘总作为创始人，拥有一定的高权重投票权利，比如：可以看到所有的投票，任意选择投票进行投票 ，但是数量要有限制，按照一定算法给刘总分配一定数量的投票
2. 刘总作为创始人，每个月拥有一个”免死金牌“，比如可以让某一个 EI 小于 0.8 的人 EI 变成 0.8
3. 刘总作为一个有贡献，但是没有 ICP 的贡献者，要拥有一定的投票权。票数的多少，可以由其他贡献值在提交时，指定一个希望刘总可以参与这位贡献者自己票的比例
4. 加入一些其他维度的投票，比如面向其他贡献者整体情况的投票，比如这个月这位贡献者的工作质量，工作多少，协调流畅度等方面的投票，具体机制，可以再设计，开脑洞的想，比如可以给某一个人减分

讨论中，大家觉得目前的弊端
1. 仔细投票，和简单看来分豆豆的投票，结果感觉没有区别
2。 现在的投票机制，不鼓励太大的SIZE，但是工作不是简单的可以拆分的，只能为了整体SIZE，互相匀SIZE，形成恶性循环

**Comment by georgeliuyu** [comment]
回复：
- 针对大家的意见，推出：https://github.com/sibbay-ai/public/issues/653 暂行规定
关于所谓弊端：
- 1、其实平衡的策略就是投票人的一种选择；
- 2、是的，太大的size可能会增大随机性，所以还是不建议
