### ISSUE TITLE
关于优化SHT机制的通知

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#655]
为了进一步完善SHT的奖励机制，促进icp的贡献。想进行进行规则的完善。
https://github.com/sibbay-ai/public/pull/654

2020年8月1日开始实施

@sibbay-ai/all

**Comment by fushang318** [comment]
修改机制的动机
http://sibbay-files.oss-cn-hangzhou.aliyuncs.com/share/sht_unlock_change.mp4
