### ISSUE TITLE
小白社区贡献者ICP流程认证- HaomingDave 

### ISSUE THREAD

**Issue by nancy919** [sibbay-ai/public#658]
目前已完成了对 @HaomingDave 的贡献者ICP流程认证培训和测试工作，

以下是审核结果：

<img width="426" alt="屏幕快照 2020-05-15 下午2 53 33" src="https://user-images.githubusercontent.com/42829996/82020721-3545b400-96bc-11ea-98ce-90be9674079e.png">

相关连接：https://github.com/sibbay-ai/public/blob/master/icp_auth_records/HaomingDave.md

**Comment by nancy919** [comment]
@georgeliuyu  请进行审批

**Comment by georgeliuyu** [comment]
同意，level从CPL-D开始
@jessica
