### ISSUE TITLE
mri bunch撰写培训

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#66]
1、怎么样才能让不懂技术的医学或文科从业人员能够比较容易地输入结构化/半结构化的诊疗对话，并且能比较快地转换成 mri 脚本。
2 上手操作：下周一找李飞要到 mri 新版后台账号并上手操作，熟悉功能，并且看看这个对话录入工具有什么需要改进的地方？
3 试着讲课：试着把 mri 工具的使用方法做成半小时左右的课程。试着把icp众和流程相关的知识，整理成可以讲课的内容。

提交物及icp的管理 @ben7th 你思考一下

**Comment by pimgeek** [comment]
@georgeliuyu 申请开发 Size：10, Deadline：2017-01-08 【周一后才会将 Deadline 收紧为合理日期】

**Comment by fushang318** [comment]
@georgeliuyu 提交物和ICP管理应该和调研工作类似

**Comment by pimgeek** [comment]
* 本周一中午 13:00 开会，预计 1 小时
* 会议主题：讨论上述工作内容的具体落实计划与相关任务安排
* 参与者： @pimgeek @fushang318

**Comment by pimgeek** [comment]
@georgeliuyu 

> 1 怎么样才能让不懂技术的医学或文科从业人员能够比较容易地输入结构化/半结构化的诊疗对话，并且能比较快地转换成 mri 脚本。

1 这项项工作是一个具有明显研究属性的任务，我虽然很想主导这件事，但是它所需的时间和资源不易估量，也无法做出任务承诺。落地思路会处于酝酿状态（时机合适时做一些实验，然后自己粗略统计实验结果和耗费的时间），但在第一次形成可复现的落地步骤之前，我很难想象如何创建 issue。

> 2 上手操作：下周一找李飞要到 mri 新版后台账号并上手操作，熟悉功能，并且看看这个对话录入工具有什么需要改进的地方？

**2 这项工作已经开始准备落地，我会在接下来的评论中给出说明。**

> 3 试着讲课：试着把 mri 工具的使用方法做成半小时左右的课程。试着把icp众和流程相关的知识，整理成可以讲课的内容。

3 这项工作，依赖于 2，所以暂不创建 issue。另外，与 ICP 众和流程相关的讲课内容，现在也不适合直接开展，所以暂时也不会创建 issue。

**Comment by pimgeek** [comment]
@georgeliuyu @fushang318 

在 https://github.com/sibbay-ai/public/issues/66#issuecomment-353831709 会议中，@pimgeek 与
 @fushang318 做了一些沟通，达成了以下共识：

- 熟悉 MRI 仿真器各项功能，提出改进意见，以及整理资料形成视频上手教程的过程，可能比较复杂，不宜用一个单一的 ICP issue 来解决，而是应该建立一个里程碑，分出一些子任务逐步完成。
- 大概工作计划：
  - 任务 1：根据李飞提供的测试环境后台管理账号，登录试用 MRI 仿真器系统，初步了解系统功能
    - 提交物：一篇报告，报告内容主要包括 @pimgeek 对系统的总体看法， @pimgeek 认为自己需要学会的要点， @pimgeek 关于系统的一些疑问和建议等。
  - 任务 2：根据任务 1 的提交物，把那些需要重点讲解的功能，划分为一些相对独立的主题，以便分别制作课件。
    - 提交物：一个主题列表，内含 MRI 仿真系统的主要课件名称和讲解要点
  - 任务 3：根据任务 2 形成的主题列表，进行课件制作

**Comment by georgeliuyu** [comment]
@pimgeek 对的，可以按照你们的讨论结果推进。icp的核心方式是：一定要有提交物。

**Comment by ben7th** [comment]
@pimgeek 把所有中间产生的教学内容，相关资源链接，培训结果记录，都整理成文档，以 markdown 代码的形式 pull request 提交到某个版本库即可。

版本库的创建和 pull request 的提交到时可以找我。关系到 ICP 工作的验收和贡献发放。

**Comment by fushang318** [comment]
本周五（2017-12-29）中午 13:00 开会，预计 1 小时
会议主题：MRI仿真器问题答疑
参与者： @pimgeek @fushang318

**Comment by pimgeek** [comment]
@ben7th 请帮我创建一个【MRI 仿真器使用教学】相关的版本库，我今天晚些时候会提交【MRI 仿真器试用报告】相关 Pull Request 到里面。

**Comment by ben7th** [comment]
@georgeliuyu 你在这里提交内容吧
https://github.com/sibbay-ai/mri-learning

**Comment by fushang318** [comment]
@ben7th 你 @ 错认了      @pimgeek
