### ISSUE TITLE
云上年会

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#67]
昨天见一位来上海游玩的contributor，看看到外面已经是浓浓的圣诞气氛了，突发奇想：小白是否可以开一个“云上年会”。
虽然我们的同学分布在各地，但通信已经使其变得不是问题。
来吧！你们创新看看！

**Comment by fangrongxaing** [comment]
分享类：自我分享/才艺表演
娱乐类：成语接龙/猜谜解密/
角色扮演：（分别扮演小白使用者和没使用小白的普通人，怎么通过自己的推荐方式赢得对方的信任和采用）
感悟类：发有意义故事和视频，然后看谁能提取其中字最短，却最有意义的一句话

**Comment by georgeliuyu** [comment]
参加的范围：2017年为小白做过贡献的同学。  
1. 这个讨论可以分出icp的issue。如果你还没有贡献过现在就是机会。  
2. 活动费用5000元+两样特殊礼品。

**Comment by georgeliuyu** [comment]
如何组织？或者说组织者如何产生？

**Comment by alisahuxu** [comment]
我们可以做一些前期的线上宣传：制作邀请卡，设计一些游戏环节，还可以让用户可以参与，领取一些小礼品。

**Comment by pimgeek** [comment]
我提一个小建议，或许可以增进贡献者之间的互相了解。

下面的这个【会员思维导图演示动画】，我在我们的演讲俱乐部使用过，效果不错，至少吸引了会员们的关注。或许可以用于小白众和团队。
![2018-tmair-officers-with-intro](https://user-images.githubusercontent.com/1609306/34333162-9ac119ac-e974-11e7-97de-0027c57afe77.gif)

**Comment by alisahuxu** [comment]
小白健康——云上年会
1.1 电子邀请函：时间、联络工具、会议主题、小白健康组织介绍

1.2 开场环节
1.2.1  成员思维导图演示动画或视频
1.2.2  小白健康发展阶段介绍

1.3互动环节
1.3.1 分享2017年的感悟
1.3.2 小游戏，颁奖

1.4媒体报道

@shero3 我们现在有多少成员，他们分别负责什么工作？
如果实物邀请函要提前制作，麻烦告诉我一下。

大家有什么好的点子，可以添加进来。谢谢~

**Comment by georgeliuyu** [comment]
@alisahuxu @shero3 我们的人员核心是在码市上

**Comment by shero3** [comment]
https://github.com/sibbay-ai/public/issues/90   这个里面包含了2017年为小白做出过贡献的人员名单，我知道医学组这边不止小贾一人，组员是否一起列入年会名单？  @georgeliuyu

**Comment by georgeliuyu** [comment]
@alisahuxu 另外你可以在 小白的众和群你发个通知。那里有做个贡献的同学，也有没有参与过的。

**Comment by georgeliuyu** [comment]
@shero3 原则是凡是小白支付过费用的都应该邀请。
码市上的曾经的接包人员应该都要邀请。你可以整理一下。那里都有电话

**Comment by shero3** [comment]
大概什么时候需要码市上曾经接包人员的名单 @alisahuxu

**Comment by alisahuxu** [comment]
@shero3 今天能给我吗？
