### ISSUE TITLE
关于icp流程培训课程

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#68]
建立培训icp课程，并进行一次培训。@ben7th 你确定个时间安排和deadline。

@fushang318 @sinchb 知晓

**Comment by fushang318** [comment]
@georgeliuyu 
已经有安排了吧，你看这个 https://github.com/sibbay-ai/cooperation-issues/issues/124

**Comment by pimgeek** [comment]
@fushang318 你发的这个链接，我看不到。这是一个私密地址吗？

**Comment by fushang318** [comment]
@pimgeek 是的，你需要了解吗

**Comment by pimgeek** [comment]
@fushang318 这个事情，目前对我的优先级不太高，但我希望如果培训过后有录音或录像资料，我能够在这里看到。

**Comment by fushang318** [comment]
@georgeliuyu 嗯，目前是准备开一次会，铺垫一下这个事情，到时候可以录像  @ben7th

**Comment by ben7th** [comment]
@georgeliuyu 

需求中的询问点：
- 培训针对哪些人员（除了开发者，是否还包括非技术背景的参与者）
- 培训目的和培训效果的验收目前有没有预设？

实现方式：
我计划将培训内容做成视频，上传到阿里云 OSS 以便在线观看。
再通过 issue 进行答疑。
视频制作在周五（12.29 24:00 前）完成。

**Comment by ben7th** [comment]
已经录制好两个视频：

文档导读：
http://img4ye.oss-cn-hangzhou.aliyuncs.com/sibbay-video/1.mp4
18 分 17 秒

操作示例：
http://img4ye.oss-cn-hangzhou.aliyuncs.com/sibbay-video/2.mp4
22 分 10 秒

目前放在其他的 OSS，需要 @fushang318 帮忙传到 sibbay 的 OSS 里，选择合适的目录（可公开访问）
完成后，由我提交索引文档 PR

**Comment by fushang318** [comment]
@ben7th 
1. 在 aliyun 开通一个 oss: sibbay-files
2. 给 sibbay-files oss 规划了 /icp_tutorial 目录放置 icp 教程
3. 给 @ben7th 的阿里云子账号设置了 /icp_tutorial 目录的编辑权限

**Comment by ben7th** [comment]
已经上传到指定位置：
http://sibbay-files.oss-cn-hangzhou.aliyuncs.com/icp_tutorial/1.mp4
http://sibbay-files.oss-cn-hangzhou.aliyuncs.com/icp_tutorial/2.mp4
