### ISSUE TITLE
ICP方式下的贡献者确定讨论

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#7]
在ICP模式下存在一个需求有多个contributor有能力和兴趣开发的情况出现：
见：https://github.com/sibbay-ai/public/issues/6
关于如何选择的？
欢迎大家本着尊重和感谢的原则发表您的建议：（不建议拆分或共同完成）
可能的因素：历史（在小白社区中的贡献值）、效率（工作量）、deadline、提交时间、或者您想到的因素

**Comment by ax003d** [comment]
我建议是：
当我们的 contributor pool 还不够大的时候，应该优先选择新的 contributor，扩大 pool；
当我们的 contributor pool 已经足够大的时候，应该优先选择 pool 中的 contributor，保证 pool 中的 contributor 有足够的工作量。

**Comment by cyssxt** [comment]
我认为首先在基于需求的重要性和时间点上面考虑!
        对于脱离于业务存在的需求，我觉得应该尽量选择新的contributor，这样可以培养一批新的contributor，
        对于需要熟悉老的业务的需求，最好是通过一个老contributor带动一个新的或多个contributor去发展一批新的contributor，
        对于有难度的，重要性比较高的，选择评分高的
        对于一次完整contribute，都需要对于contributor需要评分，
        这样就存在了另一个课题，就是如何有效的评分？时间？工作量？bug数？反馈时间？兼职类型？

**Comment by cyssxt** [comment]
我觉得对于icp的模式，就是需要尽量多的人参与进来，并且能保证效率和正确率，避免issue的单点依赖。

**Comment by fushang318** [comment]
在历史（在小白社区中的贡献值）、效率（工作量）、deadline、提交时间等因素都差不多的情况下
可以从对需求理解的程度和熟悉程度上考虑

**Comment by georgeliuyu** [comment]
还想到一个问题，在决策因素确定的情况下：是由发起需求的committer全权决定还是需要讨论？

**Comment by fushang318** [comment]
可以由发起需求的committer 自己决定是否需要讨论或者自己就可以决定吧

**Comment by ben7th** [comment]
一般这种情况容易出现在这样的工作上：

- 工作的需求非常明确（无需花时间讨论需求/决策）
- 工作对于产品/项目之前的知识没有太多依赖

若上述判断成立，我的想法是，凡是具有此类特征的工作，尽量优先让新加入的开发者参与；
理由是：这是新加入开发者最容易参与的工作，换言之，要把参与门槛不高的工作优先开放给新加入开发者，才有利于众合组织的成长。

从另一个角度来说，多次合作的开发者，应该努力争取参与门槛较高的任务（需要花较多精力在需求讨论决策上，以及对过去的产品知识需要较多掌握），这样，才能印证开发者在该众合组织内的提升。

若不这样做，很可能会演变成：简单工作很多人抢，困难工作无人承担的局面；

总结：
- 鼓励新加入开发者参与低门槛工作
- 鼓励老开发者逐渐参与高门槛工作

**Comment by sinchb** [comment]
我同上面几位意见其实类似，committer可以从两个方面考虑

1. 优先从投入产出比考虑
如果一个需求需要很强的小白业务背景知识，需要跨部门协作，需要依赖过去经验去作决策，那么由一位老手去做，可能会有很高的投入产出比。新人则需要投入比较大的学习和辅助成本。
2. 从培养新人方面考虑
如果一件事是全新的，或者如上面几位同学所述，和现有业务解耦，或者是一个讨论等，可以由committer去决策，选出 **一位或者几位** 新人去练手。

**Comment by wb14123** [comment]
我之前参与过的一个开发也有类似的管理机制，他们是根据积分、开发者的空闲时间和加入时间等因素,自动分配的任务。如果开发者不愿意接受这个任务可以再分配给其他人。

这里有两个他们的工作方法的链接，我感觉还是挺不错的。可以参考：

http://www.xdsd.org/
http://www.yegor256.com/tag/xdsd.html

**Comment by georgeliuyu** [comment]
@wb14123 非常有参考价值。

**Comment by ben7th** [comment]
文档已合并，此 issue 关闭
