### ISSUE TITLE
小白健康-日历

### ISSUE THREAD

**Issue by alisahuxu** [sibbay-ai/public#70]
用户每天打开小白健康-小程序，都有一句问候，以日历的形式推送给用户。
内容关于健康、生活等等，风格以简洁，抚慰人心。
后期，如果对用户有大数据分析，可以做到针对性的文案推送。

**Comment by fushang318** [comment]
> 以日历的形式推送给用户。
没有明白 日历的形式 指的是什么

**Comment by alisahuxu** [comment]
就像翻看日历一样。用户每天打开小白，可以推送给他们一个页面，或者图片：比如：良好的心态是健康的基础——2017年12月25日。

**Comment by fushang318** [comment]
😞, 还是没懂

**Comment by alisahuxu** [comment]
可以参考京东金融和单向街日历。哈哈哈~

**Comment by fushang318** [comment]
@alisahuxu 
一个需求和功能，要把它介绍的足够清楚，不能是简单的这样一句话，或者是参考XXX，因为参考这个词太大了，每个人看到一个东西的关注点是不一样的，你能够确保别人看了XXX想的就和你完全一样吗

具体说说这个需求，我认为有两个关键词
1. 每日推送
2. 日历

能否把你的想法通过对参考APP的截图来详细说明一下这两个关键词的意思呢

**Comment by fazhen** [comment]
目前小白是一个小程序，打开之后是直接进入了界面（不知道改版后是怎样一种形式）；它不像APP一样，可以在你打开时推送一些信息出来。如果希望添加这个功能，是不是可以利用微信公众号每天进行推送？

**Comment by fushang318** [comment]
@fazhen 
微信小程序也是可以推送内容的，不过形式上和技术上有一定限制，具体还要看具体想要实现什么形式的内容推送和呈现

**Comment by fushang318** [comment]
@alisahuxu 您推荐的两个APP我会看，但是也希望您看看我的建议，这样沟通需求会更精准一些，减少后续工作的风险

**Comment by fazhen** [comment]
我觉得可以利用墨刀或者axure画一些简单原型，这样比较清楚一些

**Comment by alisahuxu** [comment]
可以。@fushang318
微信公众号可以每天推送，小程序如何实现我不太清楚@fazhen

**Comment by fazhen** [comment]
在知乎上看到的，关于小程序推送消息的限制。http://www.zhihu.com/question/52719661

**Comment by georgeliuyu** [comment]
![image](https://user-images.githubusercontent.com/16983441/34333245-a6d315c8-e975-11e7-9bd5-a7620b44ef82.png)

![image](https://user-images.githubusercontent.com/16983441/34333250-af061952-e975-11e7-99d6-1c7bcb961bde.png)

@alisahuxu  是这个吗？

**Comment by alisahuxu** [comment]
![webwxgetmsgimg](https://user-images.githubusercontent.com/34643533/34333831-a99f9276-e97b-11e7-8e3d-5ba1e3f8a349.jpeg)

**Comment by alisahuxu** [comment]
![webwxgetmsgimg 1](https://user-images.githubusercontent.com/34643533/34333877-15130ede-e97c-11e7-80f5-b90b1face17b.jpeg)

**Comment by fushang318** [comment]
@alisahuxu 
我已经体验了 单向历
![image](https://user-images.githubusercontent.com/326242/34334257-db8850bc-e97f-11e7-8f12-11ec0877b8cb.png)

在体验这个APP之前我带了如下几个问题  
1. 这些像日历样式的内容，一般是每天早晨推送到手机通知栏，然后可以点击通知栏消息进入这个页面吗
2. 不同的人，相同的一天，看到的信息是否一样
3. 是否有一个日历界面（以月视图显示），然后可以查看以前的某一天的信息，或者是否可以查看以后某一天的信息
4. 每日的信息是需要运营人员提前几天去填写的吧

体验完这个APP后，我得出了如下结论
针对问题 1，需要结合小程序技术实现，看看是否可以实现
针对问题 2 ，可以先做成是一样的
针对问题 3  ，结论是
1. 有一个日历界面（以月视图显示）
2. 可以查看以前的某一天的信息
3. 不能查看以后某一天的信息

针对问题 4 ，我觉得是需要开发一个后台功能，给运维人员去填写每日内容的

你看看我的理解是否有偏差

**Comment by alisahuxu** [comment]
是的。针对问题4，作为运营，我可以提前准备一个月的内容。不知道能否批量导入，后台定时推送？

**Comment by fushang318** [comment]
@alisahuxu 嗯

1. 您说的批量导入，其实需求就是：后台可以支持运营人员比较方便的提前创建好后续一段时间的每日信息

2. 后台定时推送当天信息，这个是肯定的

**Comment by fushang318** [comment]
@alisahuxu 
我还想再问一个问题：设计这个功能的初衷是什么

**Comment by ax003d** [comment]
已通过 MRI 实现，关闭此 issue
