### ISSUE TITLE
熟悉MRI仿真器系统，并提交一篇报告

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/public#71]
需求来源： https://github.com/sibbay-ai/public/issues/66

熟悉MRI仿真器系统，并提交一篇报告，内容包括
1. 对系统的总体看法
2. 认为自己需要学会的要点
3. 关于系统的一些疑问和建议等

需要的提前准备
1. @fushang318 提供后台管理系统账号
2. @fushang318 提供一些基础资料

**Comment by fushang318** [comment]
@pimgeek 我邀请你进入 sibbay-ai team 了，你确认一下

**Comment by fushang318** [comment]
@pimgeek 请确认 size 和 deadline

**Comment by pimgeek** [comment]
@fushang318 size：1 deadline：2017-12-29，截止期可协商。

**Comment by fushang318** [comment]
@pimgeek 好的
文档可以用 markdown 写，提交到 https://github.com/sibbay-ai/doc-started  
目录是 mri-sandbox/pimgeek.md，需要新建分支来提交并创建 pull request 到 master 分支

或者用石墨写，把石墨连接提交到 mri-sandbox/pimgeek.md 文件中

**Comment by pimgeek** [comment]
这项工作，实际撰写报告，调整版式，外加提交到 GitHub 版本库的的时间超出了预期，希望调整为：

size：1.5 deadline：2017-12-29

提交结果可参考 ：https://github.com/sibbay-ai/mri-learning/blob/pimgeek-patch-1/mri-simulator-trial-use-report.md

**Comment by fushang318** [comment]
完成

**Comment by fushang318** [comment]
@pimgeek 已经修改
