### ISSUE TITLE
小白界面UI更改总目录

### ISSUE THREAD

**Issue by fangrongxaing** [sibbay-ai/public#72]
小白界面UI更改
原版本称为V1.0  
目前版本成为V1.5
V1.5与V1.0在格式和内容上有许多不符，在V1.0原版本上，V1.5应该与其保持一致（内容，版面，颜色，图标）。如有更好的创意，请@我，然后我会编辑方案，在让刘总考虑。
以下是更改要求
（后台是否直接用V1.0当做模板设计编程）
总体更改目录（链接）
1.排版矫正 #73 
2.图标矫正 #77 
3.字体矫正 #80 
4.颜色矫正 #86 
5.其它细节
![01](https://user-images.githubusercontent.com/33997808/34336545-fb384e90-e992-11e7-9790-6ecb27b28bb4.jpg)
@ben7th

**Comment by ben7th** [comment]
@fangrongxaing 

已经在 https://github.com/sibbay-ai/public/issues/73 之中回复

**Comment by Yidadaa** [comment]
@ben7th @fangrongxaing 

我来负责调整。

**Comment by ben7th** [comment]
@Yidadaa 好，建议可按 @fangrongxaing 提出的
排版，图标，字体，颜色，其他细节的方式调整，分若干次提交 pr

我会在 lt-miniapp 下面发 ICP issue 来跟踪，你在下面回复计划时间

**Comment by Yidadaa** [comment]
@ben7th 收到，今晚回复计划时间。

**Comment by fangrongxaing** [comment]
2017-12-30更新素材（爱心发送 （2）/背景墙）PNG
[更新素材.zip](https://github.com/sibbay-ai/public/files/1594450/default.zip)
@Yidadaa @ben7th
