### ISSUE TITLE
写一篇对后台管理系统代码理解的文档

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/public#75]
写一篇对后台管理系统代码理解的文档，可以包括技术，业务，UI，UE各方面内容。

**Comment by fushang318** [comment]
文档提交到：https://github.com/sibbay-ai/doc-started

**Comment by georgeliuyu** [comment]
可参考 https://github.com/sibbay-ai/mri-mri/blob/develop/README.md @fushang318

**Comment by fushang318** [comment]
@georgeliuyu 好的

**Comment by fushang318** [comment]
@bqx619 
后台管理前端代码版本库 https://github.com/sibbay-ai/ms-view

**Comment by bqx619** [comment]
@fushang318 了解

**Comment by fushang318** [comment]
后台API文档：https://sibbayms.docs.apiary.io/#

**Comment by fushang318** [comment]
后台管理测试环境地址：http://dbtest.sibbay.net/

**Comment by fushang318** [comment]
@bqx619

**Comment by bqx619** [comment]
@fushang318 收到.

**Comment by fushang318** [comment]
@bqx619 
今天晚上刚进行了小白立会，立会决定希望你的这篇文档以补全完善 https://github.com/sibbay-ai/ms-view 的 README.md 文档为目标
其实今天我给你演示的 mri-mri 的 README.md 文档就是这两天一位同学补全完善的 README.md，思路上你可以参考，目的是就是给以后的新人留下更完善的 README

**Comment by bqx619** [comment]
@fushang318 了解, 本来还有些纠结相关在 `README.md` 出现的东西, 我的文档是不是不用再写了. 现在就好办了, 当做 `README.md` 来写即可. 谢谢.

**Comment by bqx619** [comment]
@fushang318 已发起`doc-started`的 pr , 第一阶段码市发包任务于`2017-12-29`第一次提交. 如通过,请告知我是否在码市上操作第一阶段任务的完成.

**Comment by fushang318** [comment]
@bqx619 
1. 把 PR 直接提交到 ms-view 项目吧
2. 你在码市上点击这个阶段提交吧，提交内容附上 PR 的链接

**Comment by bqx619** [comment]
@fushang318 已完成 PR 和码市阶段提交

**Comment by fushang318** [comment]
已完成
