### ISSUE TITLE
症状审批功能中，增加可以提交审批未通过的原因

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/public#76]
来自：#74

写一个小的功能，并熟悉小白的开发流程

功能为：在症状审核流程中  
1. 审核者需要可以提交未通过原因
2. 草稿编辑者应该可以看到没有通过审核的原因

**Comment by fushang318** [comment]
代码版本库：文档提交到：https://github.com/sibbay-ai/ms-view

**Comment by bqx619** [comment]
@fushang318 是指第一步的理解文档和之后的功能开发都提交至 `ms-view` 这个库吗?

**Comment by fushang318** [comment]
> @fushang318 是指第一步的理解文档和之后的功能开发都提交至 ms-view 这个库吗?


@bqx619 看 https://github.com/sibbay-ai/public/issues/75 的说明

**Comment by bqx619** [comment]
@fushang318 ok

**Comment by bqx619** [comment]
@fushang318 功能完成, https://github.com/sibbay-ai/ms-view/pull/80

**Comment by fushang318** [comment]
已验收
