### ISSUE TITLE
微服务向FC的迁移规范制定

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#8]
小白的所有微服务都会迁移到FC上，那么需要一份可以切实可行的FC服务端开发规范，要考虑的因素：
1、与API gateway的连接；
2、日志；
3、sentry；
4、测试；
5、数据库；阿里暂时还不支持VPC方式，一旦支持则会全面迁移。
6、环境变量
或者其他需要考虑的内容。

采用ICP的方式。
请在这里提交工作量和deadline

**Comment by ax003d** [comment]
这个事我可以做，工作量大概是 1D，截止日期为 2017-11-24

**Comment by georgeliuyu** [comment]
@ax003d 请提供最终文档的目录及简单说明（如果你认为有必要）

**Comment by ax003d** [comment]
@georgeliuyu 这个我可以在动手写之前提供出来

**Comment by georgeliuyu** [comment]
@ax003d 那这个就你做吧， @sinchb 负责验收
@ben7th 是否所有的doc都统一向一个doc repo发pr

**Comment by ax003d** [comment]
@georgeliuyu @sinchb @ben7th 请问这个文档要放在哪个仓库？

**Comment by georgeliuyu** [comment]
@ben7th 是否所有的sr统一建一个doc的repo，你安排一下

**Comment by ax003d** [comment]
@georgeliuyu @sinchb 目录结构如下，看看有什么需要补充的

小白健康阿里云函数计算（FC）开发规范
1 阿里云函数计算（FC）简介
2 开发
2.1 Python 版本
2.2 代码库结构
2.3 与 API Gateway 的通信
2.3.1 event
2.3.2 resp
2.3.3 用户标识的获取
2.4 第三方库的使用
2.5 连接阿里云 Redis
2.6 连接数据库
2.7 参数配置
2.8 单元测试
2.9 日志
2.9.1 logging
2.9.2 sentry

**Comment by sinchb** [comment]
@ax003d 目前没有补充， 👍

**Comment by georgeliuyu** [comment]
@ax003d 
1、添加一个mq（消息队列）的通信方式
2、建议添加迁移的方法，可设为第3章 迁移方法（或者叫迁移注意事项）
比较全面 :+1:

**Comment by ax003d** [comment]
@georgeliuyu 
1. 我们目前的 MQ 方案还没定，这个等 MQ 方案定下来之后，再补充吧
2. 上面的目录是我根据实际的 FC 编写经验总结出来的，迁移这个还没做过，我们可以先增加一个章节，待后续做过一个服务的迁移再补充吧

@ben7th 这个文档应该放在哪个仓库？

**Comment by georgeliuyu** [comment]
@ax00d
MQ和迁移都先列目录。

**Comment by fushang318** [comment]
@ben7th @sinchb @ax003d 
https://github.com/sibbay-ai/sr-wiki  就可以了吧

**Comment by ben7th** [comment]
@ben7th @sinchb wiki 这样也行，不过建议放到 wiki 功能里，比较好做外链

**Comment by sinchb** [comment]
wiki 功能可以提交pr么？建议现在项目中建立文档，提交pr，review，各方comment，等merge之后，再迁移到wiki功能中会比较合适。  @ben7th @georgeliuyu @ax003d

**Comment by ax003d** [comment]
sr-wiki 中的 issue：
https://github.com/sibbay-ai/sr-wiki/issues/21
