### ISSUE TITLE
关于小白文章撰写方面有如下几个疑问，麻烦大家讨论一下

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/public#81]
1.目前相关文章在什么平台发布？小白的微信公众号？
2.关于文章内容，我们是以科普性为主，还是以推广小白或小白的理念为主？
3.文章是什么格式？纯文字？或者图文？如果是图文，图片是需要兼职自行准备还是由你们统一配图？如果是兼职提供图片，牵扯到版权时如何解决？
4.文章如何署名？是统一署名“小白”？或者是兼职自行署名？
5.文章是否有字数限制？最少多少字？
6.如果兼职在其他平台有自己的原创文章，能否直接进行转载？
7.每篇文章是否需要提供参考文献？
8.兼职提交文章后如何进行审核？目前有无审核流程？
9.我们每篇文章的预算大概是多少？

**Comment by fazhen** [comment]
能否对兼职（撰写文章）制定评级和淘汰标准？级别越高的兼职所得报酬相应提高，而差的也必须淘汰，维持与优秀兼职的长期合作。

**Comment by fazhen** [comment]
关于小白的第一篇文章撰写，我原计划是介绍一下国内的移动医疗情况，然后引出小白健康，小白的理念及优势做一个介绍，但是我发现我们官网首页对小白的介绍已经非常详细了？我是否有必要再次以软文的形式进行介绍？或者换一个话题？ @alisahuxu

**Comment by alisahuxu** [comment]
我在官网写的介绍更偏向广告。如果你可以连贯的写一篇文章介绍小白，我觉得是可以的。你先写出来吧~哪怕一个提要也可以~@fazhen

**Comment by fazhen** [comment]
我其实还是有一点不太清楚，以后我们的文章是以科普性为主，还是希望每期都要推广小白健康 @alisahuxu

**Comment by alisahuxu** [comment]
1.目前相关文章在什么平台发布？小白的微信公众号？
答：包括但不限定微信公众号。但都是和小白健康相关的媒体平台。

2.关于文章内容，我们是以科普性为主，还是以推广小白或小白的理念为主？
答：文章的主题由您来定。频率暂定：每月4篇。

3.文章是什么格式？纯文字？或者图文？如果是图文，图片是需要兼职自行准备还是由你们统一配图？如果是兼职提供图片，牵扯到版权时如何解决？
答：文章内容由您来决定，如果有需要配图但没有素材，再联系设计师。

4.文章如何署名？是统一署名“小白”？或者是兼职自行署名？
答：文章署名统一为“小白健康”

5.文章是否有字数限制？最少多少字？
答：文章没有字数限制。给到您之后，烦请代为审核，再给到我最后编辑，推送到微信公众号平台。

6.如果兼职在其他平台有自己的原创文章，能否直接进行转载？
答：如果您看到合适的文章，得到作者允许后，可以转载。

7.每篇文章是否需要提供参考文献？
答：如果有援引的文献，请备注。

8.兼职提交文章后如何进行审核？目前有无审核流程？
答：专业内容审核交由您完成。

9.我们每篇文章的预算大概是多少？
答：每篇文章的内容含金量各有不同，这个我建议和刘总一起开会讨论 。@georgeliuyu

**Comment by georgeliuyu** [comment]
@alisahuxu @fazhen 你发起会议我参加。

**Comment by fazhen** [comment]
经讨论，初步明确：
1.文章撰写每月至少4期，具体排期有我来制定；
2.随时追踪当月热点，提取医学主题，已达到吸引用户的目的；
3.文章原则要求原创，并提供设计参考文献；
4.文章交付后，想由我进行初步审核，之后交付小胡审核 @alisahuxu ，均通过后小把你健康平台进行发表；
5.每篇文章的费用初步设定在150-200之间，具体费用视文章主题及撰写人员情况而定；

**Comment by georgeliuyu** [comment]
@fazhen 讨论不是icp的issue，你可以经过讨论产生出具体任务的icp，如：协作（管理类）、review（评审）、撰写等等

**Comment by fazhen** [comment]
好的 @georgeliuyu
