### ISSUE TITLE
谁能帮我解释一下github中project的作用

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#82]

**Comment by sinchb** [comment]
@georgeliuyu 你是说projects吗？我用这个做跨repo的看板：https://github.com/orgs/sibbay-ai/projects/3?

**Comment by georgeliuyu** [comment]
milestone是针对相同repo下，能通过issue的close体现燃尽状况；而project则支持跨版本的卡片移动，不过要手工移动。对吗？ @sinchb

**Comment by georgeliuyu** [comment]
那么协作更像一个project

**Comment by fushang318** [comment]
@georgeliuyu 缺点是没有燃尽图和 deadline
不过可以自己设置看板 lable ，比如叫做 block 的 lable ，把目前卡主大家工作的 issue 放在那一列，不过这个只是设想    
宋亮是有一些使用经验的，可以听听他的心得

**Comment by ben7th** [comment]
project 可以用来做跨代码库的 issue 管理
但是，无法设置 deadline
这样，实用性上就无法代替里程碑。
特别是使用 codetree 可以做跨版本库的里程碑，project 的意义就变得小了。

**Comment by sinchb** [comment]
@georgeliuyu 只能手动移动，任何一个issue都可以放到看板里
