### ISSUE TITLE
症状审批功能中，增加可以跳过正在审核的草稿的功能

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/public#83]
来自：https://github.com/sibbay-ai/public/issues/74

需要增加一个跳过正在审核的草稿的功能，这个会有后端提供一个API
具体逻辑是：释放掉这个草稿的审核，使草稿变为待审核状态

**Comment by bqx619** [comment]
@fushang318 收到

**Comment by bqx619** [comment]
@fushang318 
关于此点需求有个逻辑问题:
1.审核者点击[跳过] -> 2.调取下一条待审核症状 

在上述中, 当1发生后,调用此API,释放了该条症状
但是并没有记录是谁对这条症状的审核选择了跳过
换句话说,接下来执行2时会把刚刚才跳过的症状再次获取,以致功能失效

是否将后端 跳过 功能的 API 增加返回值, 返回值为跳过该条以后的下一条待审核症状记录

**Comment by fushang318** [comment]
跳过的逻辑确实不太容易自洽，先暂时去掉这个跳过功能，等待症状数据工作人员的使用反馈在考虑如何完善这个功能
