### ISSUE TITLE
症状审批功能中，审核界面增加一种 diff 视图

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/public#84]
来自：#74

症状审批功能中，审核界面增加一种 diff 视图
类似 git diff 显示原始 json 对比

**Comment by bqx619** [comment]
@fushang318 功能按照要求完成, 思考了一下, 选用 table 的形式做 diff, 可能比较易接收
![2018-01-02 8 01 03](https://user-images.githubusercontent.com/9692149/34483428-4ff66b62-eff9-11e7-87f7-9300ad5cb9a1.png)

**Comment by bqx619** [comment]
@fushang318 https://github.com/sibbay-ai/ms-view/pull/80

**Comment by fushang318** [comment]
已验收
