### ISSUE TITLE
症状审批功能中，增加可以跳过正在审核的草稿的后端API

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/public#85]
来自：#74

需要为 https://github.com/sibbay-ai/public/issues/83 提供一个后端API
具体逻辑是：释放掉这个草稿的审核，使草稿变为待审核状态

**Comment by bqx619** [comment]
@fushang318 收到

**Comment by fushang318** [comment]
@bqx619 这个是后端开发，我来做

**Comment by bqx619** [comment]
@fushang318 恩恩, 明白

**Comment by fushang318** [comment]
已经完成，并且部署到了测试环境
API文档：https://sibbayms.docs.apiary.io/#reference/0/audit-syminfodraft/1

@bqx619

**Comment by bqx619** [comment]
@fushang318 收到

**Comment by fushang318** [comment]
该API暂时未用到
