### ISSUE TITLE
官网页面后端修改

### ISSUE THREAD

**Issue by alisahuxu** [sibbay-ai/public#88]
![image](https://user-images.githubusercontent.com/34643533/34428290-16e1723e-ec86-11e7-8195-20a060b2e067.png)
请问，官网页面是哪位制作的，这里信息不全，需要删除。
谢谢~
网址：http://www.sibbay.ai/

**Comment by georgeliuyu** [comment]
@ben7th  @fushang318

**Comment by fushang318** [comment]
@alisahuxu   
这个页面的第一版是 @ben7th 完成的
不过其他前端开发人员也可以修改的  
您的要求是把这些内容删除是吗？需不需要增加其他内容？

**Comment by ben7th** [comment]
@alisahuxu 具体需要删除那些内容，还是全部删除

**Comment by alisahuxu** [comment]
这些全部删除吧，因为点击之后没有链接。 @ben7th

**Comment by ben7th** [comment]
@alisahuxu 好的，我今天（12-29）处理完毕

**Comment by alisahuxu** [comment]
另外还有一个问题：
![image](https://user-images.githubusercontent.com/34643533/34432614-cc30c89c-ecb3-11e7-9d04-1eaf177ee4be.png)
以上这个图片不是我们的二维码，请替换成：
![-](https://user-images.githubusercontent.com/34643533/34433001-0a6ee0d2-ecb7-11e7-8b77-74760a0346ef.jpg)

**Comment by ben7th** [comment]
@alisahuxu 好的

**Comment by ben7th** [comment]
@alisahuxu 已经进行了以下修改：

- 去掉了下方目前多余的文字
- 修改了公众号二维码

**Comment by alisahuxu** [comment]
@ben7th 
能否给我预览一下。我目前登录：http://www.sibbay.ai/
还是原来的样子。
![image](https://user-images.githubusercontent.com/34643533/34472646-6df71f1a-efa1-11e7-9641-6020decf9474.png)

**Comment by fushang318** [comment]
@alisahuxu 这种情况应该是浏览器缓存，强制刷新一下页面应该就可以了

**Comment by alisahuxu** [comment]
OK,我用手机端看到了。谢谢~

**Comment by georgeliuyu** [comment]
@fushang318 @alisahuxu @ben7th 这个应该是个icp issue，怎么没有人标注？
