### ISSUE TITLE
github 贡献者名单管理

### ISSUE THREAD

**Issue by ben7th** [sibbay-ai/public#90]
根据 2017-12-27 立会讨论内容，为了便于今后工作开展，需要整理各个贡献者的 github 账号和姓名的对应，让大家知道今后该去 @ 谁。

名单整理范围：所有有 github 账号的，且通过 github 进行过需求/业务沟通或 ICP 协作/开发的贡献者。

由各个 committer 给出各个贡献值的大致工作内容概括（二十字以内）

统一收集后，由 @ben7th 以 markdown 文档形式在 public 下维护。

- [x] @ben7th 给出目前小程序前端，数据组贡献者的 github 账号，姓名，工作内容概括
- [x] @fushang318 给出运维，管理工具开发相关名单
- [ ] @sinchb 给出后端微服务，MRI 开发相关名单
- [x] 由于运营的同学才开始尝试参与 github 上的沟通，我对他们的账号不太熟悉，能否先由 @georgeliuyu 列出

**Comment by ben7th** [comment]
|github 账号|姓名|工作内容|
|-|-|-|
|@ben7th|宋亮|小程序前端，数据分析，ICP 过程管理 committer|
|@lixinxuan|黎信轩|数据生成工具开发者|
|@arnkorty|符安招|用户社区前端开发者|
|@Yidadaa|张义飞|用户社区前端，健康日记 1.4 版开发者|

**Comment by fushang318** [comment]
|github 账号|姓名|工作内容|
|-|-|-|
| @fushang318 | 李飞 | 后台管理后端开发者，后台管理需求协调，互动脚本开发者，运维 |
| @choufeng | 夏佳 | 后台管理前端开发者 |
| @NiuShy | 牛双雨 | 后台管理前端开发者 |
| @bqx619 | 吴善超 | 后台管理前端开发者 |
| @yeyuexia | 刘卓 | mri 后端开发者 |

**Comment by sinchb** [comment]
@ben7th mri开发由 @georgeliuyu 和 @fushang318 管理

**Comment by sinchb** [comment]
|github 账号|姓名|工作内容|
|-|-|-|
| @sinchb| 陈斌 | 小程序后端开发、维护， |
| @ax003d  | 郑和柳| 社区私信开发者、负责后端Function Server 迁移 |
| @wb14123 | 王斌 |社区后端开发者 |

**Comment by georgeliuyu** [comment]
|github 账号|姓名|工作内容|
|-|-|-|
| @alisahuxu| 胡序| 营运管理 |
| @fangrongxaing| 小嵘|平面设计 |
| @fazhen| 贾发振|医学内容 |
