### ISSUE TITLE
编写并成功运行一个简单的 “hello world” MRI 互动脚本并制作成教程

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/public#95]
需求来源： #66 #71

设法编写并成功运行一个简单的 “hello world” MRI 互动脚本，然后提交 Pull Request 并通过审核（仿真环境），最后把学会的部分制作为视频教程（初级）

**Comment by fushang318** [comment]
给出提交物内容描述和 deadline 吧

**Comment by pimgeek** [comment]
- 提交物内容说明
  - 一段可以在 MRI 仿真器中正常运行的脚本源码（需接收虚拟用户的交互请求，并返回虚拟用户的 ID 信息等），源码在仿真器后台提交 PR 并通过审核。
  - 一份仿真器使用说明，从登录到 PR 审核通过，主要操作步骤都要按顺序记录，并作出必要的说明。
  - 一段 MRI 仿真器使用演示视频（录屏，含语音讲解，带有章节引导页面，参见下方截图）。

size: 2, deadline: 2018-02-09

**Comment by fushang318** [comment]
@pimgeek 2018-02-09？和 size 是不是不协调
要么 size 少了，要么 deadline 写错了吧？

**Comment by pimgeek** [comment]
抱歉，的确是写错了，请以最新评论中的为准。
size: 2, deadline: 2018-01-09

**Comment by fushang318** [comment]
好的 @pimgeek

**Comment by pimgeek** [comment]
@fushang318 最近两天因为一些计划外的杂事，不能及时提交成果，申请修改 deadline，请酌情考虑。
新数值： size 2, deadline: 2018-01-11

**Comment by fushang318** [comment]
@pimgeek 好的  

另外的补充：
1. 建议你以后申请 deadline 时，给自己多留一些余地，宁可第一次就定晚一些，也不要老是改，因为daedline 的变更会影响到相应配合工作的人的工作协调问题，总是改的话，对其他人不好
2. 按照正常流程 deadline 变更超过2天以上，是需要项目经理介入处理的，考虑到你的工作内容特点和目前还不算太影响其他人的工作，这次就算了，下不为例

**Comment by pimgeek** [comment]
@fushang318 我了解了，这次的确对时间估计不足，勉强卡着时间节点完成的。
