### ISSUE TITLE
mri-mri record mlang开发需求规格书

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/public#96]
为实现： #25 
mlang的内容见：https://shimo.im/doc/t9y37ed4Uv0WQV9z   第11章
参见：https://shimo.im/doc/db5na08k2R0yA4qb 写一份需求规格书

请按照icp方式申请

**Comment by ax003d** [comment]
@georgeliuyu 申请开发 Size：1 Deadline：2018-1-5

**Comment by ax003d** [comment]
@georgeliuyu 需求规格书见：https://shimo.im/docs/KRue04uBzcUgsCF3

**Comment by ax003d** [comment]
@georgeliuyu 这个可以关闭了

**Comment by georgeliuyu** [comment]
@ax003d 这个要与pr放到一起

**Comment by ax003d** [comment]
@georgeliuyu 好的，我下次注意

**Comment by georgeliuyu** [comment]
@ax003d 你要加上去，否则统计不到。

**Comment by ax003d** [comment]
@georgeliuyu 好的，加了。

**Comment by fushang318** [comment]
@ax003d 这样还是统计不到，统计条件
1. issue 有 ICP 和 SIZE 标签
2. 有PR 关联了这个 issue
3. PR 的 git commit message 中关联了这个issue

第三点你没满足，这样统计不到工作量...

**Comment by ax003d** [comment]
@fushang318 可是这个 commit 已经 merge 了，这要怎么处理？

**Comment by fushang318** [comment]
@ax003d 我建议在提交一个PR，内容可以是多一个空格，少一个空格啥的，或者完善一下注释

**Comment by ax003d** [comment]
@fushang318 那我在下一个 commit 和 PR 关联那个 issue 吧。
